### ISSUE TITLE
Minify and compress the demo

### ISSUE THREAD

**Issue by MaxMilton** [epicmaxco/vuestic-admin#10]
I had a quick look at your demo site and... **holy crap I just loaded 10 MB** of data for a single web page!!

You've clearly put in the effort with the dashboard; it looks very nice, but forcing a user to download 10 MB is like a slap to the face. Please compress the images, minify and compress the JS + CSS. You can automate it via a proxy such as [Cloudflare](https://www.cloudflare.com) or [mod_pagespeed](https://developers.google.com/speed/pagespeed/module/) or you can incorporate these steps into your build pipeline.

**Comment by smartapant** [comment]
@MaxMilton yep, that's our bad, thanks! 

We'll be fixing that

**Comment by smartapant** [comment]
@MaxMilton that's happens to huge images size - I'm using some Instagram snaps for dashboard widgets. Will use lighter versions of them
