### ISSUE TITLE
Keyboard with vuestic-simple-select and vuestic-multi-select

### ISSUE THREAD

**Issue by salehis** [epicmaxco/vuestic-admin#100]
Hello, I saw this topic was closed. Sorry for bad English.
Is it possible to see select tag in this awesome theme.
Thnx

**Comment by jean-moldovan** [comment]
How about `vuestic-simple-select` component ?

See https://github.com/epicmaxco/vuestic-admin/wiki/Selects

**Comment by salehis** [comment]
Thank you for reply.  I saw this select from link but it does not behave as classic select would.
It does not open on focus and arrow up and arrow down keys + enter is not supported.
You have to control it with mouse. Can you please give me any hint. I need this feacure to work completely with keyboard using tab, arrow up/down and enter.

Thank you for quck reply once more.

**Comment by salehis** [comment]
Can you please give me any hint how to modify this if possible, or are you planning to do something similar

**Comment by jean-moldovan** [comment]
Our template is based on Bootstrap, so I think you should be able to use default Bootstrap Select form control

https://getbootstrap.com/docs/4.0/components/forms/#form-controls

**Comment by salehis** [comment]
Thnx. I will figure out something. Yes i can use default Bootstrap Select but it is not fitted in your theme as i would like . I was wonderind if there is a way to modify your current select in way it respondes to tab and arrow keys + enter instead of mouse click.
Thanks anyway.

**Comment by salehis** [comment]
By the way theme is awesomev and FREE.
Thanks again

**Comment by whoan** [comment]
@salehis You can attach a `keyup` event listener in the select component and check the pressed key to make it work as you expect. Look at this commit for a reference: https://github.com/epicmaxco/vuestic-admin/commit/8aa4b94c782f8f5d3651b59abd4db350f9b98526

**Comment by salehis** [comment]
Thank you very much. This is helpful. Wish you all the best
