### ISSUE TITLE
Bug scroll Firefox in select

### ISSUE THREAD

**Issue by Xeyos88** [epicmaxco/vuestic-admin#103]
After the first selection in a select, the scroll doesn't work anymore. This only in Firefox.

**Comment by whoan** [comment]
I can confirm this behaviour. I'm using FF 58.0.2.

**Comment by smartapant** [comment]
@whoan @Xeyos88 thanks, will have a look

**Comment by whoan** [comment]
@smartapant The only hint I have for now, is that it happens when you call `erd.removeAllListeners` in VuesticScrollbar.vue . If you comment that line, it works again.

If I have time, I can dig into it to see what is happening.

**Comment by Xeyos88** [comment]
Good, it works. Thx.
