### ISSUE TITLE
wow. no dark version?

### ISSUE THREAD

**Issue by ahakobyan79** [epicmaxco/vuestic-admin#1035]
Cool template. just too bright.

**Comment by asvae** [comment]
Hey, you can find theme switch in [settings](https://admin-demo.vuestic.dev/settings).

We didn't move it to some prominent place as we tried to make admin more similar to real app.

![image](https://github.com/epicmaxco/vuestic-admin/assets/5394573/89f98e50-5ad7-4e62-9dc5-a85570fbf4bb)

![image](https://github.com/epicmaxco/vuestic-admin/assets/5394573/b42827dd-6a54-4cd6-b561-c322c1477991)
