### ISSUE TITLE
Hello author, I want to ask is this framework commercially available

### ISSUE THREAD

**Issue by Rose1AND25** [epicmaxco/vuestic-admin#1048]
I want to ask is this framework commercially available.Are there copyright issues if this framework is used commercially?

**Comment by rajithaeyee** [comment]
@Rose1AND25 https://github.com/epicmaxco/vuestic-admin/blob/master/LICENSE this license says you can.

**Comment by asvae** [comment]
Hey, you can use it commercially without limitations.
