### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by NikitaLiashenko** [epicmaxco/vuestic-admin#11]
Great repo with lots of useful component.

Unfortunately it's almost useless due to lack of documentation.
Please, add documentation.

**Comment by smartapant** [comment]
@NikitaLiashenko many thanks! Indeed, documentation is really needed. It's one of out priorities, but we need some more time. Right now, all our custom components lie inside vuesptic-components/ folder and each page has examples of components' usage

**Comment by smartapant** [comment]
@NikitaLiashenko https://github.com/epicmaxco/vuestic-admin/wiki

**Comment by NikitaLiashenko** [comment]
@smartapant Looks nice. Thanks
