### ISSUE TITLE
How to make the side bar and nav bar fixed in position?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#116]
When scrolling down a page, the sidebar and the top nav bar are hidden up in the view. How to keep them in view even during scrolling?

**Comment by smartapant** [comment]
@harishankards is it urgent? I could experiment and tell you quick steps or I could develop new layout class with fixed elements this week, so it will e even easier for you to implement. What suits you best? :)

**Comment by harishankards** [comment]
Hey @smartapant! Thanks for the reply. It's kinda urgent. If that quick workaround doesn't disturb the other elements, please let me know the steps. Else, I choose to wait for the new layout. :)

**Comment by harishankards** [comment]
Hey @smartapant,

just wanted to check whether do I have any updates on this.

**Comment by smartapant** [comment]
@harishankards hey!

In 1-2 hours :)

**Comment by smartapant** [comment]
@harishankards quick and dirty solution:

* Layout.vue. Add this style to .content-wrap:
    `padding-top: 0;`
* _base.scss. Add this style to body:
    `padding-top: $sidebar-top;`
*  Navbar.vue. Add these styles to .navbar.app-navbar:
    ` position: fixed;
       top: 0;
       width: 100%;
       z-index: 1;`
* Sidebar.vue. Add this style to .sidebar:
   `position: fixed`

Must work :)

**Comment by harishankards** [comment]
Hey @smartapant ,
Thanks a lot. It worked. But please release new layout class as the permanent solution for the longer run.

**Comment by smartapant** [comment]
@harishankards no problem!

Created #138

**Comment by harishankards** [comment]
@smartapant, as you said it's dirty only. With this quick workaround implemented, the auth pages: signup and login getting blank headers space on the top. I guess it's due to this: 

change in src/sass/_base.scss  
  padding-top: $sidebar-top;

Waiting and hoping for a permanent fix :)
