### ISSUE TITLE
Date and time pickers

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#117]
[Design](https://cdn.zeplin.io/5a5e24188993724b2abfc6a9/screens/2970BD44-B401-4770-ACEF-9959B2835B17.png), the detailed mockup can be found in Zeplin (for team members)

Datepickers must be placed on Form Elements page in a separate widget. Also, of course, they're reusable vuestic-components with v-model and stuff.

Known issues:

- [x] padding right is strange (no repro)

**Comment by asvae** [comment]
@xx13 we also probably require styling for **today**. Any idea on how to implement (and be consistent with ranges etc)?

**Comment by smartapant** [comment]
@asvae please extract datepicker safari selection as a separate issue

**Comment by smartapant** [comment]
@xx13 i'll be closing the issue along with 1.6.0 milestone.

Please review current version of datepickers and create a separate issue for 1.7.0 milestone
