### ISSUE TITLE
Keyboard with vuestic-simple-select and vuestic-multi-select

### ISSUE THREAD

**Issue by MPrtenjak** [epicmaxco/vuestic-admin#12]
There is no keyboard support with ‘select’ components so they are pretty much hard to use even with prepared examples. 

It is much easier to select a country by typing SLO (or something) than scroll down to character S.

**Comment by smartapant** [comment]
@MPrtenjak in progress)

**Comment by vvscode** [comment]
Looks like it worth to add optional ability to type inside the input and filter options based on entered text (outside of the select-component) - it will be the most flexible way

@MPrtenjak  @smartapant  are you agree?

**Comment by vvscode** [comment]
@georgeMuraveiAlkh  are you still working on it?

**Comment by smartapant** [comment]
@vvscode nope

**Comment by nathanbrizzee** [comment]
I too would really like to see this enhancement.

**Comment by jean-moldovan** [comment]
@vvscode , you mean autocomplete input? Well, that would be another element.

**Comment by vvscode** [comment]
so what kind of behavior is expected? Cause I thought it would be like filtering event (if you enter text you got filtered list)

**Comment by jean-moldovan** [comment]
This is an example of how native select works in the browser: https://html.com/tags/select/

Basically, once element is focused, you could press 'Arrow-Down' to open it and then 'j' to jump to an option that starts with a 'j'. When you press 'Enter' option is selected.

**Comment by jean-moldovan** [comment]
Will consider adding this to our roadmap. Thanks everybody for your feedback!

**Comment by salehis** [comment]
Awesome theme. Adding <select> tag would be realy helpful. Hope to see it soon
