### ISSUE TITLE
Range slider

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#123]
Make range slider a reusable vuestic-component

The range slider exists on the Icons page, the code might be extracted from this PR https://github.com/epicmaxco/vuestic-admin/pull/77 (see vuestic-slider)

**Comment by yevdyko** [comment]
@smartapant I've already done it. Can I add it as a separate PR from the customizing Spinners?

**Comment by smartapant** [comment]
@yevdyko thanks! Will check it today
