### ISSUE TITLE
Add customization controls to Spinners page

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#124]
[Design](https://cdn.zeplin.io/5a5e24188993724b2abfc6a9/screens/15251BCC-0175-4D11-9E52-117DDF586AAC.png)

Use vuestic-slider and vuestic-color picker

**Comment by yevdyko** [comment]
@smartapant I'm going to close the issue this week and then extend `Color Pickers` components related to the #118.
