### ISSUE TITLE
Documentation - tooltips and popovers

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#126]
Documentation on tooltips and popovers is required for our [wiki](https://github.com/epicmaxco/vuestic-admin/wiki)

**Comment by motatoes** [comment]
I would like to work on this, should I make a new section under UI Elements called "notifications" ?

**Comment by asvae** [comment]
@motatoes Sure!

**Comment by asvae** [comment]
See https://github.com/epicmaxco/vuestic-admin/wiki/Tooltips-and-Popovers
