### ISSUE TITLE
Sample axios integration

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#131]
Sample [axios](https://github.com/axios/axios) integration is needed.

May be done together with file upload component #119 

TODO Issue needs more implementation details.

**Comment by Vad1mo** [comment]
Suggestion to use https://christianmalek.github.io/vuex-rest-api/ as it works on top of axios and is convenient. 

Example:
```js
import Vapi from 'vuex-rest-api'
import axios from 'axios'

Vue.use(Vuex)

const tenants = new Vapi({
  baseURL: '/api',
  state: {
    tenants: [],    
  }
})
  .get({
    action: 'ALL_TENANTS',
    property: 'tenants',
    path: '/tenants'
  })
  .get({
    action: 'getTenantById',
    property: 'tenant',
    path: ({ id }) => `/tenants/${id}`
  })
  .getStore()
```

**Comment by ssemenkoff** [comment]
Axios is already used in one of Data Tables. I believe this will should be enough for sample since further deeping in axios api would be nothing more than rewriting their docs.
