### ISSUE TITLE
In css fix hover or active colors.

### ISSUE THREAD

**Issue by 4iloveg** [epicmaxco/vuestic-admin#140]
Maybe I should make the selection a bit different

![image](https://user-images.githubusercontent.com/19300333/38023728-bb86d18a-328b-11e8-9866-096b8f746951.png)

**Comment by smartapant** [comment]
@xx13 what do you think?

**Comment by xx13** [comment]
@4iloveg @smartapant 
Thanks for sharing your thoughts! 
I'd suggest using a slightly lighter background than the one used for active and hover states. That way you will add an extra style to a level 2 section and keep the current logic of hover & active states.

**Comment by smartapant** [comment]
@4iloveg will add it to the next milestone, thanks)
