### ISSUE TITLE
Why nav and sidebar is embedded into view when creating a new component ?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#153]
I created a component here: src/components/landing/Landing.vue. I set up the route for it and when I viewed that component in the browser, it's surrounded by navbar and sidebar. Whereas, I want to achieve a page with my own design. Please suggest how would I do that?

Also, if I add an item to the sidebar, the item is displayed as if it's active. But it's not, what class I should use. Please suggest.

**Comment by harishankards** [comment]
@smartapant and team. Any updates on this?

**Comment by asvae** [comment]
@harishankards the fastest (hackiest way) would be to add another check to App.vue.

Something like should work for you.

```javascript
 computed: {
  isLading () {
    return this.$route.name === 'landing'
  }
  // ...
```

Other than that, I created a separate issue for the bug. https://github.com/epicmaxco/vuestic-admin/issues/154

**Comment by harishankards** [comment]
Thanks @asvae !
 I'll try that out. Before that, I have a quick question. The navbar and sidebar are not visible in auth/login and signup. How that works fine?

**Comment by asvae** [comment]
You can use named route and check its name.

> this function
Which one?

**Comment by harishankards** [comment]
@asvae 
Ok. I created a  named route in /router/index.js 
```
export default new Router({
  routes: [
    ...generateRoutesFromMenu(menuModule.state.items),
    {path: '*', redirect: { name: getDefaultRoute(menuModule.state.items).name }},
    {path: '/', component: landing, name: 'landing'}
  ],
  mode: 'history'
})
```
Then in App.vue,
I added the condition
`    <landing v-else-if="isLanding"></landing>`
and the function
```
      isLanding () {
        return this.$route.name === 'landing'
      }

```

But it's still showing me the landing component surrounded by nav and sidebar. What am I missing here? Please help.

**Comment by asvae** [comment]
@harishankards can you check?

```javascript
console.log('this.$route.name', this.$route.name)
```

**Comment by harishankards** [comment]
@asvae all I have to do is change the name to 'Landing' as below :rofl: 
```

      isLanding () {
        return this.$route.name === 'landing'
      }
```

**Comment by harishankards** [comment]
@asvae 
I have one more query to address, so for now I have defined landing page router be like:
```
router/index.js:
export default new Router({
  routes: [
    ...generateRoutesFromMenu(menuModule.state.items),
    {path: '*', redirect: { name: getDefaultRoute(menuModule.state.items).name }},
    {path: '/', component: landing, name: 'landing'}
  ]
})
```
And I deleted the file I created in `/src/store/modules/menu/landing.js` as I thought I have defined directly and I don't want `landing page` to sit in the side bar.
Then when I tried to run the project, I was receiving an error as name undefined in `router/index.js`. Any idea why?

**Comment by asvae** [comment]
@harishankards 
>  I was receiving an error as name undefined in router/index.js

I don't get it. Please elucidate.
