### ISSUE TITLE
How to add round images?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#156]
Hi, I'm trying to create a LinkedIn kinda social network using vuestic theme. The vuestic feed is just awesome. 

I want to use the round photo container of vuestic feed alone for the newsfeed titles. How do I achieve that? Please help

**Comment by asvae** [comment]
Copypaste some sass : 3

```sass
      .photo-container {
        margin-right: 1rem;
        border-radius: 50%;
        border: 2px solid gray;
        .photo {
          background-size: cover !important;
          width: 3rem;
          height: 3rem;
          border-radius: 50%;
        }
      }
```
