### ISSUE TITLE
How to add multiple line contents to vuestic-feed responsively?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#157]
Right now, with vuestic-feed, I'm able to have single line description without disturbing the responsiveness.
But, in my use case, I want to display the description in multiple lines without burying them in a single line using the ellipsis. How can I achieve that?

**Comment by asvae** [comment]
For text container:

```sass
min-height: 3.5rem;
height: inherit;
```

For text itself: 
```sass
 white-space: inherit;
```

**Comment by harishankards** [comment]
Worked thanks @asvae
