### ISSUE TITLE
Arabic and RTL support

### ISSUE THREAD

**Issue by amralii** [epicmaxco/vuestic-admin#158]
Does such template support Arabic or RTL ?

**Comment by smartapant** [comment]
@amralii we're using vue-i18n, check out https://github.com/kazupon/vue-i18n/issues/182

**Comment by majebry** [comment]
I'm thinking of forking the repo trying to support RTL, it hasn't done before?

**Comment by amirh95** [comment]
Any plans to add RTL support?
Not the locale and translate, the UI components I mean.
