### ISSUE TITLE
How to bring blinking cursor by default in medium editor?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#161]
Hi team,

The vuestic medium editor is great and I'm using it. Right now, 

- the `data-placeholder` starts from the centre and not the left side.
- I would like to have a blinking cursor with the placeholder to be shown before the user types something
- Also, whatever we type start from the centre of the widget, how do I take it to left side?

**Comment by harishankards** [comment]
Also, the content I enter in the editor is going out of the component:
![image](https://user-images.githubusercontent.com/5006693/38655264-5024adb6-3e31-11e8-85ba-0234194e974a.png)

**Comment by pfrohner** [comment]
@harishankards for the alignment issues, compare your code with the original, none of the issues you mention happens so my guess would be something went wrong with your implementation...or you use IE8 :-D

for the blinking cursor modify "highlightSampleText" function a bit

```javascript
      highlightSampleText () {
        let sampleText = document.getElementsByClassName('default-selection')[0]

        if (sampleText) {
          this.editor.selectElement(sampleText)
        } else {
          this.editor.elements[0].focus()
        }
      }
```
