### ISSUE TITLE
How to bring multiple children under /src/store/modules?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#165]
Hi,

For my project, there will be multiple roles, say student and company. So, what I thought is entirely having two set of things in components and store modules.

So, inside `src/components`, I created two folders `src/components/company` and `src/components/student` and kept the related components under that.

Like that, I wanted to have multiple modules for both as the sidebar items will have different things. So, I changed `/src/store/modules/menu/` into two: `/src/store/modules/company/menu/` and `/src/store/modules/student/menu/`.

I changed the store file and all accordingly. But, I receive an error from Layout.vue due to breadcrumbs, as I am stuck and confused about how to change that in getters.js
```
Errors:
1. Cannot read property 'menu' of undefined | studentMenuItems (getters.js?c729:3)
2. TypeError: Cannot read property 'menu' of undefined |  VueComponent.breadcrumbs (Layout.vue?9bde:51)
```
below is my getters.js, please direct me how to make this work or is there a better way to solve my use-case. Please let me know.

```
import utils from 'services/utils'

const studentMenuItems = state => state.student.menu.items
const companyMenuItems = state => state.company.menu.items
const sidebarOpened = state => state.app.sidebar.opened
const toggleWithoutAnimation = state => state.app.sidebar.withoutAnimation
const config = state => state.app.config
const palette = state => state.app.config.palette
const isLoading = state => state.app.isLoading
const breadcrumbs = state => {
  return (keyword) => utils.findInNestedByName(state.menu.items, keyword)
}

export {
  studentMenuItems,
  companyMenuItems,
  toggleWithoutAnimation,
  sidebarOpened,
  config,
  palette,
  isLoading,
  breadcrumbs
}

```

**Comment by harishankards** [comment]
So @asvae when will I get my answer? ;)

**Comment by asvae** [comment]
I'd say, at best, wednesday. I'm not a vuex guy. And colleagues are on vacation.

**Comment by harishankards** [comment]
Great! Thanks for the update @asvae. Looking forward :)

**Comment by harishankards** [comment]
Hi @asvae! Just wanted to quickly check whether do I got any updates?

**Comment by asvae** [comment]
The easiest solution would be to keep routes linear, and just add role via meta.

Other than that you probably want to throw away vuestic routing and do one by yourself at this point.

**Comment by harishankards** [comment]
@asvae 
I understand. In my case, student role will have set of different sidebar items and company will have a different set.
Say, if I define 
```
meta: {
'role': 'student' // for student and company for companies
}
```
 in modules/menu/*js, how do I show the side bar items according to roles? Can you help me out in this?

**Comment by asvae** [comment]
Probably the same as you did previously with alternate layout? Via `v-if` : 3.

**Comment by harishankards** [comment]
@asvae 
That I understood. I know to change the layout. But I'm having doubt on how do I handle the sidebar items?

**Comment by asvae** [comment]
If you need different sidebars depending on permissions / role, I would recommend to decouple sidebar and routes.

More like create separate config, something like this: 

```javascript
const studentNavigationRoutes = [
  {name: 'product', icon: 'student'},
  // ...
]
```

Then toss it into sidebar
```html
<your-sidebar :config="studentNavigationRoutes">
```

This will get you some decoupling (fresh air) for your app to grow.

Trying to hack vuestic-sidebar won't get you far as it's tightly bound to router.

**Comment by harishankards** [comment]
Hey,

I found one method. What I'm doing is, in the sidebar.vue, I'm using v-show to change the sidebar items.

If the role is a student, I'll use the default one (menuItems) provided by you. If it is a company, I'll change the menu items to the list of items created by me.

Works for me.

Thanks @asvae for your help
