### ISSUE TITLE
How to add a button in the table

### ISSUE THREAD

**Issue by AmoSunsh1ne** [epicmaxco/vuestic-admin#169]
use this
<vuetable
          ref="vuetable"
          :apiUrl="apiUrl"
          :apiMode="apiMode"
          :httpFetch="getList"
          :fields="tableFields"
          :data="list"
          dataPath="data"
          :perPage="perPage"
          :paginationPath="paginationPath"
          @vuetable:pagination-data="onPaginationData"
        />
Add a column titled Operation with the button inside

**Comment by smartapant** [comment]
@AmoSunsh1ne also i've added `additionalTableControl` slot for adding custom controls next to 
`per page` buttton.
