### ISSUE TITLE
npm NOT install in windows10

### ISSUE THREAD

**Issue by IRIP** [epicmaxco/vuestic-admin#174]
`(venv) C:\pycharm\duty\web>npm install
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
npm ERR! code 128
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\irip\AppData\Roaming\npm-cache\_logs\2018-04-18T15_13_02_007Z-debug.log

(venv) C:\pycharm\duty\web>
`

**Comment by asvae** [comment]
> Maybe git-submodule is broken?
Have you checked?

We had no trouble installing vuestic on a number of environments (win 10, ubuntu, ios).

**Comment by sebyul2** [comment]
Packages using the git submodule command appear to exist. Make sure that git is installed properly in the terminal environment you have run.
