### ISSUE TITLE
Dynamic paths (aliases, dynamic requires)

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#177]
* This applies only to internal component hadling. Presentation componets should have shortened routes. We do not expect our users to operate IDE effectively or even own one.
* For our internal component hadling, relative routes kill IDE support for file operations. Most notable: navigation, move file, find usages. We should use relative paths everywhere.

- [ ]  **Router**

**Is:**
```javascript
{
  name: 'TreeView',
  path: '/ui/tree-view',
  component: lazyLoading('ui/tree-view/TreeView'),
  meta: {
    title: 'menu.treeView'
  }
},
```

**Should be:**
```javascript
{
  name: 'TreeView',
  path: '/ui/tree-view',
  component: () => import('../../../components/ui/date-time-pickers/DateTimePickers.vue'),
  meta: {
    title: 'menu.treeView'
  }
},
```
- [ ]  **Charts.vue**
- [ ]  **Check other places and add them to this issue**

**Comment by pfrohner** [comment]
@asvae why require instead of import?

**Comment by asvae** [comment]
@pfrohner because derp. Thanks for noticing.

**Comment by smartapant** [comment]
@asvae that's arguable, i really hate relative paths and already had a problem while doing project restructure

**Comment by asvae** [comment]
Fixed already.
