### ISSUE TITLE
Refactor sidebar

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#189]
* Make sidebar independent from store by passing sidebar-items via properies
* move sidebar to `vuestic-components` folder, rename it to `vuestic-sidebar` and add `vuestic-sidebar` css classes
* sidebar that will be used in the application must be wrapped into `app-sidebar` component with menu-items prefilled, must be stored inside `layout/app-navbar` folder
* move all vuex/toggle logic into app-sidebar component

**Comment by asvae** [comment]
I suggest to handle sidebar close/open state from layout component.
