### ISSUE TITLE
Easy REST api hooks

### ISSUE THREAD

**Issue by scottsanchez** [epicmaxco/vuestic-admin#19]
Consider adding an easy way to tie in to REST apis the way "admin on rest" dashboard does! 

Reference: https://github.com/marmelab/admin-on-rest

**Comment by smartapant** [comment]
@scottsanchez thanks, we'll have a look)

**Comment by jean-moldovan** [comment]
Will consider adding this to our roadmap. Thanks @scottsanchez !

**Comment by harishankards** [comment]
Hey @jean-moldovan,
Is there any update on this?
