### ISSUE TITLE
Vuestic-wizard vertical has buttons aligned in separate line instead of inline

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#191]
Hi,

I'm using vuestic-wizard in a vertical manner, the navigation buttons `back` and `confirm` are aligned in separate lines instead of being it in a single line.

Please refer the below screenshot.
![image](https://user-images.githubusercontent.com/5006693/39612022-6c74eb6c-4f79-11e8-9b59-ca89e0627d78.png)

**Comment by harishankards** [comment]
@pfrohner or @asvae, can you shed some light here? Sorry for tagging thought

**Comment by asvae** [comment]
Screen too small, no?

Here's the one from demo. https://i.imgur.com/2ADxh9y.png

**Comment by harishankards** [comment]
Oops. Now it works fine with col-md-12. But, even when I'm using col-md-10, it switches back to vertical view :(

**Comment by smartapant** [comment]
@harishankards it seems that the width of wizard's content is way too narrow

**Comment by harishankards** [comment]
Nope @smartapant , if you want I can take full page screenshot. There is nothing on the screen, other than this except sidebar. And why the input fields are having very short width? Am I doing wrong something here?
Please help

**Comment by asvae** [comment]
Check style block in form wizard.
You can do something similar for your page.
```
  .form-wizard-page {
    .form-group {
      min-width: 200px;
      max-width: 360px;
      width: 80%;
    }
  }
```

**Comment by harishankards** [comment]
@asvae , I dont' find a file called `FormWizard.vue`

My version is `1.4.0`

**Comment by asvae** [comment]
Could be `form-wizard-page` Presentation component with wizards basically.

**Comment by harishankards** [comment]
Yes,

It is `form-wizard-tab-content` and it's not helping. :disappointed:
