### ISSUE TITLE
How to reproduce the new rolled out features in my project?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#192]
Hi,
I have developed a lot of things over the vuestic-admin. Now, I want the latest features, without disturbing my components and functionalities. How would I do that? Won't git pull spoil mine?

**Comment by smartapant** [comment]
@harishankards which version are you using?

**Comment by harishankards** [comment]
@smartapant, I typed `vuestic --version` in my terminal and got `0.1.1`.

Is this how I need to check the version? I installed 2 months back only.

**Comment by harishankards** [comment]
Hi @smartapant, just wanted to check whether have you had a chance to look into this.

**Comment by smartapant** [comment]
@harishankards please check package.json file :)

**Comment by harishankards** [comment]
Oh, thanks! Mine is 1.4.0 @smartapant.

**Comment by smartapant** [comment]
Duplicate of #204
