### ISSUE TITLE
How to change the spinner on page load?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#196]
Hi guys,

Currently, I'm seeing V-shaped spinner on page load. How do I change it, as per this [page](http://vuestic.epicmax.co/#/ui/spinners)? I see that the docs are missing for that. 
Looking for the solution

**Comment by AngeloAnolin** [comment]
That v-shape component is on the [VuesticPreLoader.vue](https://github.com/epicmaxco/vuestic-admin/tree/master/src/vuestic-theme/vuestic-components/vuestic-preloader) component.

Specifically, you may want to play around with the draw() method so you can change it to the epic spinner you have mentioned.

**Comment by harishankards** [comment]
Thanks, @AngeloAnolin !
