### ISSUE TITLE
Content is moving around in menu when opening submenus

### ISSUE THREAD

**Issue by pfrohner** [epicmaxco/vuestic-admin#198]
When the sidebar is longer than the content area, the menu moves up/down a few pixels when opening/closing menu items:

https://www.screencast.com/t/Ga70hYAcYB

**Comment by smartapant** [comment]
Hi @pfrohner 

Thanks for submitting the issue. The scroll we use is strange to be honest :( Will add the label to this bug but i'm not sure when we'll be fixing it - little bit secondary and might require much work

**Comment by asvae** [comment]
Likely not an issue in 2.0. Sidebar is overhauled.
