### ISSUE TITLE
Progress bar improvements round 2

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#199]
## Remake interface

Check [bootstrap progress bars](https://bootstrap-vue.js.org/docs/components/progress/) for reference.

Props:

- [x] value - percent value
- [x] color - color
- [x] size - ['default', 'thin', 'thick,]
- [x] disabled - disabled
- [ ] text - string, will be shown instead of percent value on top of progress bar. In case you want to override defaults.
- [x] remove refs

## Remake internals

- [x] Use more specific selectors (`.progress-bar.progress-bar-thin` instead of `.progress-bar.thin` f.e.)
- [ ] Use [css animation](https://www.w3schools.com/cssref/css3_pr_animation.asp) for blinking.
- [ ] Remove style blocks from presentation components.

## Presentation

- [ ] Colorful Progress Bars 100% filled from the very beginning

**Comment by omrihar** [comment]
I was about to create a new issue, but perhaps it fits here - it seems that the `CircleProgressBar` has a `min` and `max` props, but they are completely ignored by the implementation. I would expect the progress bar to automatically calculate the percentage of `value` from these values, but this doesn't seem to be the case. Also, what do you think about not hard coding the `%` symbol into the display? This way one could use the progress bar to display a percentage using the progress display, but also let it display the absolute value of the number (which is not a percentage).

**Comment by asvae** [comment]
@omrihar Thanks, I added this to issue as an optional prop `text`. Will allow to write your own value or even disable.
