### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by eminpala** [epicmaxco/vuestic-admin#20]
We couldn't make it work.  Please see below.
----------------------------------
`$ npm run dev

> vuestic-admin@1.0.0 dev C:\Users\Admin\Desktop\Temp\vuestic-admin\vuestic-admin
> node build/dev-server.js

(node:21536) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
 ERROR  Failed to compile with 1 errors1:56:38 PM

This dependency was not found:

* vue-slider-component in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/ui/icons/Set.vue

To install it, you can run: npm install --save vue-slider-component
> Listening at http://localhost:8080
`

**Comment by travisrussi** [comment]
In `src/components/ui/icons/Set.vue` change line 46 from:

```
  import Slider from 'vue-slider-component'
```

to this

```
  import Slider from 'vue-slider-component/src/vue2-slider.vue'
```

**Comment by alexanderrudnik** [comment]
@travisrussi thank you for help
