### ISSUE TITLE
Upgrade from 1.4.0 to 1.5.0

### ISSUE THREAD

**Issue by cowboy93** [epicmaxco/vuestic-admin#204]
I'm developing our site with vuestic-admin. 
It is very powerful framework. 

I found it is upgraded 1.5.0.

How can I upgrade my 1.4.0 based project ? ? ? 

Please help ~

**Comment by smartapant** [comment]
@cowboy93 this week 1.6.0 will be released, i will try to create a guide after that :)

**Comment by cowboy93** [comment]
Thank you very much ~ 
I will wait for that !

**Comment by harishankards** [comment]
Hey @smartapant, just wanted to check whether do I have got any updates. Looking forward

**Comment by smartapant** [comment]
@harishankards sorry, we've missed this one in the end :( 1.7.0 is out, do you still need the guide?

**Comment by cowboy93** [comment]
Yes please ~~~

**Comment by harishankards** [comment]
@smartapant that's okay. But we really need it :D

**Comment by motatoes** [comment]
This would be really helpful since I am faced with the same situation. There are some updates such as the Toast Notification that I would like to add to my project but there is no straightforward way to upgrade the Vuestic version since the project contains the vuestic source.

I think we should be able to install Vuestic as an external npm package since that will enable us to upgrade with ease ..

**Comment by itmonk** [comment]
thanx for the tool. but an ability to upgrade the vuestic base code to next version without affect own code it's necessary feature. what the way you suggest to do it now? is there any approach for this?

**Comment by smartapant** [comment]
@cowboy93 @motatoes @itmonk @harishankards 
here's the commit that has all diffs between 1.4.0 and 1.8.1 https://github.com/smartapant/vuestic-admin/commit/b6381c1cf86df0ac2c3619a35a25509e3836483c

Also you'll need to:
```bash
$ npm install -g @vue/cli
$ npm install
$ npm run serve
```

**Comment by Nataliia-Radina** [comment]
Hi! So how actually to update versions?
My project is still at 1.5.0

**Comment by Hawzaz** [comment]
Hello
My project is 1.7 and i would like to upgrade to 2.0, did you finally wrote the guide somewhere ? What are the steps needed to upgrade ?

Thank you project is awesome ~
