### ISSUE TITLE
Where can I find VuesticTreeRootMapper.js?

### ISSUE THREAD

**Issue by The-BlackWidow** [epicmaxco/vuestic-admin#206]
Hi @asvae ,

I am trying to reproduce the README you have just released on the  TreeView component, however I can't find the mapping component. Is it on purpose?

**Comment by asvae** [comment]
Are you looking [here](https://github.com/epicmaxco/vuestic-admin/wiki/Tree-view)? Mapper was in first version. Not in current one.

**Comment by asvae** [comment]
Load current version of admin panel and check examples (src/components/ui/tree-view/TreeView.vue). Basically you just stack them together in html.
