### ISSUE TITLE
vuestic-select enhancements

### ISSUE THREAD

**Issue by AngeloAnolin** [epicmaxco/vuestic-admin#208]
Some enhancements that I could think for the vuestic-select component:
![vuestic-select](https://user-images.githubusercontent.com/1944084/39827729-13797d7e-5376-11e8-9156-7a2fe9839ff2.PNG)

1. Display of vertical scrollbars to denote that there are more items on the list.
2. Possibility of providing an option to specify number of items to be displayed.
3. Auto-scroll when typing the first letter in the select list.
4. Allow keyboard navigation to go up and down the select list.

**Comment by smartapant** [comment]
@AngeloAnolin thanks, will include in one of the milestones

**Comment by vlad-shusterman** [comment]
1) Done
2)You can change ites per page yourself in styles
![2018-06-14 (2).png](https://images.zenhubusercontent.com/5acb54934b5806bc2bce429b/86ba62e6-1577-4f49-8175-58012ec99a1b)
3)Done 
![2018-06-14 (3).png](https://images.zenhubusercontent.com/5acb54934b5806bc2bce429b/99094e8f-65f0-4082-a0e7-dc221a1fbf11)
4)Added next miliestone
