### ISSUE TITLE
Error in some props or computed properties

### ISSUE THREAD

**Issue by jesus9ias** [epicmaxco/vuestic-admin#21]
I get a warning when VueTable loads

[Vue warn]: The computed property "fields" is already defined as a prop.

Exactly here:
\node_modules\vuetable-2\src\components\Vuetable.vue

Of course I see a prop, but not the computed property, how can I solve this?

**Comment by alexanderrudnik** [comment]
@jesus9ias , thanks. We are working on it.

**Comment by Invision70** [comment]
+1

**Comment by alexanderrudnik** [comment]
@someburner helps us to fix it. Thank you all for bug report!
