### ISSUE TITLE
I cannot set Human-friendly Dates for Datepicker

### ISSUE THREAD

**Issue by codegor** [epicmaxco/vuestic-admin#211]
The element flatpickr have ability for Human-friendly Dates (https://flatpickr.js.org/examples/#human-friendly-dates), but I cannot set it. Could you help me?

**Comment by smartapant** [comment]
@asvae could you please have a look?

**Comment by asvae** [comment]
@smartapant bootstrap >.>. We have to fight back.

**Comment by asvae** [comment]
Fixed with 75228ffeca926ae13b3e4413e10edac7727d16d1
