### ISSUE TITLE
What are you think about ad-grid?

### ISSUE THREAD

**Issue by codegor** [epicmaxco/vuestic-admin#212]
I use your admin panel, but I found that [ad-grid](https://github.com/ag-grid/ag-grid-vue-example) is very functional like datatable, maybe it's worth making another alternative for the tables? ad-grid is very functional like for me
https://www.ag-grid.com

**Comment by smartapant** [comment]
@codegor we might do it, but that's quite a complex thing and we'll keep this issue open for some time as we won't be able to include it in our next milestones

**Comment by codegor** [comment]
ok, thank you

**Comment by smartapant** [comment]
@codegor will be using it in Vuestic 2.0

**Comment by asvae** [comment]
We'll give 2 options for 2.0:
* Normal styled table.
* Ag-grid with vuestic theme.

With a couple of examples for each of these to get started easily.
