### ISSUE TITLE
What are you think about vue-formly as form generator?

### ISSUE THREAD

**Issue by codegor** [epicmaxco/vuestic-admin#213]
I use your admin panel, but I found that vue-formly is very functional like form generator, becouse I can on the config object set all configurations of form and it is very easy. All of the form elements from the admin panel I have set up as a [custom elements](https://matt-sanders.gitbooks.io/vue-formly/content/v/2.0/how_to_use/creating_formly_fields.html) for that package and now the creation of the form is very simple.
(for validation I use vee-validate, I don't use validation from that package)
https://github.com/formly-js/vue-formly

**Comment by smartapant** [comment]
@codegor thank you for the suggestion but we think that formly lib is still quite fresh to be added as a dependency :)

We're thinking of wrapping inputs in something like <vuestic-input /> elements by the way

**Comment by codegor** [comment]
will be very cool if you will create a system for creating form from one config file, like at that pakedge. I think it is cool idea create form from 1 config object. Thank you for reply.
