### ISSUE TITLE
What are you think about vue-modal-dialogs for show modal window (dialog window)?

### ISSUE THREAD

**Issue by codegor** [epicmaxco/vuestic-admin#214]
I use your admin panel, but I found that [vue-modal-dialog](https://github.com/hjkcai/vue-modal-dialogs) is very functional like manager of modal windows. If you think so maybe will be good to use it?
in the folder structure, you could create a window folder (components/windows) and add all the files for modal windows
https://hjkcai.github.io/vue-modal-dialogs/

**Comment by smartapant** [comment]
@codegor we've got `<vuestic-modal>` component inside the package, you can report issues if you need some new behavior for the modals :)

**Comment by codegor** [comment]
For now I use <vuestic-modal> like a part of that packedge. I think it is cool idea if all windows/dialogs will be at one place of root template, like at that package done and if window system has a open() and close() method for open/close window/dialog. That's when I need a window/dialog on a page I only need import a JS var and call open() (or create()) method and the window will be shown. The view of the window I do at another .vue component. This gives that I have the window and I can call it on diferent places of my app, without copy pasting template and logic of the window.
