### ISSUE TITLE
Date & Time Picker Update

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-admin#215]
1. Let's highlight the current day with #4AE487. Please refer to Zeplin project: zpl.io/aBErAMQ
2. Can we offer different output formats? Not only '2018-05-27', but 'May 27, 2018' or '05/27/2018' at the same time.
3. Can we offer an option to adjust the order of the days: a) from MON to SUN, b) from SUN to SAT?!
4. Range picker works a bit tricky, not intuitive at all.
[Screen Shot 2018-05-15 at 12.32.55.png](https://images.zenhubusercontent.com/5af0455b4b5806bc2bd208f1/45040b30-a177-45d3-b5b1-2368e3ca7ce1)

**Comment by gramlin** [comment]
3) :config="{              
                    locale: {
                                 firstDayOfWeek: 1
                    },}"
