### ISSUE TITLE
Can you create form element for upload files (pdf, images) with preview?

### ISSUE THREAD

**Issue by codegor** [epicmaxco/vuestic-admin#217]
it would be very cool if there would be an element for uploading files with a preview (and if the file already exists on the server (was uploaded), then it shows it on the preview plase (for image), or if it is a pdf file - shows an icon of file, and if click on it we can to download it)

**Comment by smartapant** [comment]
@codegor no probs, it's in our current milestone :) https://github.com/epicmaxco/vuestic-admin/issues/119

**Comment by codegor** [comment]
ok thank you
