### ISSUE TITLE
[Proposal] vuestic-admin installer tool

### ISSUE THREAD

**Issue by amranidev** [epicmaxco/vuestic-admin#22]
It would be more easier to create new vuestice projects via a command line interface instead of git clone or downloading form GitHub.

I suggest to create a npm package to handle this operation.

```bash
# install vuestic-admin globally.
$ npm install -g vuestic
# create new project.
$ vuestic <my-new-project>
```
If you like the idea, I can take care of it.

**Comment by smartapant** [comment]
@amranidev nice! I've emailed you about this one

**Comment by smartapant** [comment]
@amranidev that would be cool to implement. Will you do this one?

**Comment by amranidev** [comment]
Yes sure

**Comment by amranidev** [comment]
@smartapant just to update you, I already push initial code to [vuestic-installer repo](https://github.com/epicmaxco/vuestic-installer) and registering it through [npmjs](https://www.npmjs.com/package/vuestic-installer).

**Comment by smartapant** [comment]
@amranidev thank you for the awesome contribution! If you have some feature in mind - you can always ping me :)

**Comment by amranidev** [comment]
yeah sure!! 
Thanks a lot.
