### ISSUE TITLE
Dropdown component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#223]
- [ ] Should conform 3 dropdowns in header.

**Comment by smartapant** [comment]
@asvae @Eugenizer any solution for flicker-bug?

**Comment by smartapant** [comment]
@asvae @Eugenizer anyway, bug is too visible to leave it as it is

**Comment by asvae** [comment]
@smartapant tried everything simple I can think of. So probably no easy solution.

So it's either we leave it as is, or we move it to next milestone.
