### ISSUE TITLE
Add proper issues and PRs templates

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#225]
Right now our issues are garbage (this one included), i guess we need to keep some order to move forward. https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/

- [ ] Add contact email to CODE_OF_CONDUCT.md

**Comment by smartapant** [comment]
@asvae we definitely need to have a talk about it (you already proposed it once) next time you're in Minsk

**Comment by asvae** [comment]
@smartapant We need an issue to have our talk about issues properly organized... oh wait.

**Comment by smartapant** [comment]
@asvae exactly 💃
