### ISSUE TITLE
Is there any dynamic css classes to show/hide green dot over notification icon?

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#227]
Hi,

In the `Navbar`, over the notification bell icon, there is a green dot to represent the new notifications. I want to hide/show based on the notifications. Do you have any dynamic way to achieve this?

Or if you could suggest me a better way to implement in your package, it would be helpful.

Looking forward!

**Comment by smartapant** [comment]
@harishankards in Navbar.vue, search for ` <span class="i-nav-notification notify"></span>`, this `.notify` class renders the dot. So you need to dynamically add/remove this class based on your notifications

**Comment by harishankards** [comment]
Thanks a lot, Smartapant!
