### ISSUE TITLE
Add slots to vuestic data table

### ISSUE THREAD

**Issue by alexanderrudnik** [epicmaxco/vuestic-admin#228]
Introduce slots like in original vuetable2 https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-11

**Comment by smartapant** [comment]
@alexanderrudnik that seems to be quite complicated, i will close this issue until there are more people requesting this feature

**Comment by alexanderrudnik** [comment]
we should keep this open with low priority to let people know about the issue

**Comment by smartapant** [comment]
Tables will be reimplemented in Vuestic 2.0
