### ISSUE TITLE
Vuestic Table Hover

### ISSUE THREAD

**Issue by AngeloAnolin** [epicmaxco/vuestic-admin#232]
Hi,

I am unsure if there are others who tried adding table-hover class to the css class for the Vuestic DataTable and not getting the hover effect.

I even tried isolating vuetable and see whether the table hover class will show up, but for some reason, the hover effect does not seem to apply.

Any suggestions? Thanks.

**Comment by asvae** [comment]
It's likely we messed up styles somewhere. We'll take a look.

**Comment by smartapant** [comment]
@AngeloAnolin here's the solution https://github.com/epicmaxco/vuestic-admin/pull/299
it will be merged to master closer to 1.8.0 release
