### ISSUE TITLE
Feature Suggestions

### ISSUE THREAD

**Issue by MrClan** [epicmaxco/vuestic-admin#24]
1. Internationalization (i18n)
2. Theme switch (dark/light)
3. Forms like typeforms [https://www.typeform.com/]
4. UI Blocker (during form submissions)
5. Route-change animations (like what nuxt does)
6. Keyboard navigation

**Comment by smartapant** [comment]
@MrClan thanks, that's quite interesting!

**Comment by MrClan** [comment]
On a totally unrelated context, in main.js, on line 14, you may want to change this:

`Vue.use(VeeValidate)`

to

`Vue.use(VeeValidate, { fieldsBagName: 'formFields' })`

This will remove the following warning in the console:

> [Vue warn]: The computed property "fields" is already defined as a prop.

**Comment by alexanderrudnik** [comment]
@MrClan thank you for advice. We tried this solution before but it didn't work.

**Comment by MrClan** [comment]
@alexanderrudnik Strange. I tried it in my current setup, and it definitely makes that warning go away.

**Comment by nathanbrizzee** [comment]
I'd love to see a date/calendar control themed to match the other control themes. Also a way to change the theme color scheme would be nice.  Something like what [vue-paper-dashboard](https://cristijora.github.io/vue-paper-dashboard) does.

**Comment by raymondmuller** [comment]
i18n: https://github.com/epicmaxco/vuestic-admin/pull/33

**Comment by AngeloAnolin** [comment]
I'd like to make a suggestion where we include an example where HTTP calls are made (via axios) and how it is going to be defined in the store. That way, people perusing this template would have an understanding of where to put a centralized location for all their api calls.

**Comment by smartapant** [comment]
@AngeloAnolin that sounds nice, we really need to make something like that. Thanks!

**Comment by smartapant** [comment]
@nathanbrizzee we're working on datepickers right now

**Comment by jkbbwr** [comment]
Stripe support? :) Great job on everything by the way.

**Comment by SzaboGabesz** [comment]
Hey! Could you guys design a tree component. That'd be awesome! Thanks

**Comment by smartapant** [comment]
@jkbbwr thanks! we're thinking about some pages with 'pricing plans' layout and credit cards widgets but will be delivering it not soon.

@SzaboGabesz I will ask @xx13 to design it :)

**Comment by smartapant** [comment]
@nathanbrizzee Datepickers' designs are ready, check out #117 
@SzaboGabesz Trees' deisgns are ready, check out #120

**Comment by asvae** [comment]
Suggestions go to separate issues.
