### ISSUE TITLE
VuesticRadioButton static label

### ISSUE THREAD

**Issue by gramlin** [epicmaxco/vuestic-admin#241]
Was a bit curios on why I was getting "Radio" as text for all my radiobuttons...
Seems to be static in VuesticRadioButton.vue; 
`<span class="abc-label-text">{{'forms.controls.radio' | translate}}</span>`

should be
`<span class="abc-label-text">{{ label }}</span>`

**Comment by smartapant** [comment]
@gramlin thanks for mentioning :)
