### ISSUE TITLE
reactiveProp chart fails to update labels

### ISSUE THREAD

**Issue by MasudaH** [epicmaxco/vuestic-admin#243]
Following the code found here: https://github.com/epicmaxco/vuestic-admin/pull/181/commits/86e38af592fe1cd8c854a7d0e0f1e525e2872b56
I made the vertical bar chart provided by vuestic reactive. However, in \src\data\charts\VerticalBarChartData.js, even though the data attribute inside the datasets array can be updated causing the chart to change, the labels array only changes the chart on its first update. All following changes to the labels array do not change the chart even though the bars change height as the data is updated.

**Comment by asvae** [comment]
There was a quirk with vue-chartjs options handling.
