### ISSUE TITLE
Vee-validate error doesn't display on the first time, but working fine only in the second time

### ISSUE THREAD

**Issue by harishankards** [epicmaxco/vuestic-admin#247]
**Versions**
- vee-validate: 2.0.0-rc.7
- vue: 2.5.2

**Bug description**
The error is not shown for the first time when clicking in and coming out of the required input box. But working fine when clicking in and coming out of the required input box for the second time.

**To Reproduce**
When I check outside the vuestic-theme it's working fine (please check demo link below). But inside the vuestic-theme, it is not working properly.

**Expected behaviour**
I expect it to show the error on clicking in and out for the first time itself

**Demo Link**
https://codesandbox.io/s/7wv0y85wm6

**Desktop (please complete the following information):**
- OS: Ubuntu
- Browser: Chrome
- Version 67.0.3396.79

Any clue that why this issue is happening?

**Comment by vlad-shusterman** [comment]
Hi,
I don't see this bug. Give more info, if it is possible, please. You can check it in https://vuestic.epicmax.co/#/admin/forms/form-wizards

**Comment by ariellevitsky** [comment]
I'm having the exact same issue but only on one page of the app. On all other pages the library works as intended.
