### ISSUE TITLE
Stateless input component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#260]
* Extremely useful for masking.

**Comment by jean-moldovan** [comment]
@asvae Custom `vuestic-input` component with `mask` prop?

**Comment by asvae** [comment]
@jean-moldovan I think it's easier to provide a couple of masking examples in presentation rather than implementing our own solutions. Diversity is just too high for masking.

**Comment by asvae** [comment]
Not doable easily, not conventional.
