### ISSUE TITLE
Broken vuestic

### ISSUE THREAD

**Issue by tk512** [epicmaxco/vuestic-admin#264]
I decided to test this out and I ran npm install - it gives a lot of warnings but does eventually start up the site with npm run dev.

It works well in a browser but with some minor UI glitches  (footer text). Also it does not render properly at all on Safari on iOS.

Examples of errors when running npm install:

> npm WARN vue-bulma-expanding@0.0.1 requires a peer of bulma@>=0.2 but none is installed. You must install peer dependencies yourself.

> added 1395 packages from 713 contributors and audited 9644 packages in 82.224s
found 22 vulnerabilities (4 low, 14 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details

And when running npm run dev, the following message is repeated hundreds of times:

> No parser and no filepath given, using 'babylon' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.

The primary problem that I would like to report is that it doesn't render on mobile though.

**Comment by smartapant** [comment]
@tk512 thanks for reporting!

Please check if mobile view is fixed in the latest master

**Comment by tk512** [comment]
Yes, seems to work. Thanks!

**Comment by smartapant** [comment]
@tk512 always welcome :)
