### ISSUE TITLE
how to use i18n in vuestic-data-table

### ISSUE THREAD

**Issue by leon4770** [epicmaxco/vuestic-admin#277]
how to use i18n in vuestic-data-table

**Comment by HarmlessEvil** [comment]
You can override translation string 'tables.ddataTable.noDataAvailable' in your corresponding localization file

Also, you can use props `items-per-page-label` and `filter-input-label` to put a translated string into the component.

Like that:

```html
<vuestic-data-table :items-per-page-label="$t('label1')" :filter-input-label="$t('label2')"></>
```

**Comment by leon4770** [comment]
I mean how to change table filed title when I change language?

**Comment by HarmlessEvil** [comment]
@leon4770 May you provide some code, how do you use table, where is the title?

**Comment by smartapant** [comment]
@alexanderrudnik please answer @leon4770 question, and close the issue when resolved :)

**Comment by renato04** [comment]
Hello!

I have this same doubt, in the sample there is a `fields-definition.js` containing 
`
    {
      name: 'address.line2',
      title: 'city'
    }
`
Is there a way to use i18n to transalate the `title`?

**Comment by alexanderrudnik** [comment]
hey @leon4770 @renato04 

For table titles you can use:

```
tableFields () {
        return [
          {
            name: '__component:column-vulnerability-id',
            title: this.$t('prefix.vulnerabilityId'),
            sortField: 'vulnerability_id'
          },
          {
            name: '__component:column-summary',
            title: this.$t('prefix.summary'),
            sortField: 'summary'
          },
     // other columns
        ]
      }
```

And do not forget to normalize fields:

```
watch: {
      tableFields () {
        this.$nextTick(() => this.$refs.datatable.normalizeFields())
      }
    }
```

**Comment by lelelethu** [comment]
> @alexanderrudnik thanks for the answer but i`m getting some errors
> 
> ![image](https://user-images.githubusercontent.com/5497267/46371658-5381ac00-c65f-11e8-9c4d-07298c219d0b.png)
> 
> Do i have to import something?

Hi renato04,

I am not real mater in Vue. But i think you can move code have 'tableFields ' into *.vue file () instead of placing it in the file 'fields-definition.js'.
In the .Vue file, i18n is declare, then it work fine.
