### ISSUE TITLE
how to use Pagination in data-table

### ISSUE THREAD

**Issue by leon4770** [epicmaxco/vuestic-admin#278]
my json data struct:
{{
	"pageSize": 15,
	"start": 0,
	"totalCount": 1858,
	"totalPageCount": 124,
	"pageNo": 1,
	"form": "listForm",
	"result": [{
		"GAA018": "Ray",
		"GAA019": "",
		"GAA012": "",
		"GAA013": "Tiffany Qiu",
		"GAA010": "",
		"GAA011": "ESP",
		"GAA016": "C122356",
		"GAA017": "trophymuskegon",
		"GAA014": "Tiffany Qiu",
		"GAA015": ""
	}, {
		"GAA018": "Ian Fraenkel",
		"GAA019": "561-323-8335",
		"GAA012": "",
		"GAA013": "Amy Yang1",
		"GAA010": "",
		"GAA011": "ESP",
		"GAA016": "CSU00858",
		"GAA017": "IJF Creative Group Toot Box LLC",
		"GAA014": "amy yang",
		"GAA015": ""
	}, ],
	"currentPageNo": 1,
	"toolbarHtml": "<span class='firstDis2' ></span><span class='prevDis2' ></span>第1页<span class='nextPage' onclick='gotoPage(listForm,2)' ></span><span class='lastPage' onclick='gotoPage(listForm,124)' ></span>",
	"footerHtml": "【第1页】【共124页】【每页15条】【共1858条】"
}},

I tried to set paginationPath='',  but not work

**Comment by HarmlessEvil** [comment]
@leon4770 It's relying on component "[vuetable](https://github.com/ratiw/vuetable-2)", so you should check their wiki: https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-07

**Comment by leon4770** [comment]
Thanks a lot.
