### ISSUE TITLE
Click on sidebar category hides sidebar

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#283]
- [ ] and it shouldn't

![image](https://user-images.githubusercontent.com/5394573/43274886-117199fa-9109-11e8-9288-95020c7dd3a4.png)

**Comment by LuanFreitas** [comment]
I also had the same problem but found no solution.
By clicking on some link in the mobile mode, the whole menu hides

**Comment by pfrohner** [comment]
here it is

https://github.com/epicmaxco/vuestic-admin/pull/296
