### ISSUE TITLE
Installation error - Vue packages version mismatch

### ISSUE THREAD

**Issue by yeya** [epicmaxco/vuestic-admin#29]
```
#npm run dev
 error  in ./src/App.vue

Module build failed: Error: 

Vue packages version mismatch:

- vue@2.4.2
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
```

I fixed it by ```npm install npm isntall vue-template-compiler@2.4.2```

**Comment by alexanderrudnik** [comment]
@yeya your solution works, thanks!

**Comment by franciskisiara** [comment]
@yeya just a small pointer - you have a typo on the second "install"

**Comment by yeya** [comment]
Well, not really. https://github.com/npm/npm/issues/2933 but thanks. :-)

**Comment by yangfandashuaige** [comment]
我删除了 xxx
是可以的

> ```
> #npm run dev
>  error  in ./src/App.vue
> 
> Module build failed: Error: 
> 
> Vue packages version mismatch:
> 
> - vue@2.4.2
> - vue-template-compiler@2.4.4
> 
> This may cause things to work incorrectly. Make sure to use the same version for both.
> If you are using vue-loader@>=10.0, simply update vue-template-compiler.
> If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.
> ```
> 
> I fixed it by `npm install && npm install vue-template-compiler@2.4.2`
I deleted node_modules
Reinstall
Yes.
