### ISSUE TITLE
Duplicate 'You are running Vue in development mode.'

### ISSUE THREAD

**Issue by youyi1314** [epicmaxco/vuestic-admin#295]
When i use `vuestic NewProject ` with using vuestic installer,
and run `npm install` .
after finish install, i run `npm run dev` it show duplicate 

> You are running Vue in development mode.

It should be import twice Vue in this code.
how can i fixed this?

Photo below :
![image](https://user-images.githubusercontent.com/8391468/43689067-1aed7136-9927-11e8-82b6-12bdd4ef3ca2.png)

Version
Vue : 2.5.2
Vuestic-Admin: 1.7.0
Node: v10.6.0

**Comment by smartapant** [comment]
@youyi1314 our epic spinners cause this second message. not fatal though, we'll be fixing that :)

**Comment by smartapant** [comment]
@youyi1314 fixed 'epic-spinners' lib. Now you can upgrade to 'epic-spinners' 1.0.4 to get this issue fixed for you.

We'll also fix it in Vuestic 1.9.0

**Comment by youyi1314** [comment]
wow, sorry for very late reply, I will try that, thanks for your update. 👍

**Comment by smartapant** [comment]
@youyi1314 sorry for late fix :)
