### ISSUE TITLE
http://vuestic.epicmax.co/#/extra chat message length

### ISSUE THREAD

**Issue by datskevichsergey** [epicmaxco/vuestic-admin#3]
Hi Guys, I've just tried to write a message with quite a big length (something like "aegeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyykkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk") and part of the string was hidden instead of being moved to another line.
Chrome on Ubuntu 16.04
Version 60.0.3112.90 (Official Build) (64-bit)

**Comment by smartapant** [comment]
Thanks! We'll have a look!
