### ISSUE TITLE
Back to Icons Link Bug

### ISSUE THREAD

**Issue by alexanderrudnik** [epicmaxco/vuestic-admin#305]
Back to icons link directs user to the Dashboard page.

Here is a movie about an issue
https://www.dropbox.com/s/pife35v523z26k2/back-to-icons-bug.mov?dl=0

**Comment by alexanderrudnik** [comment]
Still an issue. Version 1.8.0

**Comment by asvae** [comment]
759a4a1be72c2dc69fc6548a9f796451c8aca05c
