### ISSUE TITLE
Bug mobile view chat

### ISSUE THREAD

**Issue by Marlysson** [epicmaxco/vuestic-admin#31]
When visualizing via mobile the talks breaks to show the text.

**Comment by georgeMuraveiAlkh** [comment]
@Marlysson hi! Could you provide more details about your device and browser version?

**Comment by Marlysson** [comment]
![photo5116130189791831980](https://user-images.githubusercontent.com/4117999/31504516-f5105500-af48-11e7-9ad9-7320347dc7a5.jpg)

Here are the UI.

**Comment by smartapant** [comment]
@Marlysson what's your android version?
