### ISSUE TITLE
Vuestic input component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-admin#329]
### Design
- [zeplin](https://zpl.io/VYkGrkk)
- [design doc](https://xx13.github.io/vuestic_redesign/#inputs)

### Props

- [x] value - String. 
- [x] label - String - sets title above the input content.
- [x] placeholder - String - text, which contains input content before any symbol is typed. Usually it is used as a hint.  
- [x] disabled - Boolean.
- [x] readonly - Boolean.
- [x] clearable - Boolean - if set to 'true', displays close icon that clears input on click content.
- [x] type - String - set value of HTML5 form type attribute for input. More about this property look here: https://www.w3schools.com/tags/att_input_type.asp. We do not want to support this prop in any other way apart from giving user a way to pass it down to input. So if masking, let's say, breaks for `type="number"` - we don't care.
- [x] error - Boolean - error state.
- [x] messages - Array.
- [x] error-messages - Array.

### Possible Props
- [ ] rules - Array - сontains array of functions, that will validate input value. 
- [ ] prefix - String - sets non-editable text before input content.
- [ ] suffix - String - sets non-editable text after input content.
- [x] success - Boolean - success state.
- [ ] success-messages - Array.
- [ ] hint - String.
- [ ] limit - Number - maximum number of symbols, that can be typed. 
- [ ] number - Boolean - if set to 'true', input content allow typing only numeric text.
- [ ] required - Boolean - if set to 'true', input content should contain valid text before form is submitted.
These props can be used as 'rules' prop alternative.
- [ ] icon - String - insert icon with defined class from the left side of the input.
- [ ] icon-right - String - insert icon with defined class from the right side of the input.
These props can be used as 'prepend' and 'append' slots alternative.
- [ ] outline - Boolean - if set to 'true', remove input background and set border instead of it. (@asva probably later ver)
- [ ] size - String. (small/large ?)
- [ ] background-color - String - set color for area around the input content. Possible colors for input background: 'success', 'info', 'warning', 'danger'.
These props can be used for customizing input.
- [ ] hide-details - Boolean - if set to 'true', hide all hint/error messages.

### Extensions

- [ ] textarea - Boolean - if set to 'true', input becomes textarea.
- [ ] autogrow - Boolean - if set to 'true', textarea grows depending on amount of text.
- [ ] autocomplete - Boolean.
- [ ] loading - Boolean - if set to 'true', shows loading indicator (progress bar, spinner?).
- [ ] mask - String - maximum number of symbols, that can be typed.

### Slots

- [x] default - for input content.
- [x] prepend - area from the left side of the input.
- [x] append - area from the right side of the input.

### Events
(@asva - I think we can just proxy all events, but check refs just in case)
- [x] @input - triggered on immediate value change
- [ ] @change - triggered on lazy value change
- [x] @focus
- [x] @blur
- [x] @keydown
- [x] @keyup

### References
Main:
- [Vuetify](https://vuetifyjs.com/en/components/inputs) (!) - main reference
- [Quasar](https://quasar-framework.org/components/input-textfield.html) (!) - validation and password extensions
- [Vue Bootstrap](https://bootstrap-vue.js.org/docs/components/form-input/) (!) - input sizes, 'aria-invalid' attribute
Other:
- [Ant Design](https://vue.ant.design/components/input/)
- [Vue Material](https://vuematerial.io/components/input/)
- [Vue Form Components](https://www.npmjs.com/package/vue-form-components)

SP8

**Comment by asvae** [comment]
Would be wise to check existing implementations from vuetify and quasar.
