### ISSUE TITLE
i8n Toast message - how to translate toast message?

### ISSUE THREAD

**Issue by Pietro89** [epicmaxco/vuestic-admin#344]

**Comment by BeatrizPP** [comment]
this.showToast(this.$t('/*your i18n key*/'), {
          className: 'vuestic-toast danger',
          icon: 'fa-exclamation-triangle',
          position: 'top-right',
          duration: 2500,
          fullWidth: false
        })

**Comment by asvae** [comment]
Like this

```js
this.showToast(this.$t('dashboard.table.resolved'))
```
