### ISSUE TITLE
Table Component Pagination Error

### ISSUE THREAD

**Issue by cgslivre** [epicmaxco/vuestic-admin#35]
![image](https://user-images.githubusercontent.com/2656420/31549240-f430681c-b003-11e7-8f25-8605d37a25a6.png)
Route: http://vuestic.epicmax.co/#/tables

**Comment by raymondmuller** [comment]
@cgslivre  
This was / is an dependency issue from vuetable-2.
Fixed in v1.6.6 https://github.com/ratiw/vuetable-2/releases/tag/v1.6.6

**Comment by alexanderrudnik** [comment]
@raymondmuller yep, updating vuetable-2 to the 1.6.6 version fixed the issue. Thank you!
