### ISSUE TITLE
Use shorter prefix for components and styles

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#355]
For now we use `vuestic-`, which is quite a challenge to type.

I suggest something shorter, like `vt`.

@smartapant @jean-moldovan @Eugenizer @alexanderrudnik what do you think?

**Comment by Eugenizer** [comment]
`vs` as an option

**Comment by asvae** [comment]
> `vs` as an option

@Eugenizer heavily reminds me of VisualStudio.

**Comment by jean-moldovan** [comment]
Could be `vst`. Although if you Google, it seems to be taken by some plug-in interface or whatever.

**Comment by asvae** [comment]
It's ok if we don't hit major players, no need to think of something super unique. 

Just `v-` is overused but would be perfect otherwise

**Comment by asvae** [comment]
Settled on `va`
