### ISSUE TITLE
Icon component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#366]
Zeplin: https://zpl.io/aREYDlN

- [x] use `i` for tag
- [x] Perform component checks (#378)

### Props
- [x] icon: String, For the time being just fallback to class.
- [x] small: Boolean
- [x] large: Boolean.
- [x] size: String | Number.
- [x] fixed-width: Boolean
- [x] rotation: String | Number. Validate to be numeric.
- [x] color: String should work the same as here #367. By default color should be taken from font (see `currentColor`)

### Keynotes
* We want more control for this component, but not entirely sure how to do this.
* Ideally we want to support ligatures, icon fonts, svg icons.
* We want the ability to swap icons for internal icons of system coponents. Config (a la vuetify) seems to be a feasible solution.

### References
* vue-font-awesome: https://github.com/FortAwesome/vue-fontawesome
* quasar: https://quasar-framework.org/components/icons.html
* vuetify: https://vuetifyjs.com/en/components/icons

**Comment by smartapant** [comment]
@asvae vuestic-icon for tag?

**Comment by asvae** [comment]
@smartapant `i` is internal tag.
