### ISSUE TITLE
Check bootstrap

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#380]
After everything with 2.0 is done check what is left of bootstrap and do an issue.

- [x] check `vuestic-sass/overrides` and remove things we don't need anymore 
- [x] remove bootstrap from `resources.scss`. This file is what you want to have globally accessible for vuestic-admin. So that user won't have to import variables for every component.
- [x] remove `shared.scss`. User `resources.scss` instead.
- [x] check for `bootstrap` steps in all files, which are belong to `vuestic-sass` folder (@asva cryptic message, skip on fail to decipher).
- [x] in `package.json` delete bootstrap dependencies (`bootstrap` and `awesome-bootstrap-checkbox`)

**Comment by smellyshovel** [comment]
Solved with #597.
