### ISSUE TITLE
bug report - datepicker with time lags

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#383]
To reproduce the bug go to "Form Elements" page.

Play with datepicker that has 'time' label. 
After changing hours/minutes a couple of times the picker starts to be lagging and not responsive.

Works fine in Safari, lags in Chrome.

![screen shot 2018-10-29 at 3 08 56 pm](https://user-images.githubusercontent.com/3674348/47648964-beee6900-db8c-11e8-9f7a-b6dfb9382efa.png)

**Comment by asvae** [comment]
Fixed by https://github.com/epicmaxco/vuestic-admin/commit/21c43ab400c5068bfb61e27b335888a23e7ac519

Presentation issue.
