### ISSUE TITLE
Not able to load data from mongodb in Data-table component

### ISSUE THREAD

**Issue by sahar-fehri** [epicmaxco/vuestic-admin#389]
Hello everyone,
I am trying to populate my datatable with elements loaded from a mongodb database. 
I am trying to use the datatable compoenent in the vuestic-admin table with the pagination cause it looks pretty cool ^^. But i don't seem to find out  how to make it work, there are a lot of files that seem to be very connected to one another,, If someone could help me through this i would really appreciate it , thanks !

**Comment by asvae** [comment]
Please reopen If still relevant
