### ISSUE TITLE
How to create a route that is not display in menu?

### ISSUE THREAD

**Issue by kahwooi** [epicmaxco/vuestic-admin#40]
How can I hide this from menu?
  
 ```
   {
      name: 'user',
      path: '/user/:id',
      component: lazyLoading('user/Edit'),
      meta: {
        title: 'Edit'
      }
```

**Solved it by adding route into router/index.js**

**Comment by HugoHeneault** [comment]
Where your breadcrumb still working? 🤔

**Comment by Frootzy** [comment]
Also, can you please show how you added it ?
I don't see how you did that :disappointed:
