### ISSUE TITLE
1.9.0 bugs

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#412]
Check these are obsolete and components are implemented.

- [ ] Select too long https://user-images.githubusercontent.com/5394573/49163283-c8aaee00-f33d-11e8-8242-9d5a4c1e637b.png

**Comment by Arseniy91** [comment]
The scroll is not working. 
![image](https://user-images.githubusercontent.com/41131032/49034125-b43de880-f1b9-11e8-84af-c8bd77daa374.png)

**Comment by paulociva** [comment]
the text is under the scroll bar
![texto-menu](https://user-images.githubusercontent.com/2572582/49105078-da6d9200-f266-11e8-8c41-2a3f89b6e0d7.PNG)

**Comment by The-BlackWidow** [comment]
Is it possible to make the scrollbar thumb draggable ?

**Comment by asvae** [comment]
@The-BlackWidow 
For now - no.

We plan to use native navbar for 2.0.

**Comment by asvae** [comment]
Not relevant for 2.0.
