### ISSUE TITLE
Colors presentation

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#415]
- [x] Create `ColorsPresentation` coponent with demo.
- [x] add some kind of tooltip on hover with friendly suggestion to click and copy HEX to clipboard

* It might be included into main presentation at some point.

* Zeplin: https://zpl.io/bWkYvZp

  ![](https://i.imgur.com/IY6cBpc.png)

**Comment by smartapant** [comment]
@asvae @xx13 @nastassiadanilova would be cool to have some kind of tooltip on hover with friendly suggestion to click and copy HEX to clipboard
