### ISSUE TITLE
Add colors presentation component to active presentations

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#426]
See https://github.com/epicmaxco/vuestic-admin/issues/415

This only pertains to ui-component part of vuestic. Shouldn't be in presentation.

- [ ] also apply themes instead of scss or numeric colors.

**Comment by smartapant** [comment]
@smellyshovel let's put it in UI Components -> Colors (next to spacers). For now :)

**Comment by smellyshovel** [comment]
Solved with #609
