### ISSUE TITLE
Dropdown is not selected in UI Element->buttons-> Icons, Groups, Dropdowns

### ISSUE THREAD

**Issue by Arseniy91** [epicmaxco/vuestic-admin#428]
1) click on dropdown botton
2) choice of 3 options is displayed (-action -another action -something else here)
3) choose any of the 3
Expected result: one of the selected options removes "dropdown" and the selected option is displayed instead
![image](https://user-images.githubusercontent.com/41131032/49829970-8dc2a480-fd98-11e8-9b0b-f8a2ae26062f.png)

**Comment by asvae** [comment]
That is correct behavior for dropdown.
