### ISSUE TITLE
How to validate at confirm page?

### ISSUE THREAD

**Issue by kahwooi** [epicmaxco/vuestic-admin#43]
Vuestic-Wizard does not has isValid() for the confirm page.

If I have some validation at the confirm page, how can I stop it from complete?

**Comment by smartapant** [comment]
@kahwooi confirm page exists for displaying some success info to a user, all the validation shall be present on preceding steps

**Comment by kahwooi** [comment]
Example, I am saving something at confirm page, but something went wrong, how to stop from complete?

**Comment by kahwooi** [comment]
What if the process like saving is not successful, how can I prevent it from complete?

**Comment by smartapant** [comment]
@kahwooi hey!

Check out docs https://github.com/epicmaxco/vuestic-admin/wiki/Wizards

The basic idea is that success page is shown if everything's gone good :)

You can create the page that comes before the last one and handle the completion logic in onComplete hook
