### ISSUE TITLE
"Toasts" in Notifications is not in the right position on a page when Fullwidth is selected 

### ISSUE THREAD

**Issue by Arseniy91** [epicmaxco/vuestic-admin#430]
reproduced for the 4 positions marked at the screenshot
![image](https://user-images.githubusercontent.com/41131032/49892358-7693bd80-fe51-11e8-8ec2-12152ffbbd43.png)

**Comment by asvae** [comment]
I think full width toast should have only 2 positions (top and bottom).

Any thoughts on this, @Arseniy91?

**Comment by Arseniy91** [comment]
think all positions should have full width option. 
Maybe the text itself should be justified too? @asvae

**Comment by asvae** [comment]
So I decided to keep the same behaviour as the library we use internally

https://shakee93.github.io/vue-toasted/
