### ISSUE TITLE
Button dropdown component

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#438]
### Props
- [x] `label` - String | Slot. Button text
- [x] `split` - Boolean. When set to 'true', list of items is shown only on clicking arrow-down/arrow-up area of dropdown button.
- [x] `outline` - Boolean.
- [x] `flat` - Boolean.
- [x] `small` - Boolean.
- [x] `large` - Boolean.
- [x] `color` - String. 
- [x] `disabled` - Boolean.
- [x] `disable-button` - Boolean - only for split.
- [x] `disable-dropdown`- Boolean - only for split
- [x] `split-to` .- String - only for split. Use main button as a router-link
- [x] `icon` - String - Custom icon instead of arrow down
- [x] `opened-icon` - String - Custom icon instead of arrow up
- [x] `position` - String. Set position of dropdown list 

### Events
- [x] click
- [x] mainButtonClick - only for split

### Notes
- [x] make existed presentation file more rich
- [x] include it in sidebar 

### Referencies
- [Vuetify](https://vuetifyjs.com/en/components/buttons#button-dropdown-variants)
- [Quasar](https://quasar.dev/vue-components/button-dropdown)
- [Vue ant design](https://vuecomponent.github.io/ant-design-vue/components/dropdown/)
- [Bootstrap Vue](https://bootstrap-vue.js.org/docs/components/dropdown)

**Comment by asvae** [comment]
`items` we likely don't need at this point. Slot is easier to do and more powerful (see any other reference apart from vuetify).

This issue is definitely not for 2.0 as we don't have select yet, which is much more important.

**Comment by smartapant** [comment]
@asvae what do you think of reassigning this task to someone on the team?

**Comment by asvae** [comment]
@smartapant no problems
