### ISSUE TITLE
FileUpload doesn't call setter and thus, doesn't emit 'input' event

### ISSUE THREAD

**Issue by MatheusMS01** [epicmaxco/vuestic-admin#439]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
I'm trying to capture a change event upon a file upload, using vue-file-upload component. However, the setter, which emits an 'input' event, doesn't seem to be ever called. I did a little research and I found out that [setters only work with direct assignments](https://forum.vuejs.org/t/how-to-call-setter-for-object-in-computed-properties/29177/3), so I tryied, for testing sake, directly assign `this.file` to `{ ...files }`, on `uploadFile` method and it worked, although VuesticFileUploadList didn't work anymore. So I tryed instead emit the 'input' event on the uploadFile method instead and worked as I expected.

* **What is the expected behavior?**
Emit 'input' event upon a file upload change on vue-file-upload component

* **What is the motivation / use case for changing the behavior?**
Directly assing the computed property 'files' in order to call the setter method, OR emit the 'input' event on 'uploadFile' method

**Comment by asvae** [comment]
Thanks for pointing this out. We modified prop directly : 3.

To fix: 
In `VuesticFileUpload.vue:65` replace 
```js
      this.files.push(...files)
```
with 
```js
      this.files = [...this.files, ...files]
```

Is fixed in 1.9.3.
