### ISSUE TITLE
Not able to reset select value

### ISSUE THREAD

**Issue by kahwooi** [epicmaxco/vuestic-admin#44]
I am not able to reset select value to empty string:

```
<vuestic-simple-select
 label="Select Name"
 v-model="form.name"
name="name"
ref="nameSelect"
 v-bind:options="nameList">
</vuestic-simple-select>

data () {
  form: {
   name: ''
  }
},
method: {
  onClear() {
     form.name = ''
  }
}
```

**Comment by smartapant** [comment]
@kahwooi oops, will need to have a look into it, may be a bug

Thanks for spotting!

**Comment by whoan** [comment]
@kahwooi, the key is `methods` (see the final **s**). Was that just a typo in your comment?

And you need the `this` keyword to refer to the instance:

```
data () {
  form: {
   name: ''
  }
},
methods: {
  onClear () {
     this.form.name = ''
  }
}
```

**Comment by kahwooi** [comment]
@whoan Sorry, it is a typo.
