### ISSUE TITLE
Investigate existing data table solutions

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#440]
Table is crucial feature of vuestic and we should provide a well weighted solution.

* Check design for what we might require from data-table.

- [x] investigate all existing solutions for grid. Do small demos to understand if that's going to work or not.

## Ag grid
* Looks very safe to use (a lot of features)
* Has styling guide for [scss even](https://www.ag-grid.com/javascript-grid-styling/#when-to-create-a-theme).
* Bloated

- [x] Check if it's MIT

**Comment by alexanderrudnik** [comment]
ag-grid as possible solution
https://www.ag-grid.com/vue-getting-started/

**Comment by asvae** [comment]
@alexanderrudnik checked all tables on vue-awesome and ag-grid is pretty much the only solution.

There are some that belong to different frameworks so it's meh.
Also there are some that are not seasoned enough.
And commercial solution.
