### ISSUE TITLE
Live example website does not work?

### ISSUE THREAD

**Issue by SamuraiJack** [epicmaxco/vuestic-admin#441]
Hello,

I can't open the `http://vuestic.epicmax.co/` website with the Admin Dashboard example, is it just me or it is actually down?

**Comment by asvae** [comment]
Doesn't seem to be any problems on my side.
Any errors maybe?

**Comment by SamuraiJack** [comment]
Ok, sorry for the noise, closing then. I'm from Russia, here they block some of the ips, thats the reason I guess.
