### ISSUE TITLE
IE support via babel-polyfill and babel-plugin-transform-runtime 

### ISSUE THREAD

**Issue by simonwangtx** [epicmaxco/vuestic-admin#442]
Could this project support by Internet Explorer via babel-polyfill and babel-plugin-transform-runtime?

**Comment by asvae** [comment]
Should be fixed in 1.9.2. 

We initially had support, but while switching to vue-cli3 I commented it out for some reason >.>.

Feel free to reopen this issue if something doesn't work for your.
