### ISSUE TITLE
Automate deployment for master

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#443]
We want master deploy do be specific to epicmax and contain all analytics, chats and CEO stuff required.

Ideally this config/template should not be included in vuestic package that is going to be installed.

- [x] Test types of integration (analytics, chats) to ensure they work.

**Comment by alexanderrudnik** [comment]
Set up circleCI yaml config and settings. Tested -- everything (chats, metrics, deployment itself) is ok. Closing
