### ISSUE TITLE
How to integrate vuestic-admin asp.net core 2+ application

### ISSUE THREAD

**Issue by trktuhin** [epicmaxco/vuestic-admin#445]
Hi, I want to try vuestic-admin in my asp.net core application. But I failed to integrate this template. Please help me on how to integrate this template with asp.net core. If any starter template is available then it would be better for me and many others like me

**Comment by asvae** [comment]
> But I failed to integrate this template

Can you pinpoint exactly what went wrong?

*I'm not asp.net expert personally, but I can ask around. : 3*

**Comment by ramyareye** [comment]
I wrote something compatible with Laravel, it's based on jwt and a standard laravel permission package. If u send me your api docs maybe I can integrate it :)
