### ISSUE TITLE
Icon search bug on demo site (vuestic.epicmax.co)

### ISSUE THREAD

**Issue by amulchinock** [epicmaxco/vuestic-admin#447]
**I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

**Do you want to request a *feature* or report a *bug*?**
Report a bug about the [Vuestic Admin demo website](https://vuestic.epicmax.co)

**What is the current behaviour?**
When navigating to [/ui/icons/font-awesome](https://vuestic.epicmax.co/#/admin/ui/icons/font-awesome), and attempting to use the Icon Search box, the first few characters will trigger a search - but all subsequent characters added will cause a console error ("TypeError: Cannot read property 'key' of undefined").

After getting this error, attempting to navigate away from the page using the navbar will no longer work, forcing a user to refresh their browser window.

**If the current behaviour is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
See previous section.

**What is the expected behaviour?**
For the demo site to function fully, without errors.

**What is the motivation / use case for changing the behaviour?**
It's broken.

**Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
None.

**Comment by asvae** [comment]
We didn't handle properly icons that are included in multiple sets :/.

Thanks for pointing this.
Fixed in 1.9.2.
