### ISSUE TITLE
Polyfills not included

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#449]
#442 stated that VA doesn't work for IE11. I tested and it reproduced.

I included polyfills to hotfix the issue.

```js
import 'es6-promise/auto'
import 'babel-polyfill'
```

But in fact vue-cli3 should include polyfills by itself! See [docs](https://cli.vuejs.org/guide/browser-compatibility.html#browserslist).

We have to investigate why the inclusion doesn't happen.

You can check by simply opening main page in IE11. Wihout polyfills IE should complain about `Object.assign` and the page should stay blank.

**Comment by asvae** [comment]
We can get some hints from this article: https://sgom.es/posts/2019-03-06-supporting-old-browsers-without-hurting-everyone/

**Comment by asvae** [comment]
I checked PR and it's all nice. We need to resolve conflicts, then merge?

**Comment by Kreezag** [comment]
Fixed in issue #684
