### ISSUE TITLE
How do I add header to the data-table?

### ISSUE THREAD

**Issue by kahwooi** [epicmaxco/vuestic-admin#45]
How can I add Authorization to the data-table request header?

**SOLVED**

In main.js, I did this:

```
axios.defaults.baseURL = 'http://localhost'
axios.defaults.headers.common = {
  'Authorization': 'Bearer',
  'Accept': 'application/json'
}
```

**Comment by mjalindahl** [comment]
@kahwooi I'm having the same issue.

I tried adding your solution to my main.js and it doesn't seem to be doing anything.  Could you please elaborate?

Thanks!

**Comment by smartapant** [comment]
@mjalindahl the way @kahwooi solved the issue is the quite close to the one we use in commercial projects. Check out https://github.com/axios/axios and read it's docs, it's quite easy to use.

**Comment by mjalindahl** [comment]
@smartapant That doesn't help.  I use axios every day, and am quite familiar with it.

Pasting the "solution" in main.js does not solve the issue.  The apiUrl call still sends the request without headers to the API.

Could you explain where the actual apiUrl is being run?  Is there other stuff that needs to be changed?
