### ISSUE TITLE
Tooltip component

### ISSUE THREAD

**Issue by AlexanderBoriskin** [epicmaxco/vuestic-admin#473]
### Design
- Zeplin https://zpl.io/andq79r
- [Design doc](https://xx13.github.io/vuestic_redesign/#tooltips)

We use a library for tooltips. Provide all the functionality from library, just do a restyle.

-------------------

Probably useless
```
### Props
- [ ] `value` - Boolean. Controls tooltip visibility.
- [ ] `color` - String. Default - 'success'. Supported tooltip colors: 'success', 'info', 'warning', 'danger', 'gray'.
- [ ] `position` - String. Set position of tooltip from suggested options: 'top', 'left', 'right', 'bottom'.
- [ ] `delay` - Number. Amount of seconds that should pass before tooltip appears.
- [ ] `disabled` - Boolean. 
```

### References
- [Vuetify](https://vuetifyjs.com/en/components/tooltips)
- [Quasar](https://quasar-framework.org/components/tooltip.html)
- [Vue Ant design](https://vuecomponent.github.io/ant-design-vue/components/tooltip/)
- [Bootstrap Vue](https://bootstrap-vue.js.org/docs/components/tooltip)

![image](https://user-images.githubusercontent.com/39219429/51996477-e45d7c80-24c5-11e9-99d1-f786ce511d8c.png)

**Comment by smellyshovel** [comment]
va-simple-select seems to work incorrectly. Fixing it should also fix the popover/tooltip presentation
