### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#495]
### Design
- [zeplin](https://zpl.io/agrvXjN)
- [design doc](https://xx13.github.io/vuestic_redesign/#dropdown_selects)

must based on dropdown component

### Props
- [x] v-model
- [x] options - array of objects {text, value, icon} - if icon is provided, it will appear at the left of the option https://prnt.sc/msyk4c
- [x] readonly - boolean
- [x] placeholder - string | slot
- [x] multiple - boolean
- [ ] chips - boolean - (only for multiple) - default: true - if set to true, the selections will appear as chips (instead of comma separated strings) on the input frame
- [x] max - number - the max number of chips, when the number of selected items is bigger then max, there is only text '6 items selected'
- [x] selectedText - string - this text will be shown inside the input, if it will be provided
- [x] clearable - boolean - default: true
- [x] loading - boolean - set loading icon in dropdown area instead of options
- [x] searchable - boolean - default: false - if set true, input can be edited and options are filter automatically by inputted text

**extended props**
- [x] position - string- 'bottom', 'top'
- [x] disabled - boolean
- [x]  maxWidth - string (125px) or number (125) - the default value is the width of input
- [x] maxHeight - string or number
- [x] absolute - set the position absolute
- [ ] noFade - boolean - default: false - disable fade animation

extra: I'm not sure that we actually need it now, but the design has the variant with grouped options. https://prnt.sc/msywrz . see the reference to the idea of implementation - (not needed, same for horizontal groups - @asvae)

### References
- [quasar](https://quasar-framework.org/components/select.html)
- [ant design](https://vue.ant.design/components/select/)([source](https://github.com/vueComponent/ant-design-vue/tree/master/components/vc-select)
- [vuetify](https://vuetifyjs.com/en/components/selects#select) ([source](https://github.com/vuetifyjs/vuetify/tree/master/packages/vuetify/src/components/VSelect))
- [option group](https://vue.ant.design/components/select/#components-select-demo-option-group)
- [vue-multiselect](https://github.com/shentao/vue-multiselect) - well tested and streamlined multiselect without feature bloat.

**Comment by smartapant** [comment]
@asvae any update on this one?
