### ISSUE TITLE
bug: wizard fails validating

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#497]
Original report:
> In the examples of the wizard forms there is no example of how to integrate a Date time picker or the Checkboxes, Radios or Switches.
The problem is in the validation of the content. I can not continue to the next step if I integrate something other than an Input or a Select.

From my understanding - wizard fails to progress to next step if any of following components are used inside:
- [x] Date time 
- [x] Checkboxes
- [x] Radios
- [x] Switches
We have to check these. Changes should go to master as wizard will be overhauled in 2.0.

**Comment by AlexanderBoriskin** [comment]
See wiki description:
https://github.com/epicmaxco/vuestic-admin/wiki/Wizards
