### ISSUE TITLE
UI - Oversized Donut while exploring dev demo

### ISSUE THREAD

**Issue by bdeanindy** [epicmaxco/vuestic-admin#5]
Environment:
* Ubuntu Xenial
* Google Chrome

After a fresh `clone`, `npm install`, and `npm run dev` the app opened as expected, but when I clicked on the "Explore" button, the donut displayed exists beyond its containing element visually.

Looks like it could be related to this styling rendered in the browser:

```width: 100%; height: 200%; position: relative;```

~~The above appears to come from the fact this component is picking up the base chart component display of, `flex`. When that is overridden, this chart displays properly.~~

![oversized_donut_screenshot](https://user-images.githubusercontent.com/2376876/28987040-7795575c-791e-11e7-9164-b29dccc2c9ac.png)

I am trying to debug and confirm that overriding this, for ONLY that specific chart, operates as I would expected and if it does, I will submit a PR.

**Comment by bdeanindy** [comment]
So I reset my Git head back to when I first cloned, opened [Statistics -> Charts](http://localhost:8080/#/statistics/charts) and I see the same issue with all of the charts, they all have the wrapper to the `<iframe>` having a `height: 200%`.

So I am going to poke around a few more minutes to see if I can figure out where this is coming from (of course, I've never used Vue.js before, so this is a learning experience for me in several ways).

**Comment by bdeanindy** [comment]
Ok, after some archaeology, I discovered that this appears to be an issue with the [Vue-ChartJS Base Charts](https://github.com/apertureless/vue-chartjs/tree/develop/src/BaseCharts) having the height of all elements set to `200%`. I am unsure if this is intentional, but I would think it is not.

The result of this is that all the charts used anywhere in your app are then doubled in height as compared to their parent element's height.

Would you like to close this issue and have me create an issue on their lib, keep this issue open and link to a new issue on that lib, or what precisely?

**Comment by smartapant** [comment]
@bdeanindy thank you for your investigation! We will check this thing after the weekend. Quite strange issue though

**Comment by bdeanindy** [comment]
Just to be proactive, I asked this question (and pointed back to this issue in my question) on the [Vue-ChartJS issue tracker](https://github.com/apertureless/vue-chartjs/issues/164).

**Comment by apertureless** [comment]
Sorry, my fault 🙈  
With `vue-chartjs@2.8.0` I introduced dynamic styles for the div containing the canvas. However the 200% height was a typo. 

Should be fixed with `vue-chartjs@2.8.1` 

✌️

**Comment by bdeanindy** [comment]
@apertureless thanks for the quick fix.
