### ISSUE TITLE
Flow Type Support

### ISSUE THREAD

**Issue by Vad1mo** [epicmaxco/vuestic-admin#50]
Having types in JavaScript is a nice feature. TypeScript is one option, however a better one is to user flowtype. 

I was trying to integrate flow type with vuestatic based on this tutorial:
https://alligator.io/vuejs/components-flow/

My question is can flow be integrated into vuestic-admin officially? 

It has no overhead such as typescript and improves the dev workflow.

**Comment by jean-moldovan** [comment]
Will consider adding this to our roadmap. Thank four your feedback!
