### ISSUE TITLE
yarn book:serve - fix errors

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#509]

**Comment by jean-moldovan** [comment]
Please provider more info on what needs to be fixed here.

**Comment by jean-moldovan** [comment]
Am I correct that the issue is that shared components are not loaded in "book" mode?

**Comment by smartapant** [comment]
@asvae ?

**Comment by asvae** [comment]
@jean-moldovan you can talk with @smellyshovel. I discussed this matter with him recently.

In short `serve:book` has too many errors/problems. Should have none.
