### ISSUE TITLE
Make accordion default open/expanded.

### ISSUE THREAD

**Issue by grafxflow** [epicmaxco/vuestic-admin#515]
Is there a way of making the accordion default set to open/expanded?

**Comment by asvae** [comment]
I think the simplest solution until 2.0 is out would be to copy component from `develop` branch.

* [Demo](http://vuestic-epicmax.asva.by/#/demo/vuestic-theme/vuestic-components/va-collapse/VaCollapse.demo.vue)

* [Components to copy](https://github.com/epicmaxco/vuestic-admin/tree/develop/src/vuestic-theme/vuestic-components/va-collapse)

**Comment by grafxflow** [comment]
So it's best to use collapse for the active state of open?

**Comment by asvae** [comment]
Yep. You can use collapse without accordion.
The sole point of accordion is to have only single collapse open, actually.

**Comment by grafxflow** [comment]
Okay I have sorted it by duping the same actions on both the mounted and watch. 👍
