### ISSUE TITLE
VuesticDataTable with external data

### ISSUE THREAD

**Issue by 6miramira** [epicmaxco/vuestic-admin#52]
I don't understand the flow of processing raw data from external API into table in front end. Like, is it right if I want to show data from REST API, I just have to change this code : 
`data () {`
      `return {`
        `apiUrl: 'http://vuetable.ratiw.net/api/users',`
        `apiMode: true,`
       `tableFields: FieldsDef.tableFields,`
        `itemsPerPage: ItemsPerPageDef.itemsPerPage,`
        `sortFunctions: FieldsDef.sortFunctions,`
        `paginationPath: ''`
      `}`
    `}`
(Table.vue)

into : 
`data () {`
      `return {`
        `apiUrl: 'http://localhost:4000/event',`
        `apiMode: true,`
        `tableFields: FieldsDef.tableFields,`
        `itemsPerPage: ItemsPerPageDef.itemsPerPage,`
        `sortFunctions: FieldsDef.sortFunctions,`
        `paginationPath: ''`
      `}`
    `}`

Because it doesn't work, I still don't get the data from localhost:4000, the Table shows "No Data Available", eventhough it sends the right response when I checked it using Postman.

**Comment by gramlin** [comment]
Are you setting the return-header: Access-Control-Allow-Origin to * 
That was what I had to do to get it to work.

**Comment by 6miramira** [comment]
@gramlin Thank you for replied. Yes, I forgot to add the authorization in configuration file. But now I've stuck on pagination issue. Because the response i got from my API doesn't contain pagination information like what we got from https://vuetable.ratiw.net/api/users. Maybe the same case had happened to you? Would you like to tell me how to fix it? I'm a newbie to Vuejs :(

**Comment by smartapant** [comment]
@alexanderrudnik could you please have a look into @6miramira pagination issue?

**Comment by jean-moldovan** [comment]
@6miramira , Please see https://github.com/ratiw/vuetable-2-tutorial/wiki/lesson-07#pagination-data-structure for more information

**Comment by Dzipai** [comment]
Hi guys,How do I send a POST request to a REST API using the above Vue template
