### ISSUE TITLE
Importing router on Vuex module crashes the whole application

### ISSUE THREAD

**Issue by Zimmerr** [epicmaxco/vuestic-admin#542]
I'm submitting a ...
  - [X] bug report
  - [ ] feature request
  - [ ] support request 

Hey guys, im planning to use Vuestic theme to build a system. As im a beginner to VueJS, im trying to implement the Log In screen using a authentication API that i have on my machine for another system. Everything goes OK, the request is made, and the 200 is returned.
The problem started when i tried to redirect to the main page after the request was done. I tried to do `router.push('/')` after doing the `import router from '@/router'`, but this import line didnt worked, and everything in the application stopped working after this with the following error:

    import store from '@/store'
 
    let palette = store.getters.palette

> VuesticChartConfigs.js?4e61:3 Uncaught TypeError: Cannot read property 'getters' of undefined
>     at eval (VuesticChartConfigs.js?4e61:3)
>     at Module../src/vuestic-theme/vuestic-components/vuestic-chart/VuesticChartConfigs.js (index.js:27514)
>     at __webpack_require__ (index.js:725)
>     at fn (index.js:102)
>     at eval (chartMixin.js:6)
>     at Module../src/vuestic-theme/vuestic-components/vuestic-chart/chart-types/chartMixin.js (index.js:27598)
>     at __webpack_require__ (index.js:725)
>     at fn (index.js:102)
>     at eval (PieChart.js?1bf0:1)
>     at Module../src/vuestic-theme/vuestic-components/vuestic-chart/chart-types/PieChart.js (index.js:27574)

I strongly believe that the Vuex Store is crashing because of my import, but i really dont know why, below here i 'll leave all the code that im using to do the login. Im using Vuex and Vue-router as provided in this template, and i wanted to fix this error above. Its directly caused by the importing of the router, but i cant find a workaround of how to properly import the router to my module

**Vuex Store - src/store/index.js**

    import Vue from 'vue'
    import Vuex from 'vuex'
    import VuexI18n from 'vuex-i18n' // load vuex i18n module
    import app from './modules/app'
    import { authentication } from './modules/authentication.module';
    //import router from '@/router'; //tried to import here, but still crashes
    import * as getters from './getters'
    
    Vue.use(Vuex)
    
    const store = new Vuex.Store({
      strict: true, // process.env.NODE_ENV !== 'production',
      getters,
      modules: {
        app,
        authentication,
      },
      state: {},
      mutations: {},
    })
    
    Vue.use(VuexI18n.plugin, store)
    
    export default store
    
**Authentication component - src/store/modules/authentication.module.js**

    import { LoginService } from '@/services';
    import router from '@/router'; //this causes the error, it works without this line, but i wanted to import the router so i could do the router.push('/')
    
    const user = JSON.parse(localStorage.getItem('user'));
    const initialState = user
        ? { status: { loggedIn: true }, user }
        : { status: {}, user: null };
    
    export const authentication = {
        namespaced: true,
        state: initialState,
        actions: {
            login({ dispatch, commit }, { username, password }) {
                commit('loginRequest', { username });
                console.log({username,password})
                LoginService.getUsers({username, password}) //the request is made here, i dont think its relevant posting the LoginService code as it works as intended
                    .then(
                        user => {
                            commit('loginSuccess', user);
                            //router.push('/'); //thats what i would to do with the router, if the import worked
                        },
                        error => {
                            commit('loginFailure', error);
                            //dispatch('alert/error', error, { root: true });
                        }
                    );
            },
            logout({ commit }) {
                LoginService.logout();
                commit('logout');
            }
        },
        mutations: {
            loginRequest(state, user) {
                state.status = { loggingIn: true };
                state.user = user;
            },
            loginSuccess(state, user) {
                state.status = { loggedIn: true };
                state.user = user;
            },
            loginFailure(state) {
                state.status = {};
                state.user = null;
            },
            logout(state) {
                state.status = {};
                state.user = null;
            }
        }
    }

Router is unchanged and works as intended. I tried using `this.$router.push('/')` on the Login button directly, and it works as intended. Also tried the same code instead of the router.push('/') on the module, but it says that this.$router is undefined, so i guess that the router cant be acessed directly from the module without a import for some reason. All i needed to know is why the page crashes if i import the router manually and how can i fix it?

**Comment by asvae** [comment]
Hi. Very nice and detailed issue.

I got a repro. My first guess, is that there is a mutual import somewhere:

```js
// module1.js
import module2 from 'module2'

// module2.js
import module1 from 'module1'
```

Webpack resolves these concurrently and `module1` will be `undefined`.

I'll think of something in a bit.

**Comment by asvae** [comment]
I tried a couple of things without much success.

So I think we can move in another direction and do a watcher in `App.vue`, somewhat like this:

```js
watch: {
  isAuthenticated (isAuthenticated) {
    if (isAuthenticated) {
      this.$router.push('/')
    }
  }
}
```

Where `isAuthenticated` you can derive with computed. Let me know how it goes.

**Comment by Zimmerr** [comment]
Thanks very much for your answer! I really liked this approach, and after some effort to figure out what would be the best way to do the isAuthenticated property, it worked! This is my app.vue now:

**\src\App.vue**

        <template>
      <div id="app" class="app">
        <router-view/>
      </div>
    </template>
    
    <script>
    export default {
      name: 'app',
      data (){
        return {
          //isAuthenticated: false,
        }
      },
    
      computed: {
        isAuthenticated: function(){
          //var x = JSON.parse(localStorage.getItem('user'));
          var x = this.$store.state.authentication.status.loggedIn;
          console.log(x);
          if(typeof(x) !== 'undefined' && x !== null){
            return true;
          }
          else return false;
       
        },
      },
      watch: {
        isAuthenticated:{
          handler (isAuthenticated) {
            console.log(isAuthenticated)
            if (isAuthenticated) {
              this.$router.push('/')
            }
          }
        },
      }
    }
    </script>
    
    <style lang="scss">
    @import "sass/main";
    
    body {
      height: 100%;
      #app {
        height: 100%;
      }
    }
    </style>
    
I tried to watch the localStorage user property, but it didnt worked, and the computed value didnt changed after a sucessful login. Now that im watching the store state its working properly. 

Also, friday night i found other approach that seems to work, but i dont know if its a bad thing to do. It involved renaming the main Vue export, and importing the whole main in authentication.module.js. I'll show you the code:

**/src/main.js** 

    //new Vue({
    //  el: '#app',
    //  router,
    //  store,
    //  render: h => h(App),
    //})
    // this is the default way, below i renamed the new Vue object

    export const vm = new Vue({
      el: '#app',
      router,
      store,
      render: h => h(App),
    })

**src/store/modules/authentication.module.js**

    import { LoginService } from '@/services';
    //import router from '@/router';
    import { vm } from '@/main' //importing the whole main using the alias 'vm'
    
    const user = JSON.parse(localStorage.getItem('user'));
    const initialState = user
        ? { status: { loggedIn: true }, user }
        : { status: {}, user: null };
    
    export const authentication = {
        namespaced: true,
        state: initialState,
        actions: {
            login({ dispatch, commit }, { username, password }) {
                commit('loginRequest', { username });
                console.log({username,password})
                LoginService.getUsers({username, password})
                    .then(
                        user => {
                            commit('loginSuccess', user);
                            vm.$router.push('/'); //acessing the router using the main we imported
                        },
                        error => {
                            commit('loginFailure', error);
                            //dispatch('alert/error', error, { root: true });
                        }
                    );
            },
            logout({ commit }) {
                LoginService.logout();
                commit('logout');
            }
        },
        mutations: {
            loginRequest(state, user) {
                state.status = { loggingIn: true };
                state.user = user;
            },
            loginSuccess(state, user) {
                state.status = { loggedIn: true };
                state.user = user;
            },
            loginFailure(state) {
                state.status = {};
                state.user = null;
            },
            logout(state) {
                state.status = {};
                state.user = null;
            }
        }
    }

This approach also worked, but i dont know how bad is renaming the Vue object and then importing the whole main.js, specially because as you said in your answer mutual imports causes problem within the web-pack, and i dont know if doing multiple imports is something that i should do considering good coding pratices. What do you think that is the best approach?

**Comment by asvae** [comment]
> This is my app.vue now
Looks perfectly functional.

> It involved renaming the main Vue export
I have no idea why that works frankly. Black magic :D.

> What do you think that is the best approach
The solution I've shown is called Guard Component. The intention behind is that a component encapsulates auth logic, does needed configs and bounces off unauthorized users. As a result, wrapped components don's have to care about these things. In no way the child will be rendered if user is unauthorized or doesn't have appropriate permissions.
