### ISSUE TITLE
`a href` button is green on hover

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#546]
- [ ] should be white

* [demo](http://localhost:8080/#/demo/vuestic-theme/vuestic-components/va-button/VaButton.demo.vue) 

![image](https://user-images.githubusercontent.com/5394573/56174943-aae4d980-5ffd-11e9-8125-563cbe31b1ef.png)

**Comment by smellyshovel** [comment]
Isn't it solved yet with the removal of bootstrap?

**Comment by smellyshovel** [comment]
Fixed with #597.
