### ISSUE TITLE
Cannot run npm instaill

### ISSUE THREAD

**Issue by shaqaruden** [epicmaxco/vuestic-admin#55]
Dependencies need to be updated for this projected. Lots of deprecation warnings, out of date versions and 404 on node-sass

> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

HTTP error 404 Not Found

**Comment by shaqaruden** [comment]
Here are the warnings

> warning kewler > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.
> warning chalk@2.0.1: Please upgrade to Chalk 2.1.0 - template literals in this version (2.0.1) are quite buggy.
> warning "bootstrap-vue > bootstrap@4.0.0-beta.2" has unmet peer dependency "jquery@1.9.1 - 3".
> warning "bootstrap-vue > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".
> warning " > vue-bulma-expanding@0.0.0" has unmet peer dependency "bulma@^0.1".
> warning " > vuex-router-sync@4.0.2" has incorrect peer dependency "vuex@^2.0.0".
> warning " > vuex-router-sync@4.0.2" has incorrect peer dependency "vue-router@^2.0.0".
> warning " > eslint-config-standard@10.2.1" has incorrect peer dependency "eslint-plugin-promise@>=3.5.0".

**Comment by smartapant** [comment]
@shaqaruden oh! that's really important

**Comment by smartapant** [comment]
@alexanderrudnik please check it tomorrow

**Comment by alexanderrudnik** [comment]
hi @shaqaruden , thanks for your remarks!
We fixed almost all warnings except of:

> warning babel-preset-es2015@6.24.1: ï¿½ Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

> warning kewler > lodash.isarray@4.0.0: This package is deprecated. Use Array.isArray.

We cant fix it because they are used to support other dependencies (vuetable-2 for example)

As about 
> warning "bootstrap-vue > bootstrap@4.0.0-beta.2" has unmet peer dependency "jquery@1.9.1 - 3".

> warning "bootstrap-vue > bootstrap@4.0.0-beta.2" has unmet peer dependency "popper.js@^1.12.3".

and 404 NOT FOUND

> node scripts/install.js
Downloading binary from https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.5.3/win32-x64-59_binding.node":

we couldn't reproduce it. 
Could you please provide more info ?

**Comment by alexanderrudnik** [comment]
@shaqaruden 
according to [this PR](https://github.com/epicmaxco/vuestic-admin/pull/51) you may face 404 NOT FOUND node-sass error if you are using Windows 10. Please update your code and check
