### ISSUE TITLE
Badge should have the same height  for outline and normal

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#550]
- [ ] fix eet!

![image](https://user-images.githubusercontent.com/5394573/56308183-4f2a6580-614f-11e9-9b48-278c0e4c7f9c.png)

**Comment by jean-moldovan** [comment]
Problem also exists for VaChip & VaButton

**Comment by smellyshovel** [comment]
#589 merged. Closing this one.
