### ISSUE TITLE
Add a sidebar-link-group inside a sidebar-link-group.

### ISSUE THREAD

**Issue by rochamc** [epicmaxco/vuestic-admin#557]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Hello.

We've been trying to add sidebar-link-group inside another sidebar-link-group but with no success (the second level sidebar-link-group doesn't resize properly). We couldn't find anywhere a way to add a third level easily.

Thanks for your help.

**Comment by ssemenkoff** [comment]
At the moment you can't have sidebar-link-group inside a sidebar-link-group by design. We plan to rework this component at some time, but it's not in the nearest future.
