### ISSUE TITLE
VuesticSwitch toggle listen for option change

### ISSUE THREAD

**Issue by motatoes** [epicmaxco/vuestic-admin#558]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
When using a `VuesticSwitch` component there is no way to listen for element `change`. It is possible to listen for the `v-on:input` event, however the problem is that this is fired when [component is mounted](https://github.com/epicmaxco/vuestic-admin/blob/master/src/vuestic-theme/vuestic-components/vuestic-switch/VuesticSwitch.vue#L21) and therefore it cannot be used to track option changes in the switch component.

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
To reroduce:

```
<template>
  <div>
      <vuestic-switch v-on:input="updated" v-model="globalVisibility">
        <span slot="trueTitle">Visible</span>
        <span slot="falseTitle">Hidden</span>
      </vuestic-switch>          
  </div>
</template>

<script>
export default {
  data () {
    return {globalVisibility: false}
  },
  methods: 
    update () {
       alert('switch was updated')
    }
  }
}
</script>
```

* **What is the expected behavior?**
The alert should not occur as soon as the component is mounted. This is not the case

* **What is the motivation / use case for changing the behavior?**
In order to correctly listen for element `change` we either need to introduce a `change` event to be emitted in the `setValue` method, or we can comment out [this line](https://github.com/epicmaxco/vuestic-admin/blob/master/src/vuestic-theme/vuestic-components/vuestic-switch/VuesticSwitch.vue#L21)) from the component

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
N/A

**Comment by asvae** [comment]
Thanks.

Works as you described in for toggle and checkbox elements in 2.0.
