### ISSUE TITLE
Vuestic 2.0 Pagination

### ISSUE THREAD

**Issue by lkho** [epicmaxco/vuestic-admin#560]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**

VaPagination shows incorrect pages, when:
visiblePages > total pages

* **What is the expected behavior?**
visiblePages should be wrapped to `Math.max(visiblePages, pages)`

* **Other information**
https://github.com/epicmaxco/vuestic-admin/pull/468
https://github.com/epicmaxco/vuestic-admin/pull/468/commits/da942a8d1c3310f6fda9e88e76756cf02bdbbb7d#diff-23ec931fc86bceec4e12313c7b7bff4b

**Comment by jean-moldovan** [comment]
Fix will be available in `2.0.0`. Thanks!
