### ISSUE TITLE
Side menu disappearing

### ISSUE THREAD

**Issue by Zimmerr** [epicmaxco/vuestic-admin#561]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

The side menu disappear if you collapse a lot of components, then click on one of the last ones. To replicate the problem, open all collapses, go to the last one(Error pages) and click on it. The side menu will disappear completely and will only appear again after refreshing the page.

Also, it seems like if you dont open sufficient collapses(like half of them), the side menu will only shrinks, but will grow again after you scroll up (but will shrink again if you scroll down).

This is a very strange behaviour, and i believe its a critical issue as the whole menu disappears, and you cant go to any other page

**Comment by nastassiadanilova** [comment]
va-sidebar was completely overhauled in vuestic 2.0. So, I think this task can be closed.
