### ISSUE TITLE
ProfileDropdown hitbox limited to the link.

### ISSUE THREAD

**Issue by rochamc** [epicmaxco/vuestic-admin#562]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
The ProfileDropdown in the navbar has a hitbox limited to the link (<a href="#"...).

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Just access the Profile Dropdown.

* **What is the expected behavior?**
Hitbox over the div.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Our fix suggestion would be like below:

ProfileDropdown.vue
```
<div v-for="option in options" :key="option.name">
  <router-link :to="{name: option.redirectTo}" class="plain-link"
          @click.native="logout(option.name)" href="#">
      <div class="dropdown-item plain-link-item">
            {{ $t(`user.${option.name}`) }}
      </div>
  </router-link>
</div>
```
*Added a div inside the router-link with the class dropdown-item plain-link-item.

_variables.scss
```
$dropdown-link-color: $vue-green;
$dropdown-box-shadow: $greeny-box-shadow;
$dropdown-background: $darkest-gray;
$dropdown-link-hover-color: lighten($dropdown-link-color, 10%);;
$dropdown-link-hover-bg: $almost-black;
$dropdown-link-active-color: $white;
```
*Changed the $dropdown-link-color to $vue-green and removed a duplicated one, and changed $dropdown-link-hover-color to lighten($dropdown-link-color, 10%).

**Comment by asvae** [comment]
Please reopen if still relevant
