### ISSUE TITLE
Checkbox should have array access

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#564]
* **I'm submitting a ...**
  - [x] feature request

* **What is the motivation / use case for changing the behavior?**
It's widely useful. Especially for smaller apps.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Interface might look like this
```html
<va-checkbox v-model="array" arrayValue="one"/>
<va-checkbox v-model="array" arrayValue="two"/>
```

- [ ] If `arrayValue` is included in array - checkbox should be selected.
- [ ] On change checkbox should emit new array with `arrayValue` added/removed.

**Comment by serjilyashenko** [comment]
Hi there
I would like to work on this issue.

I have made some research and created some prototype.
![ScreenRecording20190523at1](https://user-images.githubusercontent.com/16863087/58244008-6cf47700-7d5a-11e9-871d-e1489baae568.gif)

This example works well with arrays of strings. But it is necessary to think how to handle arrays of objects.

Also "va-checkbox" component currently exists. And fixing of it will lead to breaking changes.
I suggest to consider new component which includes existing checkbox component.

**Comment by serjilyashenko** [comment]
It was decided to implement functionality identical to va-toggle.
The component checks whether the array received or not and choses correct behavior.
