### ISSUE TITLE
VaInput append slot

### ISSUE THREAD

**Issue by lkho** [epicmaxco/vuestic-admin#578]
* **I'm submitting a ...**
  - [x] bug report

https://github.com/epicmaxco/vuestic-admin/blob/ecbb12a046060f38b74ccdd410643dfae3912178/src/vuestic-theme/vuestic-components/va-input/VaInput.vue#L70

should it be `slot=append` or `name=append`? In my understanding, it should be `name=append`, with regards to https://github.com/epicmaxco/vuestic-admin/blob/ecbb12a046060f38b74ccdd410643dfae3912178/src/vuestic-theme/vuestic-components/va-input/VaInput.vue#L55

**Comment by nastassiadanilova** [comment]
@lkho I've fixed it https://github.com/epicmaxco/vuestic-admin/blob/c64e8ed92270d2e73c9094054db85a57a4031883/src/vuestic-theme/vuestic-components/va-input/VaInput.vue#L70
Thanks!
