### ISSUE TITLE
va-topbar

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#581]
https://zpl.io/aN90Glv 
https://zpl.io/2ZkJ46J

add a top bar to the layout

**Comment by smellyshovel** [comment]
@nastassiadanilova how would this interlace with the sidebar? Do we just get rid of the last? Or is it a "sidebar for mobiles" or something?

**Comment by nastassiadanilova** [comment]
@smellyshovel the idea is that we can switch navigation layout between topbar/sidebar view with some controls https://zpl.io/bzq5YQz 
actually, topbar is already implemented, but it has some problems, so we've decided to return to it in vuestic2.1

**Comment by smellyshovel** [comment]
The work is conducted over [here](https://github.com/epicmaxco/vuestic-admin/pull/646).

Something works already, but there're many imperfections to be fixed.

**Comment by asvae** [comment]
Work in progress

**Comment by asvae** [comment]
@Kreezag this PR just requires some QA. Seems to be mostly done.

For QA we need to get proper admin + ui versions (`yarn link`).
