### ISSUE TITLE
Form Wizard - remove from 2.0 version

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#584]
Current form wizards are just a strange piece of code. Will make new version from scratch with new designs provided by @xx13 in 2.1 version.

- [x] Remove Form Wizards page and routes
- [x] Remove Form Wizards from i18n files
- [x] Remove Form Wizards from vuestic-theme folder
- [x] Remove Form Wizards from breadcrumbs

**Comment by smellyshovel** [comment]
#592 merged. Closing this one.
