### ISSUE TITLE
IE11 support

### ISSUE THREAD

**Issue by starchand** [epicmaxco/vuestic-admin#61]
IE11 support is not supported?

**Comment by smartapant** [comment]
@starchand we use unix (linux and os x) in team, tried Edge only :(

**Comment by jean-moldovan** [comment]
IE11 is not supported, sorry about that.

**Comment by starchand** [comment]
Personally I feel this should be stated more clearly on the README.md or in the documentation. 
IE10 and 11 are still wildly used in the enterprise, which I would guess is also the biggest market requiring admin dashboard's.

**Comment by jean-moldovan** [comment]
Sorry about your bad experience with the dashboard. Readme is to be updated.

Thanks!
