### ISSUE TITLE
VaSliderColorPicker saturation last segment doesn't highlight at the first click

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-admin#612]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A bug.
* **What is the current behavior?**

![Peek 2019-07-24 12-40](https://user-images.githubusercontent.com/9782236/61783716-fd117400-ae10-11e9-9aa7-3204c26b359f.gif)

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

The last segment of the saturation picker doesn't recognize a click at the first time. The color is changed, but the segment isn't highlighted.

* **What is the expected behavior?**

Opposite to described above.

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
@smellyshovel known problem.

Decision was - won't fix. Too minor problem.
