### ISSUE TITLE
Vuestic bugs.

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#616]
Add found bugs as comments behind this issue. One comment - one bug. Thanks.

Testing strategy is described in #610.

Check current staging here: http://vuestic-epicmax.asva.by

## ❗ To note

* if you finished working on post - make a notice in header (such as "addressed in `release`"),
* make sure to increment the *№* of your bug submit so that it can be easier to track, group and fix them.
* Please leave a notice if bug reproduces only on safari or something obscure.
* `P5` in header means highest priority (must be done till release). `P1` - means we can ignore. 2-4 - in betweenish. When fixing, select items with higher priority.

## Conventions

:rocket: means that the bug is fixed, checked and approved
:eyes: means that somebody's already working on the bug report and you should pick another one

### Not fixed, but in progress

**Comment by asvae** [comment]
![image](https://user-images.githubusercontent.com/5394573/61881686-b77fa480-aeff-11e9-8059-5fe98bab20c0.png)

Not centered properly.

**Comment by alexanderrudnik** [comment]
Navbar issue:

How to reproduce: click 2+ items (messages and notifications)

![Screen Shot 2019-07-25 at 5 15 50 PM](https://user-images.githubusercontent.com/9514327/61881861-062d3e80-af00-11e9-8e30-66364e7c3a25.png)

**Comment by smartapant** [comment]
Dashboard page: malformed alignment and height of some elements.

How to reproduce: large screens (24" 2k display)

![Screen Shot 2019-07-25 at 5 20 05 PM](https://user-images.githubusercontent.com/3674348/61882285-d92d5b80-af00-11e9-9aff-90533e3ba0d0.png)
![Screen Shot 2019-07-25 at 5 20 20 PM](https://user-images.githubusercontent.com/3674348/61882286-d9c5f200-af00-11e9-9e9f-d3826dc58842.png)

**Comment by smartapant** [comment]
Login/Signup page is missing

![Screen Shot 2019-07-25 at 5 34 12 PM](https://user-images.githubusercontent.com/3674348/61883126-83f24980-af02-11e9-86a2-98015da43bc4.png)

**Comment by nastassiadanilova** [comment]
old version of inputs http://vuestic-epicmax.asva.by/#/admin/ui/icons/vuestic http://vuestic-epicmax.asva.by/#/admin/ui/tree-view
![1](https://user-images.githubusercontent.com/11391037/61883170-97051980-af02-11e9-842f-9e7d540d341c.png)
![2](https://user-images.githubusercontent.com/11391037/61883173-98364680-af02-11e9-8e06-30ff3bbbaa92.png)

**Comment by ESadouski** [comment]
![image](https://user-images.githubusercontent.com/9255839/61883292-d2074d00-af02-11e9-9467-16ec285ee786.png)
Chrome. Toggle menu item and then immediately hover another one.

**Comment by nastassiadanilova** [comment]
chat doesn't use the color theme
![4](https://user-images.githubusercontent.com/11391037/61883390-0975f980-af03-11e9-928d-fad3475ccb89.png)

**Comment by smartapant** [comment]
Tabs:
1. Not easy to use on small screens (and scroll is ugly)
2. No separate UI Elements -> Tabs page

<img width="375" alt="tabs" src="https://user-images.githubusercontent.com/3674348/61940631-81ddc880-af9e-11e9-9b70-1c4e88334900.png">

**Comment by smartapant** [comment]
Tables. Reproduced on dashboard page.

1. Impossible to use on mobiles (enable horizontal scroll? or something else)
2. Pagination element is not responsive, should have resizable version (check vuestic 1.9 out)

<img width="438" alt="dashboard-table" src="https://user-images.githubusercontent.com/3674348/61940943-1ea06600-af9f-11e9-985c-ede30d930fe3.png">

**Comment by smartapant** [comment]
Ugly widget on dashboard page on iphone 5 
<img width="376" alt="dashboard-widget-1" src="https://user-images.githubusercontent.com/3674348/61941089-76d76800-af9f-11e9-912d-b78352ff526e.png">

**Comment by smartapant** [comment]
Ugly widget on dashboard page on iphone 5
<img width="369" alt="dashboard-widget-2" src="https://user-images.githubusercontent.com/3674348/61941204-b00fd800-af9f-11e9-89cc-77385639de0f.png">

**Comment by smartapant** [comment]
Navbar Dropdowns are wider than screen and are making page scrollable.

<img width="444" alt="navbar-page-width" src="https://user-images.githubusercontent.com/3674348/61941615-80ad9b00-afa0-11e9-8154-7091517054ee.png">

**Comment by smartapant** [comment]
Auth pages are malformed on all screens.

<img width="676" alt="login-signup-3" src="https://user-images.githubusercontent.com/3674348/61941675-9f139680-afa0-11e9-9250-197e2e57352f.png">
<img width="1231" alt="login-signup-2" src="https://user-images.githubusercontent.com/3674348/61941676-9f139680-afa0-11e9-8b58-27ed70065e9a.png">
<img width="415" alt="login-signup" src="https://user-images.githubusercontent.com/3674348/61941677-9f139680-afa0-11e9-90f1-e4a370412b7c.png">

**Comment by smartapant** [comment]
Progress bars pages.

1. Circles widget is not responsive
2. i18n problem

<img width="240" alt="progress-bars-i18n" src="https://user-images.githubusercontent.com/3674348/61942126-76d86780-afa1-11e9-97e0-98916ebd9573.png">
<img width="364" alt="progress-bars-circles" src="https://user-images.githubusercontent.com/3674348/61942127-76d86780-afa1-11e9-9e91-2591fcd8e7dd.png">

**Comment by AlexanderBoriskin** [comment]
List of components, that don't depend on themes or depends partfully:

1) Datepicker (Forms -> Form Elements)
![image](https://user-images.githubusercontent.com/39219429/61943983-4d213f80-afa5-11e9-9145-de510290d535.png)

2) Button group (Forms -> Medium Editor)
![image](https://user-images.githubusercontent.com/39219429/61944003-56121100-afa5-11e9-95eb-2e41530ebfca.png)

3) Table headers (Table -> Data Tables)
![image](https://user-images.githubusercontent.com/39219429/61944015-5d391f00-afa5-11e9-9525-94e63eb573b9.png)

4) Blockquote (UI Elements -> Typography)
![image](https://user-images.githubusercontent.com/39219429/61944026-64f8c380-afa5-11e9-80fd-add58de2bbd6.png)

5) Timeline titles (UI Elements -> Timelines)
![image](https://user-images.githubusercontent.com/39219429/61944035-6aeea480-afa5-11e9-8f42-d739fb64ead7.png)

**Comment by AlexanderBoriskin** [comment]
Update lists of pages according to current status (Pages -> 404 Pages -> Advanced layout):

![image](https://user-images.githubusercontent.com/39219429/61944293-0da72300-afa6-11e9-8fa2-12403f5ed551.png)

**Comment by smartapant** [comment]
Datepickers:
1. Clicking on disabled opens dropdown, dates can be changed
2. Clicking/tapping on other datepicker-inputs don't open dropdown
3. Dropdown is malformed on mobiles
4. Sometimes, opening dropdowns and changing ranges cause console errors


<img width="690" alt="datepicker-1" src="https://user-images.githubusercontent.com/3674348/61945176-05e87e00-afa8-11e9-9f57-bb1cae25319d.png">
<img width="430" alt="datepicker-2" src="https://user-images.githubusercontent.com/3674348/61945181-084ad800-afa8-11e9-9853-9bcd99dbc870.png">
<img width="800" alt="datepicker-3" src="https://user-images.githubusercontent.com/3674348/61945183-0a149b80-afa8-11e9-8146-4a11239a60f6.png">

**Comment by smartapant** [comment]
Forms. 
1) Sometimes clicking different form elements (from basic inputs and selects to toggles) cause console errors. Might be reproduced with touch events on mobile
2) Multi select clear icon is malformed
3) Input with icon has no icon

<img width="945" alt="forms-1" src="https://user-images.githubusercontent.com/3674348/61945477-c706f800-afa8-11e9-835c-323a33ee0921.png">
<img width="930" alt="forms-2" src="https://user-images.githubusercontent.com/3674348/61945480-c8382500-afa8-11e9-8ea8-5ecbe7d3124a.png">
<img width="395" alt="forms-3" src="https://user-images.githubusercontent.com/3674348/61945484-ca9a7f00-afa8-11e9-8d1e-9cbdea5e2253.png">
<img width="432" alt="forms-4" src="https://user-images.githubusercontent.com/3674348/61945485-cc644280-afa8-11e9-8125-a565d18427aa.png">

**Comment by AlexanderBoriskin** [comment]
Corrupted mobile view on presentation pages:

1) UI Elements -> Button
![image](https://user-images.githubusercontent.com/39219429/61945443-a6d73900-afa8-11e9-926d-e848736b8b13.png)
![image](https://user-images.githubusercontent.com/39219429/61945448-ac348380-afa8-11e9-927c-79a2603f4cee.png)

2) UI Elements -> Color Pickers
![image](https://user-images.githubusercontent.com/39219429/61945467-bfdfea00-afa8-11e9-893f-cd8c9cd1c288.png)
![image](https://user-images.githubusercontent.com/39219429/61945472-c40c0780-afa8-11e9-9fcc-c675b267ebb6.png)

3) UI Elements -> Icons
![image](https://user-images.githubusercontent.com/39219429/61945503-dbe38b80-afa8-11e9-8529-1fd8b9cba319.png)

4) UI Elements -> Spinners
![image](https://user-images.githubusercontent.com/39219429/61945535-ea31a780-afa8-11e9-87bc-9c37d6302ab9.png)

5) UI Elements -> Grid 
![image](https://user-images.githubusercontent.com/39219429/61945557-f61d6980-afa8-11e9-98cb-0081622f8007.png)
![image](https://user-images.githubusercontent.com/39219429/61945568-fb7ab400-afa8-11e9-8eac-50ad7801412d.png)

6) UI Elements -> Chips
![image](https://user-images.githubusercontent.com/39219429/61945576-02a1c200-afa9-11e9-99ec-1a371ead3031.png)
![image](https://user-images.githubusercontent.com/39219429/61945596-0af9fd00-afa9-11e9-9d24-180402644041.png)

7) UI Elements -> Spacing
![image](https://user-images.githubusercontent.com/39219429/61945618-19e0af80-afa9-11e9-9c47-47c7ec469250.png)

**Comment by smartapant** [comment]
Medium editor.
1) Ugly gradient buttons
2) Some console warnings

<img width="873" alt="medium-editor-2" src="https://user-images.githubusercontent.com/3674348/61945894-ccb10d80-afa9-11e9-88fb-df77372a605a.png">
<img width="622" alt="medium-editor-1" src="https://user-images.githubusercontent.com/3674348/61945895-ccb10d80-afa9-11e9-95bf-23ca2d911c54.png">

**Comment by smartapant** [comment]
Buttons page
1. i18n title
2. Button groups and paginations are not responsive, affect page width on mobiles
3. Button toggle colors choice is ugly :)

<img width="236" alt="buttons-1" src="https://user-images.githubusercontent.com/3674348/61948315-274d6800-afb0-11e9-9897-72e03eaed305.png">
<img width="921" alt="buttons-4" src="https://user-images.githubusercontent.com/3674348/61948320-2c121c00-afb0-11e9-821b-760f3b887098.png">
<img width="927" alt="buttons-3" src="https://user-images.githubusercontent.com/3674348/61948321-2caab280-afb0-11e9-8103-55c7b5020ce6.png">
<img width="922" alt="buttons-2" src="https://user-images.githubusercontent.com/3674348/61948322-2caab280-afb0-11e9-8a5d-4a9c9e644769.png">
<img width="267" alt="buttons-5" src="https://user-images.githubusercontent.com/3674348/61948325-30d6d000-afb0-11e9-8a28-096405477778.png">

**Comment by smartapant** [comment]
Color Pickers page responsiveness issues
<img width="481" alt="color-pickers-1" src="https://user-images.githubusercontent.com/3674348/61948650-194c1700-afb1-11e9-9443-a2a7c426c77b.png">
<img width="387" alt="color-pcikers-2" src="https://user-images.githubusercontent.com/3674348/61948651-194c1700-afb1-11e9-83cb-bd08be9eaa26.png">

**Comment by smartapant** [comment]
Mobile Sidebar. Expanding sidebar look stupid :) 
Let's make expanded sidebar full-width on mobiles

<img width="435" alt="Screen Shot 2019-07-26 at 2 26 27 PM" src="https://user-images.githubusercontent.com/3674348/61948851-a1322100-afb1-11e9-9382-89e4361187f3.png">
si

**Comment by smartapant** [comment]
Vertical timeline is broken on mobiles

<img width="421" alt="timeline" src="https://user-images.githubusercontent.com/3674348/61948938-e5252600-afb1-11e9-9513-29a37e058b87.png">

**Comment by smartapant** [comment]
Notifications page width is broken on mobiles
<img width="392" alt="notifications" src="https://user-images.githubusercontent.com/3674348/61949120-6e3c5d00-afb2-11e9-8b61-c39a07e6e503.png">

**Comment by smartapant** [comment]
Icons Page
1. Buttons are aligned badly
2. Range slider works badly with touch events on mobiles
<img width="413" alt="icons-3" src="https://user-images.githubusercontent.com/3674348/61949402-75b03600-afb3-11e9-884c-a401edaa518a.png">
<img width="433" alt="icons-2" src="https://user-images.githubusercontent.com/3674348/61949403-75b03600-afb3-11e9-8d8d-81e898b12ada.png">
<img width="416" alt="icons-1" src="https://user-images.githubusercontent.com/3674348/61949404-7648cc80-afb3-11e9-801e-bd2786aabd3e.png">

**Comment by smartapant** [comment]
Spinners page.
Color picker is too wide on mobiles. Range sliders work badly with touch events.

<img width="418" alt="spinner" src="https://user-images.githubusercontent.com/3674348/61949628-21f21c80-afb4-11e9-83fd-0c19a88d122d.png">

**Comment by smartapant** [comment]
Grid page is not responsive
<img width="367" alt="grid-2" src="https://user-images.githubusercontent.com/3674348/61949804-ad6bad80-afb4-11e9-9d33-e5a6babe4c9f.png">
<img width="447" alt=" grid-1" src="https://user-images.githubusercontent.com/3674348/61949806-ae044400-afb4-11e9-95f1-7e50cfa362ad.png">

**Comment by smartapant** [comment]
File upload. Media Gallery and 'Advanced, media gallery' are not showing selected files on mobile.

<img width="397" alt="file-2" src="https://user-images.githubusercontent.com/3674348/61950161-ba3cd100-afb5-11e9-826b-1dc89334d5bd.png">
<img width="402" alt="file-1" src="https://user-images.githubusercontent.com/3674348/61950162-ba3cd100-afb5-11e9-841d-c74de141ffb7.png">

**Comment by smartapant** [comment]
Chips page. 

Looks shitty (no v/h margins) on smaller screens
<img width="501" alt="Screen Shot 2019-07-26 at 2 58 48 PM" src="https://user-images.githubusercontent.com/3674348/61950336-346d5580-afb6-11e9-88b7-5430b2e57bf7.png">
<img width="436" alt="Screen Shot 2019-07-26 at 2 58 25 PM" src="https://user-images.githubusercontent.com/3674348/61950337-346d5580-afb6-11e9-92d0-585ef243abea.png">

**Comment by smartapant** [comment]
Colors page
Title vertical alignment
<img width="560" alt="colors" src="https://user-images.githubusercontent.com/3674348/61952565-ddb74a00-afbc-11e9-9eff-a0312d740c1d.png">

**Comment by smartapant** [comment]
Spacings page
1. Not responsive
2. Inputs labels are not informative

<img width="554" alt="spacing" src="https://user-images.githubusercontent.com/3674348/61952760-69c97180-afbd-11e9-9dbc-0d611bd7f30f.png">

**Comment by smartapant** [comment]
Sliders are working with touch events badly

**Comment by smartapant** [comment]
Popovers page.

1. Popover position is wrong on mobiles (not centered properly, positioned over sidebar)
2. Tapping on tooltip links on mobile cause page jump, tooltips are not always shown on tap

<img width="447" alt="popovers-1" src="https://user-images.githubusercontent.com/3674348/61953235-8dd98280-afbe-11e9-9dec-c838af68ffbc.png">
<img width="419" alt="popover-2" src="https://user-images.githubusercontent.com/3674348/61953236-8dd98280-afbe-11e9-85de-e4a5f51669f8.png">

**Comment by smartapant** [comment]
Google maps are not working
<img width="1680" alt="Screen Shot 2019-07-26 at 4 06 31 PM" src="https://user-images.githubusercontent.com/3674348/61953703-c332a000-afbf-11e9-8d3f-a2d884628cfe.png">

**Comment by smartapant** [comment]
404 pages.
1) No horizontal paddings on some mobiles
2) Image aligned badly
3) 'Guy' overflows the text
4) ' large text heading' page is not responsive at all


<img width="406" alt="4044" src="https://user-images.githubusercontent.com/3674348/61955489-cdef3400-afc3-11e9-8f1e-53d830d7e9e2.png">
<img width="406" alt="4044" src="https://user-images.githubusercontent.com/3674348/61955604-0abb2b00-afc4-11e9-8597-67def28a702a.png">
<img width="800" alt="4043" src="https://user-images.githubusercontent.com/3674348/61955605-0b53c180-afc4-11e9-8eb1-b402edcf2ba6.png">
<img width="463" alt="4042" src="https://user-images.githubusercontent.com/3674348/61955607-0b53c180-afc4-11e9-996e-a2fa20986247.png">

**Comment by smartapant** [comment]
Dashboard: colors change does not affect charts and map
<img width="897" alt="Screen Shot 2019-07-26 at 4 46 51 PM" src="https://user-images.githubusercontent.com/3674348/61956145-34288680-afc5-11e9-875c-b9365e5dc565.png">
<img width="1335" alt="Screen Shot 2019-07-26 at 4 46 46 PM" src="https://user-images.githubusercontent.com/3674348/61956147-34288680-afc5-11e9-9d5b-b4830d52a71f.png">

**Comment by smartapant** [comment]
Clicking Vuestic logo shall load/reload dashboard page
<img width="1449" alt="Screen Shot 2019-07-26 at 4 56 46 PM" src="https://user-images.githubusercontent.com/3674348/61956817-903fda80-afc6-11e9-9a14-a5fb105eea19.png">

**Comment by smellyshovel** [comment]
# № 39

![Screenshot_20190728_185703](https://user-images.githubusercontent.com/9782236/62009576-9b7f3b80-b169-11e9-8527-d65ab1318d54.png)

`VaDatePicker` seems to use an icon on an input, but there's no icon displayed and hence no way to open the datepicker.

How it's now:

![Screenshot_20190728_185900](https://user-images.githubusercontent.com/9782236/62009606-e0a36d80-b169-11e9-8640-ab870ab785db.png)

How it's should be:

![Screenshot_20190728_185946](https://user-images.githubusercontent.com/9782236/62009617-fca70f00-b169-11e9-8d7e-d13a036cbdd6.png)

Or

![Screenshot_20190728_190013](https://user-images.githubusercontent.com/9782236/62009629-0cbeee80-b16a-11e9-979d-25572985eebe.png)

Don't know exactly. Need suggestions on that.

**Important**: we should check every occurance of `VaInput` and check whether it should display an icon. Seems like it's all due to some undocumented API change.

**Comment by alexanderrudnik** [comment]
Horizontal scroll appears if notifications dropdown is opened and screen width is about 1000px

![Screen Shot 2019-07-29 at 12 46 32 PM](https://user-images.githubusercontent.com/9514327/62038807-1e9ea100-b1ff-11e9-8353-06fac0b43f48.png)

**Comment by nastassiadanilova** [comment]
### №41
You need to press the tab 2 times to move to the next form control

**Comment by asvae** [comment]
# 42-88

Reserved for vasily issues: https://docs.google.com/document/d/1S3-QwgYSouDCc1n24hXM27zAdxsp0KK8-HBAhGxyjOo/edit#

**Comment by smellyshovel** [comment]
# № 89

Make text italic doesn't work in medium editor

![medium](https://user-images.githubusercontent.com/9782236/62208600-06b25300-b3a0-11e9-9674-bf8286a93cbc.gif)

**Comment by smartapant** [comment]
> # № 3 - addressed in #619
> Dashboard page: malformed alignment and height of some elements.
> 
> How to reproduce: large screens (24" 2k display)
> 
> ![Screen Shot 2019-07-25 at 5 20 05 PM](https://user-images.githubusercontent.com/3674348/61882285-d92d5b80-af00-11e9-9aff-90533e3ba0d0.png)
> ![Screen Shot 2019-07-25 at 5 20 20 PM](https://user-images.githubusercontent.com/3674348/61882286-d9c5f200-af00-11e9-9e9f-d3826dc58842.png)

# № 3 - Not Fixed - High Priority
@smellyshovel @asvae This issue still can be reproduced on larger screens (like 24" 2k and 4k resolutions). 
<img width="1279" alt="Снимок экрана 2019-07-31 в 15 10 07" src="https://user-images.githubusercontent.com/3674348/62210893-e7b6bf80-b3a5-11e9-9fd0-f2f30b7eade3.png">

**Comment by smartapant** [comment]
> # № 12 (P3) - addressed in #619
> Navbar Dropdowns are wider than screen and are making page scrollable.
> 
> <img alt="navbar-page-width" width="222" src="https://user-images.githubusercontent.com/3674348/61941615-80ad9b00-afa0-11e9-8154-7091517054ee.png">

@asvae @smellyshovel @nastassiadanilova still can be reproduced
<img width="328" alt="Снимок экрана 2019-07-31 в 16 36 11" src="https://user-images.githubusercontent.com/3674348/62216522-944a6e80-b3b1-11e9-8baa-9f18fa9c92e2.png">

**Comment by nastassiadanilova** [comment]
### №92 
![Screenshot](https://user-images.githubusercontent.com/11391037/62279435-c7910a00-b452-11e9-9e96-9ccafbb09e3f.png)
lists on small resolutions

**Comment by asvae** [comment]
# № 93 No title

![image](https://user-images.githubusercontent.com/5394573/62296534-f1a8f300-b477-11e9-8837-85b5d67b29c6.png)

**Comment by asvae** [comment]
# № 94 Medium editor input

![image](https://user-images.githubusercontent.com/5394573/62297029-0c2f9c00-b479-11e9-9359-5dd3b2e4afb1.png)

**Comment by smellyshovel** [comment]
# № 95

The "Search by name" input field doesn't fit the screen (320pxm iPhone5)

![Screenshot_20190801_211610](https://user-images.githubusercontent.com/9782236/62317146-b6231e80-b4a1-11e9-8772-c0f26aa3fe38.png)

**Comment by smartapant** [comment]
№ 96 - Auth pages are... not great on safari
<img width="566" alt="Снимок экрана 2019-08-02 в 21 05 47" src="https://user-images.githubusercontent.com/3674348/62390523-319cd280-b56b-11e9-85f7-e7e8164dca36.png">

**Comment by smartapant** [comment]
# 97 IE 11 not working

**Comment by smartapant** [comment]
# №98 Sidebar selection - wrong color
See designs vs reality
<img width="178" alt="Screen Shot 2019-08-05 at 6 12 12 PM" src="https://user-images.githubusercontent.com/3674348/62475168-318c1500-b7ad-11e9-8725-cfaa72c943bf.png">
![Screen Shot 2019-08-05 at 6 12 09 PM](https://user-images.githubusercontent.com/3674348/62475169-3224ab80-b7ad-11e9-852e-93ecec3d646f.png)

**Comment by smartapant** [comment]
# №99 Lists are too wide on mobiles, affecting page width
![Screen Shot 2019-08-05 at 6 18 01 PM](https://user-images.githubusercontent.com/3674348/62475319-7748dd80-b7ad-11e9-96a4-84efd4d75aea.png)

**Comment by smartapant** [comment]
# №100 Sidebar doesn't change direction on sidebar expand/collapse

![Screen Shot 2019-08-05 at 6 20 06 PM](https://user-images.githubusercontent.com/3674348/62475485-c858d180-b7ad-11e9-8047-d354639ecb1a.png)

**Comment by smartapant** [comment]
# №101 It's better to have checkbox and 'recover password' on separate lines on xs screens

![Screen Shot 2019-08-05 at 6 24 22 PM](https://user-images.githubusercontent.com/3674348/62475907-af9ceb80-b7ae-11e9-8d71-20bf43ce4aad.png)

**Comment by smellyshovel** [comment]
№102 - toasts stopped working

**Comment by Eugenizer** [comment]
Tables - http://piclair.com/data/rip3q.jpg
1) Full width
2) Padding between widgets

**Comment by Eugenizer** [comment]
Tree view - http://piclair.com/data/m9mbt.jpg
1) Different distance between items

**Comment by Eugenizer** [comment]
Tabs - http://piclair.com/data/urkh7.jpg
It looks strange, maybe tabs width should not be fixed

**Comment by Eugenizer** [comment]
Color pickers - http://piclair.com/data/h0jjw.jpg
1) Input styling 
2) `HEX` font

**Comment by asvae** [comment]
Please do the following

1) Check which items are not done.
2) Split them into separate issue.
3) Close this issue.
