### ISSUE TITLE
Demo site is 404 broken - only white, empty screen

### ISSUE THREAD

**Issue by franktopel** [epicmaxco/vuestic-admin#63]
Request URL:http://67.205.141.92:8000/vuestic
Request Method:GET
Status Code:404 Not Found
Remote Address:67.205.141.92:8000
Referrer Policy:no-referrer-when-downgrade

**Comment by thedude61636** [comment]
http://vuestic.epicmax.co/
the url in the github project should be changed

**Comment by smartapant** [comment]
@franktopel yep, we've killed old demo page and it seems that the only link that leads there is epic-spinners demo page, will fix)
