### ISSUE TITLE
Vuestic v1.*

### ISSUE THREAD

**Issue by homeforce** [epicmaxco/vuestic-admin#634]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Is it possible for showing Vuestic V1.* on a old branch or old demo site?  
I'm more fan of the previous version momently... didn't take the time yet to explore the new version.

**Comment by asvae** [comment]
Hi.

You can just `git checkout v1.9.4` to get `v1.*`.

Overall I would suggest to switch to 2.0. One of things we did is separation of ui components. For 1.* we had components and pages combined, and that made very hard to impossible to migrate changes. For 2.0 it's a matter of updating your deps in yarn or npm.

**Comment by homeforce** [comment]
Yes sounds great but the problem is... i already did customization too your components in the vuestic-theme folder. 😅 

So i don't think i gonna do an upgrade

**Comment by homeforce** [comment]
how can i upgrade the most easy way ?

**Comment by asvae** [comment]
Hmm. There is hardly an easy way.

You can probably get 2.0 and try to frankenstein it on top of your current app. 2.0 is much smaller because components and styles are moved to separate repo.
