### ISSUE TITLE
Fixed position for navbar/sidebar

### ISSUE THREAD

**Issue by Eugenizer** [epicmaxco/vuestic-admin#635]
Navbar / sidebar fixed, content scrollable

**Comment by smellyshovel** [comment]
Proposed a solution #644, but needs further investigation.
Seems like we might have problems with sidebar-link-group dropdown content not being reachable on mobile devices in some cases. Tough i'm not that concerned taking into account that (afaiu) we're about to substitute the sidebar on mobiles with the topbar.
Would like to hear you comments anyway though.

**Comment by lkho** [comment]
I found another bug, may not be related to this issue

https://github.com/epicmaxco/vuestic-ui/blob/e9e7d674a32bde48f02a4d336f9492e1745ecd8c/src/components/vuestic-components/va-sidebar/VaSidebar.vue#L42-L44

forgot to override when the media query changed to `top: $sidebar-mobile-top`

**Comment by ilearnjs** [comment]
Hi @lkho. 
Is that problem still actual?
Could you please provide more details, please.
