### ISSUE TITLE
Wizards

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#639]
- [ ] Provide design for wizard component.
- [ ] Create issue for implementation and link it to current one.

References:
* [Vuetify](https://vuetifyjs.com/en/components/steppers)
* [Ant](https://vuetifyjs.com/en/components/steppers)

**Comment by xx13** [comment]
![wizard](https://user-images.githubusercontent.com/22664941/63871193-1d11f580-c9c4-11e9-857d-027ec03744d0.png)

@asvae @smartapant pls confirm, so I can create a task a share the source file.

**Comment by smartapant** [comment]
@xx13  Looks good. The only thing 'go back' - are you sure it has to be far away from 'next step' btn?

**Comment by xx13** [comment]
@smartapant I like the idea of hiding Go Back button as usually we want users to proceed without turning back.

**Comment by xx13** [comment]
@smartapant @asvae wizards pushed to Zeplin
