### ISSUE TITLE
Make Dashboard page interactive

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#640]
![image.png](https://images.zenhubusercontent.com/5abe21ac4b5806bc2bcd07ea/30d75c7b-cb8b-44cd-a4b3-f0a0650f126a)

All links on page should do something.
Be creative!

**Comment by smartapant** [comment]
Whoever completes this task, please be aware that the PR is present https://github.com/epicmaxco/vuestic-admin/pull/654
