### ISSUE TITLE
Multi select bug

### ISSUE THREAD

**Issue by lelelethu** [epicmaxco/vuestic-admin#648]
Please see code below:
<va-select
                  :label="$t('function-setting.select-role')"
                  v-model="roleSelectModel"
                  textBy="description"
                  keyBy="id"
                  multiple
                  searchable
                  :options="rolesOptions"
                  :noOptionsText="$t('selects.noOptionsText')"
                  noFade="true"
                />

rolesOptions= [{ "id":"1", " description":"des1"},{ "id":"2", " description":"des2"}]

When i select when display is: [Object Object].
I check code then see: {{ valueProxy.join(", ") }} causing this error. Because valueProxy can is array object.
Can you fix this error. Thanks.

**Comment by smellyshovel** [comment]
Already fixed in e70bf90473c9cfbb65fb9ed1f5fc3e7525c5c4e5, though not staged. @asvae, please, update

**Comment by asvae** [comment]
Fixed in vuestic-ui v0.1.9
