### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zzkzzk1984** [epicmaxco/vuestic-admin#649]
E:\workspace\vuestic-admin>yarn install
yarn install v1.17.3
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning @vue/cli-plugin-eslint > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
warning @vue/cli-plugin-unit-jest > jest > jest-cli > prompts > kleur@2.0.2: Please upgrade to kleur@3 or migrate to 'ansi-colors' if you prefer the old syntax. Visit <https://github.com/lukeed/kleur/releases/tag/v3.0.0\> for migration path(s).
warning extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > vue-bulma-expanding@0.0.1" has unmet peer dependency "bulma@>=0.2".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@vue/eslint-config-standard > eslint-plugin-standard@4.0.0" has unmet peer dependency "eslint@>=5.0.0".
warning "@vue/eslint-config-standard > eslint-config-standard@12.0.0" has unmet peer dependency "eslint@>=5.0.0".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.18.2" has unmet peer dependency "eslint@2.x - 6.x".
warning "@vue/eslint-config-standard > eslint-plugin-node@8.0.1" has unmet peer dependency "eslint@>=4.19.1".
warning "@vue/eslint-config-standard > eslint-plugin-node > eslint-plugin-es@1.4.0" has unmet peer dependency "eslint@>=4.19.1".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > babel-jest@24.8.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.6.0" has unmet peer dependency "@babel/core@^7.0.0".
warning " > copy-webpack-plugin@5.0.4" has unmet peer dependency "webpack@^4.0.0".
warning " > extract-text-webpack-plugin@3.0.2" has unmet peer dependency "webpack@^3.1.0".
warning " > file-loader@4.1.0" has unmet peer dependency "webpack@^4.0.0".
warning " > optimize-css-assets-webpack-plugin@5.0.3" has unmet peer dependency "webpack@^4.0.0".
warning " > sass-loader@7.2.0" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
[5/5] Building fresh packages...
[-/3] ⠄ waiting...
[2/3] ⠄ yorkie
error E:\workspace\vuestic-admin\node_modules\node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: E:\workspace\vuestic-admin\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe E:\workspace\vuestic-admin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'E:\\workspace\\vuestic-admin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@12.8.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\workspace\vuestic-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace\vuestic-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace\vuestic-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (E:\workspace\vuestic-admin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (E:\workspace\vuestic-admin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (E:\workspace\vuestic-admin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\which\which.js:89:16
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at E:\workspace\vuestic-admin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (fs.js:165:21) {
gyp verb `which` failed   stack: 'Error: not found: python2\n' +
gyp verb `which` failed     '    at getNotFoundError (E:\\workspace\\vuestic-admin\\node_modules\\which\\which.js:13:12)\n' +
gyp verb `which` failed     '    at F (E:\\workspace\\vuestic-admin\\node_modules\\which\\which.js:68:19)\n' +
gyp verb `which` failed     '    at E (E:\\workspace\\vuestic-admin\\node_modules\\which\\which.js:80:29)\n' +
gyp verb `which` failed     '    at E:\\workspace\\vuestic-admin\\node_modules\\which\\which.js:89:16\n' +
gyp verb `which` failed     '    at E:\\workspace\\vuestic-admin\\node_modules\\isexe\\index.js:42:5\n' +
gyp verb `which` failed     '    at E:\\workspace\\vuestic-admin\\node_modules\\isexe\\windows.js:36:5\n' +
gyp verb `which` failed     '    at FSReqCallback.oncomplete (fs.js:165:21)',
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python D:\Python37-32\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: D:\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:295:12)
gyp ERR! stack     at ChildProcess.emit (events.js:203:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "E:\\workspace\\vuestic-admin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd E:\workspace\vuestic-admin\node_modules\node-sass
gyp ERR! node -v v12.8.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

E:\workspace\vuestic-admin>

**Comment by smellyshovel** [comment]
You're using Node 12, right? Try with 11, it might solve the issue.

**Comment by patrizi** [comment]
Hi, I also have an installation error but in a different way:
npm install 
return "npm ERR! Cannot read property 'match' of undefined"

Add some rows from debug.log:
...
17 silly saveTree     `-- babel-plugin-jest-hoist@24.6.0
18 verbose stack TypeError: Cannot read property 'match' of undefined
18 verbose stack     at tarballToVersion (D:\Apps\nodejs\node_modules\npm\lib\install\inflate-shrinkwrap.js:87:20)
.... 
20 verbose Windows_NT 10.0.18362
21 verbose argv "D:\\Apps\\nodejs\\node.exe" "D:\\Apps\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
22 verbose node v12.4.0
23 verbose npm  v6.9.0
24 error Cannot read property 'match' of undefined
25 verbose exit [ 1, true ]

**Comment by aleksey-korotkevich** [comment]
@patrizi 
Seems like package-lock.json is corrupted, haven't much time to investigate it, but it is definetely package-lock.json to blame :)

Had the same error, but after deletion of the file everything worked fine
Deletion of this file is not a great solution though... But it points to the problem palce that needs attention

**Comment by asvae** [comment]
Course of actions:

1) Regenerate package lock.
2) Create a minor release.
