### ISSUE TITLE
apiUrl - setting headers

### ISSUE THREAD

**Issue by mjalindahl** [epicmaxco/vuestic-admin#65]
My requirement, as with most APIs, requires JWT.  I need to be able to send an "Authorization" header along with the API request.

Is this already supported somehow, or do I just need to replace the whole apiUrl system with an axios call?

Thanks in advance!

**Comment by mjalindahl** [comment]
This is related to Issue #45 opened by kahwooi.  His proposed solution doesn't seem to work, however.

**Comment by smartapant** [comment]
@mjalindahl the way @kahwooi solved the issue is the quite close to the one we use in commercial projects. Check out https://github.com/axios/axios and read it's docs, it's quite easy to use.
