### ISSUE TITLE
AppLayout: Move content specific layout styles to routes instead of main layout

### ISSUE THREAD

**Issue by lkho** [epicmaxco/vuestic-admin#650]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

* **What is the motivation / use case for changing the behavior?**

https://github.com/epicmaxco/vuestic-admin/blob/2a64ca23d0b462e5b4cbdf03570a45ccb69850cb/src/components/admin/AppLayout.vue#L15

I suggest the specific layout styles should be defined in routes instead of the main layout.
Any ideas?

**Comment by asvae** [comment]
I personally wouldn't recommend to define anything at all in routes, except for route stuffs.

The main problem I faced is that route meta approach doesn't really scale. Even medium sized apps had troubles.

What I did instead was a collection of objects like this:
```
{
  route: 'route-name',
  layout: 'base',
  requiresAuth: true,
}
```

They did scale without any problems, providing all needed flexibility.

**Comment by lkho** [comment]
The routes I mean to define in child route components, since I saw AppLayout has a router view

**Comment by asvae** [comment]
@lkho can you throw in some code?

I'm not exactly following.

**Comment by lkho** [comment]
for example put `class="layout gutter--xl fluid"` in 
https://github.com/epicmaxco/vuestic-admin/blob/2a64ca23d0b462e5b4cbdf03570a45ccb69850cb/src/components/dashboard/Dashboard.vue#L2
instead.

**Comment by asvae** [comment]
We plan to switch to tailwind, so this became irrelevant.
