### ISSUE TITLE
AppSidebar: remove hard coded icon set in VaSidebarLink

### ISSUE THREAD

**Issue by lkho** [epicmaxco/vuestic-admin#651]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request

I suggest removing the icon specific classes to NavigationRoutes, so we can use any other icon sets.

https://github.com/epicmaxco/vuestic-admin/blob/2a64ca23d0b462e5b4cbdf03570a45ccb69850cb/src/components/admin/app-sidebar/AppSidebar.vue#L9
https://github.com/epicmaxco/vuestic-admin/blob/2a64ca23d0b462e5b4cbdf03570a45ccb69850cb/src/components/admin/app-sidebar/AppSidebar.vue#L26

Also is the class `sidebar-menu-item-icon` redundant? I can't find the definition anywhere.

Suggested change:
```html
<va-sidebar-link
  :icon="item.meta && item.meta.iconClass"
/>
```

Any ideas?

**Comment by nastassiadanilova** [comment]
These changes are here https://github.com/epicmaxco/vuestic-admin/commit/0cfa4a16109ec227f56d2a2c8530edb555214de6
@lkho, thanks!
