### ISSUE TITLE
Provide the ability to reset the custom theme colors

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#653]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
feature
* **What is the current behavior?**
There is no any way to reset theme colors to defaults when they were changed from the UI
* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **What is the expected behavior?**
--
* **What is the motivation / use case for changing the behavior?**
When the user had an attempt to change the theme, but he is not satisfied with the result he needs to reload the whole page. It should be nice to have the button that will reset the colors to the default theme. Maybe it can be placed in the same dropdown, where theme colors are changed
* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
--

**Comment by asvae** [comment]
We can do as follows:

[Default theme] - button
[primary] - color picker
[success] - color picker
...
