### ISSUE TITLE
va-data-table exposing data-manager for API-mode sorting purpose [feature request]

### ISSUE THREAD

**Issue by lastday4you** [epicmaxco/vuestic-admin#655]
currently I am use va-data-table but after checked the src code of the component I just found that I can't listen to the table label clicked event or the default data-manager so I that can use it to change my api data when user clicked the label to sort

**Comment by jean-moldovan** [comment]
@lastday4you , Thanks for raising this issue. Indeed user should be able to listen to the header label event and implement custom api sorting. We will take a look and see if this can be added in the next version.

Thanks!

**Comment by ssemenkoff** [comment]
Solution proposed in this [pull request](https://github.com/epicmaxco/vuestic-ui/pull/43)
