### ISSUE TITLE
Vuestic as a library/dependency

### ISSUE THREAD

**Issue by rhymes** [epicmaxco/vuestic-admin#66]
Hi, is it possible to use Vuestic as a library or as a dependency of another project? If not, is there a plan for it? 

So we can do something like:

```js
import { VuesticWizard } from 'vuestic/components'
Vue.use(VuesticWizard)
```

We would like to progressively integrate it but even if it were to start from scratch it would be a bit complicated because we would basically have to fork the project, strip it down and figure out how to integrate only what we need. You can imagine how this is going to get complicated very soon.

Thank you!

**Comment by smartapant** [comment]
Hey!

Right now we don't have such a possibility but! All the components inside veustic components are independent (and even provided as plugin) from all the other project. The only thing that binds them is sass and sass dependencies inside sass folder (our base styles and bootstrap overrides). So you can take the admin, rm all the demo pages and use the components from vuesptic-components folder

**Comment by Xeyos88** [comment]
Hi, I am new in the world VueJs, therefore I would like to understand as I can import the components of Vuestic in another project...
If the components are not importable as dependence, do I have to copy them inside my project simply?
Thanks

**Comment by smartapant** [comment]
hey @Xeyos88 !

The components cannot be copied easily - they rely on our styles (override bootstrap). Also, some of them are wrapping libs. You can check the sources though and replicate the behavior easily :)

**Comment by Xeyos88** [comment]
Thanks, I have tried, but it is difficult to reply the logic in a project with Symfony and Webpack-Encore indeed.
I hope that soon it will be possible to include these components as a dependence

**Comment by mccheesy** [comment]
Any change in this? Interested in using Vuestic Admin in an existing Laravel application.

**Comment by asvae** [comment]
@mccheesy This will be in some shape and form in Vuestic 2.0.

General progress you can check in #370.

We only plan npm package, not composer package (if that matters).

**Comment by asvae** [comment]
You can also check #504. That's the main issue for separation.
