### ISSUE TITLE
Toned down theme

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#662]
* [design](https://app.zeplin.io/project/5bcd9657767a220982a4ab61/screen/5d8f43e1e23ce115b7a791ae)

- [x] Implement toned down theme.
- [x] Add ability to select theme from color dropdown.
- [x] Add ability to reset theme (should reset only color pickers, not theme itself).
- [x] toned down theme should be set on specific url (for example `/corporate-theme`).
- [x] Replace `[THEME_URL]` with theme url and check it works for all languages.
- [x] Theme should have no gradients.

## Notes
* [Original issue with discussion](https://github.com/epicmaxco/vuestic-admin/issues/642#issuecomment-536179862)

![dashboard - alternative theme](https://user-images.githubusercontent.com/22664941/65815828-9768ac00-e1f4-11e9-8f80-cb1475069a4a.png)

**Comment by smartapant** [comment]
Update Log:
* Shadows became smaller and lighter (buttons, cards).
* Main buttons don’t have gradients rather solid colors.
* Updated colors.
* Theme switcher added to the color management tool (top bar). Recover defaults button becomes active if any changes to the themes occur.
* Alternative theme has a different set of default colors with a single accent color.
* Top bar has a shadow.


Updated Colors: 
* primary #6E85E8
* success #8FDB8B
* info #74BBFF
* error #F67170
* warning #FFD55E
* black #34495E
* secondary #8396A5

**Comment by ssemenkoff** [comment]
Looks like some components from vuestic-ui have to be reworked to support toned down theme.

I've made up list of changes:
1. va-card
   - Optionally remove gradients
   - Add ability to place image (icon) on background
2. va-button
   - Optionally remove gradient
3. va-sidebar
   - Optionally unlink active item color and background color

@asvae, please check this out and create issues in vuestic-ui if necessary.

**Comment by Kreezag** [comment]
toned down theme can be set on url with params `?theme=corporate`

**Comment by xx13** [comment]
@Kreezag @asvae 404 page with updated styles applied
![404 - alt theme](https://user-images.githubusercontent.com/22664941/70807526-c2fc3b00-1dce-11ea-858c-e665b5e49c59.png)

**Comment by asvae** [comment]
404 pages handled in #701
