### ISSUE TITLE
IE 11/Edge

### ISSUE THREAD

**Issue by gerrieswart** [epicmaxco/vuestic-admin#663]
Bug Report - Both IE 11 and Edge comes up blank when browsing to https://vuestic.epicmax.co

Only the chat box pops up on both browsers.

**Comment by AngeloAnolin** [comment]
Additional Details for Edge (through the Console)

```
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

chunk-vendors.09ed7d23.js (240,596)
```

**Comment by asvae** [comment]
Thanks. Someone from our side had put incorrect version online >.>.

**Comment by gerrieswart** [comment]
I was wondering if this fix might be included in any releases coming up

**Comment by gerrieswart** [comment]
Thanks you all very much for updating this
