### ISSUE TITLE
va-checkbox component doesn't have change event?

### ISSUE THREAD

**Issue by LeeGellie417** [epicmaxco/vuestic-admin#664]
I am using vuestic-admin template and want to get checkbox change event. But no way...
This is my code:
- html
<va-checkbox
:label="`Does Not Apply`"
 v-model="dna"
@change="doesnotapply"
/>               

- Javascript method
doesnotapply() {
      console.log('aaaa');
}    

Javascript function never be called when I check/uncheck my checkbox.

Please let me know if there's any way or it's a bug.
Thanks

**Comment by AngeloAnolin** [comment]
Why not use a watch on the v-model and perform an action when the value changes?

```
watch: {
  dna (newVal, oldVal) {
    if (newVal) {
      // Checkbox was checked.
      // Perform your action here..
    } else {
      // Checkbox was UN-checked.
      // Perform your action here..
    }
  }
}
```

**Comment by LeeGellie417** [comment]
Thanks, but little weird.
Of course, watching v-model is working, but it doesn't have even `change` event?

I have a lot of check boxes in one page with different v-model, so with watching, I need to make a lot of code for handling them all separately...

Any idea for using @change ?

**Comment by asvae** [comment]
You can achieve the same with @input.

We try to keep ins/outs consistent across components. So normally it's :value + @input.
Exposing native event provides some value though.

**Comment by asvae** [comment]
Another thing is that the checkbox we provide behaves differently from vanilla checkbox. I.e. it doesn't have state. So calling event `change` wouldn't make too much sense, because nothing is changed until parent component voices his agreement. I think `input` fits better.
