### ISSUE TITLE
modal form or grid no gutters problem

### ISSUE THREAD

**Issue by codebangla** [epicmaxco/vuestic-admin#669]
* **I'm submitting a ...**
  - [ ] bug report
  

Hello,
I appreciate for the beautiful looking admin template. I was trying to add a form using the modal but when the form is in modal or any grid layout I add inside the modal it does not show the gutters.

Here is the screenshot 

![x2](https://user-images.githubusercontent.com/2529742/66695722-c8fa7080-ece6-11e9-9a2c-333ffbb16421.png)

And here is the code

https://gist.github.com/codebangla/b6b015200547a6b968622c5cba5daae1

**Comment by asvae** [comment]
Could something like `<div class="layout gutter--xl fluid">` help in your case? Modal is positionned in body and body doesn't have any wrappers, so grid gutters default to none.
