### ISSUE TITLE
Not redirecting to login page giving undefined in console

### ISSUE THREAD

**Issue by asifteletech** [epicmaxco/vuestic-admin#67]
here is my main.js code
router.beforeEach((to, from, next) => {
  store.commit('setLoading', true)
  if (to.meta.requiresAuth) {
           const authUser = JSON.parse(window.localStorage.getItem('authUser'))
           if (authUser && authUser.access_token) {
               next()
            } else {
               console.log(next({name: 'Login'}))
               next({name: 'Login'})
             }
       }
})

**Comment by smartapant** [comment]
@asifteletech could you please past here console output?

**Comment by asifteletech** [comment]
As i stated above its showing undefined
undefined
vue.esm.js?efeb:8246 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by jean-moldovan** [comment]
@asifteletech , please provide more context. It's kind of hard to debug your application custom logic remotely 😄
