### ISSUE TITLE
Notifications don't close even with closeable set.

### ISSUE THREAD

**Issue by jbcksfrt** [epicmaxco/vuestic-admin#671]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Bug
* **What is the current behavior?**
Notifications do not close or send an event with closeable.  This does not currently work on the demo either.

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

Go to the notifications demo page and try to close one.

* **What is the expected behavior?**

It should close on clicking the x.

**Comment by asvae** [comment]
Not sure what's the status here.
Expect to be not done.

**Comment by asvae** [comment]
Fixed. Now correctly emits @input `false`.

Fixes will be up for vuestic admin 2.1.
