### ISSUE TITLE
Propose to remove unused files

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-admin#678]
I propose to check and remove unused files like a SetupProfileTab.vue file and demo files.

**Comment by asvae** [comment]
Sure. Do we have an automated way to figure unused files? That would be neat to have somewhere.

**Comment by pjqdyd** [comment]
I hope there is a simple version, components can be added as needed, so that the packaged dist will not be too large

**Comment by asvae** [comment]
Doesn't seem relevant anymore
