### ISSUE TITLE
Vuestic bugs. The Sequel.

### ISSUE THREAD

**Issue by Kreezag** [epicmaxco/vuestic-admin#679]
This task is a continuation of #616 

Add found bugs as comments behind this issue. One comment - one bug. Thanks.

Testing strategy is described in #610.
(Reserved for vasily issues: https://docs.google.com/document/d/1S3-QwgYSouDCc1n24hXM27zAdxsp0KK8-HBAhGxyjOo/edit#)

Check current staging here: http://vuestic-epicmax.asva.by

## ❗ To note

* if you finished working on post - make a notice in header (such as "addressed in `release`"),
* make sure to increment the *№* of your bug submit so that it can be easier to track, group and fix them.
* Please leave a notice if bug reproduces only on safari or something obscure.
* `P5` in header means highest priority (must be done till release). `P1` - means we can ignore. 2-4 - in betweenish. When fixing, select items with higher priority.

## Conventions

:rocket: means that the bug is fixed, checked and approved
:eyes: means that somebody's already working on the bug report and you should pick another one

## TODO
Now there are no correct statuses about problems below

**Comment by Kreezag** [comment]
№ 1 (P4) Visual: Collapse
Collapse with button remains with the pressed style applied (instead of the default one).
Bottom heading margin is missing.
<img width="316" alt="Vuestic Admin 2019-11-20 18-28-01" src="https://user-images.githubusercontent.com/13301570/69252166-a3a13200-0bc3-11ea-8964-b52ba4df44da.png">

**Comment by Kreezag** [comment]
№ 2 (P2) UX: Tooltips for table actions
Tooltips should appear after some delay not instantly.
![image8](https://user-images.githubusercontent.com/13301570/69252428-072b5f80-0bc4-11ea-8b11-05a36e1e73c9.png)

**Comment by Kreezag** [comment]
## № 3
 (P1) Presentation: Tables
I suggest adding a small text style to the table content as well. Maybe have an example with the first column values with the default font style and all other content with the small one applied.
![image5](https://user-images.githubusercontent.com/13301570/69252558-422d9300-0bc4-11ea-8284-13307ca36a5e.png)

**Comment by Kreezag** [comment]
## № 4

 (P?) UX: Input Label - investigate what that means.
Input labels are missing (if they were not displayed by default). I know we should offer inputs like that as well, but the ones with labels at the top are more popular items.
![image7](https://user-images.githubusercontent.com/13301570/69252719-802ab700-0bc4-11ea-811a-b6c718d45f2d.png)

**Comment by Kreezag** [comment]
## № 5 (P1) Visual: Search input
Inputs with icons don’t seem to work. The icon should be inside and the color should be grey.
![image4](https://user-images.githubusercontent.com/13301570/69252775-93d61d80-0bc4-11ea-92c3-1191a6a9d475.png)

**Comment by Kreezag** [comment]
## № 6 (P1) Presentation: Progress bars
Progress Bars don’t look sexy. Better visual presentation suggested.
![image9](https://user-images.githubusercontent.com/13301570/69252917-ce3fba80-0bc4-11ea-8a0c-81e333256e3a.png)

**Comment by Kreezag** [comment]
## 7 UX: Adjust color theme - wontfix (you can do this by reloading the page)
 If we let users adjust main colors, they should have an option to restore the default values.

![image1](https://user-images.githubusercontent.com/13301570/69252992-f0d1d380-0bc4-11ea-8539-f2818e1ebcfc.png)

**Comment by AlexanderBoriskin** [comment]
## № 8 (P?) Presentation: Tabs
Tabs - http://piclair.com/data/urkh7.jpg
It looks strange, maybe tabs width should not be fixed

**Comment by AlexanderBoriskin** [comment]
## № 9 (P?) Colorpickers
Color pickers - http://piclair.com/data/h0jjw.jpg
1) Input styling 
2) `HEX` font

**Comment by AlexanderBoriskin** [comment]
## № 10 (P3) Gradients
Check 43, 44, 88 points in https://docs.google.com/document/d/1S3-QwgYSouDCc1n24hXM27zAdxsp0KK8-HBAhGxyjOo/edit#
