### ISSUE TITLE
Pagination Documentation

### ISSUE THREAD

**Issue by Heavenwalker** [epicmaxco/vuestic-admin#680]
I think a pagination entry is needed  in the documentation. It works really nice and it's shame if someone overlooks it.
Using it right now with markup-tables

Thanks a lot for this wonderful template

**Comment by asvae** [comment]
Thanks for suggestion.

We're going to add docs as a part of `vuestic-ui`. Here's some not feedback ready work: http://vuestic-ui-develop-docs.sub.asva.by/components/VaPagination.html :).

**Comment by haizad** [comment]
Hi, any news on this?  I am looking forward in using pagination entry on this template. 

Thank you :D

**Comment by asvae** [comment]
Here's the new link: https://vuestic.dev/en/ui-elements/pagination.
Things are very close to release. We'll time update vuestic-admin with vuestic-ui.
