### ISSUE TITLE
Add text color alias

### ISSUE THREAD

**Issue by SgtDaJim** [epicmaxco/vuestic-admin#698]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - feature request

Maybe adding some text color class alias like bootstrap? such as, text-danger, text-primary..
It will be much more convenient in development

**Comment by asvae** [comment]
Hey. Thanks for suggestion. I moved to another [issue](https://github.com/epicmaxco/vuestic-ui/issues/148) + added some details.
