### ISSUE TITLE
closeOnAnchorClick of va-select should be modifiable

### ISSUE THREAD

**Issue by SgtDaJim** [epicmaxco/vuestic-admin#699]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - feature request

I read the implement of va-select and find that the va-dropdown used in va-select has an prop 'closeOnAnchorClick', it makes the va-dropdown close after click an option. But in the va-select, it is hard code 'false', and it is not convenient enough. It should become an prop of va-select as well.

**Comment by asvae** [comment]
Thanks.

We need to pass down `closeOnAnchorClick` prop.

**Comment by elpablitos** [comment]
Hi. Is this issue still happening? I can't find any reference to ```closeOnAnchorClick``` in the project.

**Comment by asvae** [comment]
Please reopen if this still a problem
