### ISSUE TITLE
Demo link broken

### ISSUE THREAD

**Issue by Igorpollo** [epicmaxco/vuestic-admin#70]
Link of the demo is broken

http://epicmax.co/vuestic

**Comment by jean-moldovan** [comment]
Hello, @Igorpollo !

`http://epicmax.co/` has been recently updated. Where did you get this link from?

Thanks!

**Comment by Igorpollo** [comment]
This link is in the desctiption, as follow:

![capture](https://user-images.githubusercontent.com/4457845/34381182-1612e746-eaee-11e7-94d3-5507c9229d84.JPG)

But this is broken...
I think the correctly link is this http://vuestic.epicmax.co/

**Comment by smartapant** [comment]
@Igorpollo thx, fixed
