### ISSUE TITLE
Changing scss styles not possible

### ISSUE THREAD

**Issue by davidsmith242** [epicmaxco/vuestic-admin#702]
* **I'm submitting a ...**
  - [X ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

Hi Team! It is not possible to change scss styles in the latest version (2.0.0) of vuestic admin where the styles are placed in the node-modules. Overwriting variables in a project scss file doesn't work. Also including a custom scss in src/sass/main.scss seems to be ignored.

**Comment by asvae** [comment]
Should be fixed in 2.1. Please let us know if it isn't.
