### ISSUE TITLE
Fully hidden sidebar on mobile devices

### ISSUE THREAD

**Issue by SgtDaJim** [epicmaxco/vuestic-admin#704]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [ * ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

On some small screen mobile devices like smartphones, the current minimized sidebar still takes about 1/6 of the visible area. So the sidebar should fully hidden on the mobile devices like those. In vuestic-admin version 1.8.0, the sidebar is doing great.

**Comment by asvae** [comment]
Fair point.

**Comment by asvae** [comment]
Seems done to me
