### ISSUE TITLE
Eslint "quotes" rules unattended error

### ISSUE THREAD

**Issue by etino** [epicmaxco/vuestic-admin#705]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**
On new Vuestic project (created with `vuestic-installer`), Eslint configuration get an unattended error relative to `quote` rule.

Example
`375:21  error  Strings must use single-quote  quotes`

All code uses double quote, so the error is inconsistent.

```
        {
          name: "not-found-large-text",
          path: "/pages/not-found-large-text",
          component: () =>
            import("../components/pages/404-pages/VaPageNotFoundLargeText.vue")
        }
```
* **Other information** 

I solved the issue by installing `eslint-plugin-vue`.
Is it the right way?

**Comment by asvae** [comment]
Yep. We added `eslint-plugin-vue` by default in new version.
