### ISSUE TITLE
404 pages are looking different for different screen sizes

### ISSUE THREAD

**Issue by ilearnjs** [epicmaxco/vuestic-admin#706]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
404 pages are looking different for different screen sizes.
Details [here](https://github.com/epicmaxco/vuestic-admin/pull/701#pullrequestreview-341543962)

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **What is the expected behavior?**
To be discussed

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
Probably fixed already
