### ISSUE TITLE
Readme links to corporate theme

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#709]
* **I'm submitting a ...**
  - [x] bug report

* **What is the current behavior?**

Links to the corporate theme don't work in Readme

* **What is the expected behavior?**

Clicking 'New white theme demo' **link** should be opening a new tab with corporate theme.
Clicking 'New white theme demo' **image** should be opening a new tab with corporate theme.

**Comment by ilearnjs** [comment]
Done
Required to check after deploy to prod
