### ISSUE TITLE
Weird error msg on form wizard validation

### ISSUE THREAD

**Issue by jean-moldovan** [epicmaxco/vuestic-admin#71]
It says `The hsName field is required.` or `The vsName field is required.`

Should be `Name field is required.` or smth. Minor thing.

**Comment by smartapant** [comment]
@jean-moldovan try checking vee-validate's aliasses. Also, just push fix to master, no need for PR here

**Comment by jean-moldovan** [comment]
Fixed by: https://github.com/epicmaxco/vuestic-admin/pull/75
