### ISSUE TITLE
images don't switches in the gallery

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#710]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
report a bug

* **What is the current behavior?**
images are switched only after two clicks on the arrow in the gallery on the dashboard

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

1. open dashboard [link](http://vuestic-admin-staging.sub.asva.by/#/admin/dashboard)
2. click 'explore gallery' button
3. try to switch image
![Screenshot](https://user-images.githubusercontent.com/11391037/73457056-17aa4400-4384-11ea-9c33-76ea0d5a01c6.png)

* **What is the expected behavior?**
images should be switched after every click

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
Can you check if it works now? Works all right for me.
