### ISSUE TITLE
cannot upload an image to media gallery file uploader

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#713]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
bug

* **What is the current behavior?**
error in an attempt to upload an image to gallery file uploader

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
1. open a file upload [page](http://vuestic-admin-staging.sub.asva.by/#/admin/ui/file-upload)
2. try to upload an image to the first uploader from the list
3. console error
`e.filter is not a function at o.validateFiles`

* **What is the expected behavior?**
all types of uploaders should work correctly

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by misterpekert** [comment]
Probably would be closed by epicmaxco/vuestic-ui#268

**Comment by asvae** [comment]
We removed the component for now
