### ISSUE TITLE
Corporate theme's table headers

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#716]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
Data tables page, 'SORTING, PAGINATION, ACTIONS AS ICONS' widget
Active table headers are green

* **What is the expected behavior?**
Should be purple if clickable (remain dark if not).

* **Other information**
<img width="1403" alt="Screen Shot 2020-01-30 at 17 33 33" src="https://user-images.githubusercontent.com/3674348/73459003-33fbb000-4387-11ea-8d96-68cf45dc57dd.png">

**Comment by xx13** [comment]
@smartapant right, all primary things that used to be green in default theme, should be purple in a corporate one.
