### ISSUE TITLE
Arrow in not centered in va-select

### ISSUE THREAD

**Issue by nastassiadanilova** [epicmaxco/vuestic-admin#718]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
arrow is not centered in va-select in the focus state

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
try to switch focus between selects via tab key button
![Screenshot](https://user-images.githubusercontent.com/11391037/73459231-8c32b200-4387-11ea-9eb9-6551aeba78a6.png)

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by giteshk11** [comment]
Hi @asvae, I would like to work on this issue.

**Comment by asvae** [comment]
Fixed long ago )
