### ISSUE TITLE
Corporate theme's links on login page

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#720]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
The links are green, but they should be primary purple.

<img width="837" alt="Screen Shot 2020-01-30 at 17 48 10" src="https://user-images.githubusercontent.com/3674348/73460155-0ca5e280-4389-11ea-9a94-c1e18eb457e5.png">

**Comment by xx13** [comment]
@smartapant right, all primary things that used to be green in default theme, should be purple in a corporate one.
