### ISSUE TITLE
Corporate theme's glitches

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#722]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
Using http://vuestic-admin-staging.sub.asva.by/#/admin/dashboard?theme=corporate link, makes a glitch with 'original' theme's styles 

* **What is the expected behavior?**

Using a loading screen could be a solution

**Comment by ilearnjs** [comment]
Works correctly for dashboard links
