### ISSUE TITLE
Top Contributors widget issues & improvements (all themes)

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-admin#725]
* **I'm submitting a ...**
  - [ ] bug report

* **What is the current behavior?**
There a vertical line and a grey block on the right that shouldn't be there (both themes).
![Screen Shot 2020-01-31 at 12 48 53](https://user-images.githubusercontent.com/22664941/73533492-06b70c80-4430-11ea-898f-d1b4d33f1c55.png)

Duplicating colors is not that informative as if we showed different colors for progress bars.

'Show next five' button label is not optimal it takes too much space.

* **What is the expected behavior?**
The vertical line and grey area should be removed.

Let's show different colours on the first screen without duplicated versions.

Changing button label to something shorter like 'Next', 'Next 5'. It will make the widget more visually appealing. The minimal required change is to have 'Show next 5' as a button label.

**Comment by Dooxe59** [comment]
Hello, 

I fix the bug with the vertical line on the right and I also changed the label 'Show next 5' label to 'Next'.

What is the procedure to follow in order to send a PR?

Thanks in advance :)

**Comment by asvae** [comment]
Removed from new version
