### ISSUE TITLE
Missing date picker example

### ISSUE THREAD

**Issue by gravity00** [epicmaxco/vuestic-admin#73]
I was trying to find an example or documentation for datepicker inputs, but can't find none in the online demo or documentations. Is there any place I can see, at least, an usage example?

Aside, great project, congratulations.

**Comment by smartapant** [comment]
@gravity00 thanks! and thanks for pointing out the date picker - we haven't built it, will be one of our priorities after finishing ongoing tasks

**Comment by gravity00** [comment]
@jean-moldovan thanks for the info!
 I'm currently analyzing some vue templates, and I'll try to put some datepicker working on this one (I'm not a frontend guy, so it may be a challenge for me) and if I find something interesting that can be easily added and aligned with your styles, I'll let you guys know.

**Comment by smartapant** [comment]
@gravity00 no worries, we are designing a custom one at the moment :)

**Comment by smartapant** [comment]
@gravity00 component is already designed, will be implementing soon :)

**Comment by smartapant** [comment]
The design and the issue will live here :) #117
