### ISSUE TITLE
Make wihte corporate team default

### ISSUE THREAD

**Issue by smartapant** [epicmaxco/vuestic-admin#738]
* **I'm submitting a ...**
  - [ ] feature request

* **What is the motivation / use case for changing the behavior?**
Reddit [feedback](https://www.reddit.com/r/javascript/comments/eypuq0/askjs_please_help_us_choose_the_default_color/) showed us that white theme is a better default decision for most people. So it must be a default for 2.1.1 version

All the links in readme also musy be changed according to new default color scheme

**Comment by jugalj05hi** [comment]
Hello there, can I take up this issue?

**Comment by asvae** [comment]
That's done.
