### ISSUE TITLE
Misaligned dot in Radio component

### ISSUE THREAD

**Issue by followyouhome** [epicmaxco/vuestic-admin#739]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

Minor bug

* **What is the current behavior?**

![Screenshot](https://image.prntscr.com/image/MTWafOQORsqFUe6jPRwOwg.png)

On MacBook Pro 13-inch default font scaling dot inside of radio button is not centered

* **If the current behaviour is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

Go to https://vuestic.epicmax.co/admin/forms/form-elements and check radio button.
In Chrome looks better than in Safari, but misaligned too.

* **What is the expected behavior?**

Dot in radio button should be centred.

**Comment by roiLeo** [comment]
I think it's more a vuestic-ui issue.
The radio component has a weird margin-left.

**Comment by saucekode** [comment]
Good day, can I be assigned this issue to fix?

**Comment by asvae** [comment]
@saucekode would recommend against that, sorry.

Development mostly moved to https://github.com/epicmaxco/vuestic-ui
You can see current implementation here: http://vuestic-ui-develop-docs.sub.asva.by/en/option-list/#examples
