### ISSUE TITLE
error in console hex2rgb is null on certain colors on hover of a va-button

### ISSUE THREAD

**Issue by grippon** [epicmaxco/vuestic-admin#740]
Is there a way to set a jsfiddle using vuestic?

I have this code in template

    <va-button flat color="green" icon="fa fa-eye" />
    <va-button flat color="orange" icon="fa fa-eye" />

When I hover the green button, I get an error in the Firefox console : 

      [Vue warn]: Error in render: "TypeError: hex2rgb(...) is null"

Nothing happens when I hover the orange button.

I am using TopBar, the problem maybe comes from, in `TopbarLink.vue`:

    import { getHoverColor } from './../../../../services/color-functions'

which doesn't import hex2rgb from the same file?

If I change the color `green` with `#080` the button's color is almost the same, the console error doesn't appear anymore but a green background appears on hover.

**Comment by asvae** [comment]
Hi.
Vuestic admin version, vuestic-ui version and fiddle itself will be appreciated. Currently not enough data.

**Comment by grippon** [comment]
$ npm list | grep vuestic
    ├─┬ vuestic-ui@0.1.8

Can you show me a fiddle example using vuestic?

**Comment by asvae** [comment]
Still not sure how do I reproduce the problem.

Fiddle-wise, I do not expect vuestic to work all too well, as components are transpiled on build, which means importing from cdn won't be an option. Codesanbox might work though.
