### ISSUE TITLE
Changing the default theme 

### ISSUE THREAD

**Issue by abdussamadbello** [epicmaxco/vuestic-admin#741]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
 
* **Do you want to request a *feature* or report a *bug*?**
A bug and question
* **What is the current behavior?**
I'm trying to override the theme's defaults color but it doesnt work.

`Vue.use(ColorThemePlugin, {
  // override colors here.
  themes: {
    primary: '#6c7fee',
    secondary: '#6e7ff1',
    success: '#8ddc88',
    info: '#71baff',
    danger: '#f8706d',
    warning: '#ffd652',
    gray: '#8396a5',
    dark: '#34495e',
  },
}`

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Change the colours in the ColorThemePlugin.

* **What is the expected behavior?**
Change the themes default color

Or 

Please how can I change my default theme color?

**Comment by asvae** [comment]
What's your version of vuestic UI? I tested on 2.2 and it seems to work without issues.

![image](https://user-images.githubusercontent.com/5394573/75880222-f084dd80-5e2d-11ea-9965-3b555ff440ea.png)

**Comment by abdussamadbello** [comment]
Yes I am using V 2.2. I'm talking about changing the colors of the headers of the sidebar.
