### ISSUE TITLE
Site is down from server

### ISSUE THREAD

**Issue by Pranjalya** [epicmaxco/vuestic-admin#748]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ Y ] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
A bug.

* **What is the current behavior?**
ping: https://vuestic.epicmax.co/: Name or service not known

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
`ping https://vuestic.epicmax.co`

* **What is the expected behavior?**
It should return True value with TTL details.

* **What is the motivation / use case for changing the behavior?**
No way of checking out the demos of various components.

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
Thanks. Fixed.
