### ISSUE TITLE
Errors on Upgrade

### ISSUE THREAD

**Issue by joel-44** [epicmaxco/vuestic-admin#750]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
When upgrading vuestic-ui things are broken with errors like the following:

`TypeError: Cannot read property 'gradient' of undefined`
`TypeError: Cannot read property 'shadow' of undefined`

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
Upgrade vuestic-ui from 0.1.8 to 0.2.2

* **What is the expected behavior?**
We can upgrade without issues

* **What is the motivation / use case for changing the behavior?**
Getting the latests changes on the template

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
I would like to know if there is any better way to upgrade, as I might be missing the changes on the admin template itself, since the suggestion installation method is doing a git clone and working on the repository I am not sure how it should be updated so I tried to update vuestic-ui instead.

**Comment by asvae** [comment]
Hi. Sorry for late answer.

Updating is a weak point of vuestic and something we're to improve in later versions (it was designed as full app, not modular at all).
So some areas of code might be too tightly bound together, which also makes update guidline complicated to do.

But I can guesstimate what went wrong if you can provide a more detailed stack trace and more error examples hopefully.
Alternative would be to check current master of vuestic-admin with your version and tweak inconsistencies. vuestic-admin latest version is guaranteed to work with vuestic-ui 0.2.2.
