### ISSUE TITLE
Bug va-file-upload still coming out

### ISSUE THREAD

**Issue by haej3131** [epicmaxco/vuestic-admin#754]
[https://github.com/epicmaxco/vuestic-admin/issues/749]
After uploading same error comes out.
```
<va-file-upload
          dropzone
          v-model="advancedList"
          file-types  =".xls,.xlsx"
        />
```
Here is the console output:
**vue.esm.js:628 [Vue warn]: Error in v-on handler: "TypeError: files.filter is not a function"**
![스크린샷 2020-06-24 오전 11 00 56](https://user-images.githubusercontent.com/17423207/85489678-4f53aa00-b60b-11ea-917a-118c9f0442cb.png)

**Comment by asvae** [comment]
Please reopen if it persists.
