### ISSUE TITLE
Modal  onOk

### ISSUE THREAD

**Issue by jiangxinlong** [epicmaxco/vuestic-admin#758]
how to use  

<va-modal
      v-model="showDeleteModal"
      title=" 确定 "
      cancelClass="none"
      message="删除之后无法恢复，确定删除？"
      noOutsideDismiss
      noEscDismiss
      noCancel
      onOk="deleteOrder"
      class="delModal"
    ></va-modal>

methods: {
    deleteOrder () {
      console.log(111111111)
    },
  },

it is not ok!

**Comment by jiangxinlong** [comment]
<va-modal
      v-model="showDeleteModal"
      title=" 确定 "
      cancelClass="none"
      message="删除之后无法恢复，确定删除？"
      noOutsideDismiss
      noEscDismiss
      noCancel
      onOk="deleteOrder"
      class="delModal"
    ></va-modal>

**Comment by jiangxinlong** [comment]
v-model="showDeleteModal"
      title=" 确定 "
      cancelClass="none"
      message="删除之后无法恢复，确定删除？"
      noOutsideDismiss
      noEscDismiss
      noCancel
      onOk="deleteOrder"
      class="delModal"

**Comment by asvae** [comment]
You can check [demo](https://github.com/epicmaxco/vuestic-ui/blob/develop/packages/ui/src/components/vuestic-components/va-modal/VaModal.demo.vue#L175).

Hope that helps.

**Comment by asvae** [comment]
Pretty sure we have this already
