### ISSUE TITLE
Add custom colors and sass helpers classes

### ISSUE THREAD

**Issue by FerRubioMorales** [epicmaxco/vuestic-admin#761]
Hi,

I'm using **Vuestic Admin** for my project and i need to add new custom colors and generate helpers class. ¿What is the best way to do it? I need also branded colors and classes like 

    text--{brandName}--success
    text--{brandName}--lighten--success
    text--{brandName}--error

...

Please, can you help me with this? I can not understand how colors, palettes and components colors works.

**Comment by asvae** [comment]
We moved to tailwind, which solves this issue
