### ISSUE TITLE
Malformed Example on Wiki

### ISSUE THREAD

**Issue by bisguzar** [epicmaxco/vuestic-admin#762]
* **I'm submitting a ...**
  - [ ] bug report
  - [x] typo report
  - [ ] feature request
  - [ ] support request

In the "grid" section of wiki I found a typo/issue. In the first example we have a malformed div tag.
Source: https://github.com/epicmaxco/vuestic-admin/wiki/Grid

```
<div class="va-layout gutter--md">
   <div class="va-row">
     <div class="flex">
       Grid sizes
     </div>
   </div>
   <div class="va-row row wrap">
     <div class="flex xs12">
       <div class="_blue-rectangle">
            12
       </div>
     </div>
   </div        <-------------------- HERE IS THE MALFORMED TAG
</div>

```

**Comment by untael** [comment]
Thanks.
