### ISSUE TITLE
[BUG report]  when i use multiSearchableSelect to search options,it goes wrong

### ISSUE THREAD

**Issue by rofleed** [epicmaxco/vuestic-admin#769]
I used multiSearchableSelect  in my page，but when i search and click the options(nearly 400 options）,the options goes wrong,seems to "mad searching", i can't control it ,.how can i fix  it?

**Comment by rofleed** [comment]
![image](https://user-images.githubusercontent.com/19771914/92368313-23d05e00-f12a-11ea-946d-6d0a7f73377b.png)

the console tells these

**Comment by asvae** [comment]
Please reopen if this still doesn't work. Pretty sure this should be fixed in ui.
