### ISSUE TITLE
Is this project actively maintained?

### ISSUE THREAD

**Issue by ttodua** [epicmaxco/vuestic-admin#773]
Last commit happened 3 month ago.
We are interested, if this project is actively maintained and will be in the foreseeable future?
Or the company had lost the active maintaining plans for this?

**Comment by asvae** [comment]
Hey.

TL;DR: yes it is.

Now for details:
Our main focus at the moment is on [vuestic-ui](https://github.com/epicmaxco/vuestic-ui). You can check current progress [here](http://vuestic-ui-develop-docs.sub.asva.by/) and [here](http://vuestic-ui-demo.sub.asva.by/#/demo/vuestic-components/va-slider/VaSlider.demo.vue).

Problem with vuestic-admin was that it was tightly bound to components. So right now we're working on UI components/services in separation, and, after we're happy with results - we'll update vuestic-admin with new stuff.

Hope that helps.
