### ISSUE TITLE
一堆bug，建议不要用，还没人更新

### ISSUE THREAD

**Issue by rofleed** [epicmaxco/vuestic-admin#776]
文件上传、选择框啥的，一用就是一个bug，别用它，太坑了

**Comment by helloranger** [comment]
> 文件上传、选择框啥的，一用就是一个bug，别用它，太坑了

感谢提醒

**Comment by JFiscome** [comment]
哈哈哈，本来想clone下来的。

**Comment by cnlydia** [comment]
感觉界面是最好看的，还想用用呢

**Comment by magixyu** [comment]
Please specify the bugs. Please show your respect as well. @rofleed

**Comment by asvae** [comment]
Thanks, but not too specific :).
