### ISSUE TITLE
Google maps integration

### ISSUE THREAD

**Issue by peterennis** [epicmaxco/vuestic-admin#779]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**

error message

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![2020-12-06 20_08_39-](https://user-images.githubusercontent.com/140737/101308609-1dbc4d00-37ff-11eb-9139-ff0310039e7b.png)

**Comment by asvae** [comment]
Thanks! We'll take a look.

**Comment by damirJa** [comment]
Hi @asvae! I guess this is the problem
<img width="647" alt="Screen Shot 2020-12-14 at 4 32 13 PM" src="https://user-images.githubusercontent.com/10356386/102076713-f6323980-3e29-11eb-8dab-af1e8baf9309.png">

**Comment by sarathak** [comment]
i think this is not a bug
just because of don't have paid google map api key

**Comment by Derranion** [comment]
Update:

Currently it does not open completely and throws these errors:

![vuesticAdmingoogleMapsAndYandexMapsAreNotWorking](https://user-images.githubusercontent.com/7745899/147299360-75cf82eb-e90d-4d53-9139-247c20472caa.png)

**Comment by saschnet** [comment]
Currently, the load functionality fails completely:
![grafik](https://user-images.githubusercontent.com/33368683/162588871-d21d5bf4-ad56-41df-86fd-a1c0658b7e24.png)

**Comment by saschnet** [comment]
I fixed the current bug which resides in `/src/pages/admin/maps/google-maps/GoogleMap.vue` by installing the official google maps loader https://www.npmjs.com/package/@googlemaps/js-api-loader with
```bash
npm i @googlemaps/js-api-loader
```
and modified the `<script>[...]</script>` content to:
```js
import { Loader } from '@googlemaps/js-api-loader';

export default {
  name: 'google-map',

  mounted () {
    if (!process.env.VUE_APP_GOOGLE_MAPS_API_KEY) {
      throw new Error('Please provide google maps api key from env (VUE_APP_GOOGLE_MAPS_API_KEY)')
    }

    const loader = new Loader({
      apiKey: process.env.VUE_APP_GOOGLE_MAPS_API_KEY,
      version: "weekly",
      libraries: ["places"]
    });

    const mapOptions = {
      center: {
        lat: 0,
        lng: 0
      },
      zoom: 6,
    };

    loader
      .load()
      .then((google) => {
        new google.maps.Map(this.$el, mapOptions);
      })
      .catch(e => {
        console.log(e)
        // do something
      });
  },
}
```

**Comment by asvae** [comment]
We removed google map from new version.
