### ISSUE TITLE
Form Wizzard Rich 

### ISSUE THREAD

**Issue by simonackermann** [epicmaxco/vuestic-admin#78]
# rich form wizzard
The tick does not aprear when changing steps 

<img width="1611" alt="capture d ecran 2018-01-05 a 18 18 09" src="https://user-images.githubusercontent.com/10863442/34620261-268b6784-f245-11e7-824d-73f6fdc939cc.png">

This is just after initializing the project with vuestic CLI

**Comment by jean-moldovan** [comment]
Thanks for reporting this @simonackermann !

Has been fixed with https://github.com/epicmaxco/vuestic-admin/pull/79
