### ISSUE TITLE
Date picker not showing time fields

### ISSUE THREAD

**Issue by denisvitez** [epicmaxco/vuestic-admin#782]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Date picker ignores the enableTime parameter for flatpickr and time input is not shown. But if we select the date from calendar it will set time as 12:00, but this time can't be changed.

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

We add a date picker to our component, as from example code:
`<va-date-picker
            :label="$t('pages.history.dateTo')"
            :config="{enableTime: true}"
            v-model="dateTo"
          />`

We open the date picker, but time can't be set (the element is not present in the DOM).
![image](https://user-images.githubusercontent.com/9318695/106789309-64d58b80-6652-11eb-8ec5-540f3298571f.png)

If we decide to hide the calendar, time will be shown:

`<va-date-picker
            :label="$t('pages.history.dateFrom')"
            :config="{enableTime: true, noCalendar: true}"
            v-model="dateFrom"
          />`

![image](https://user-images.githubusercontent.com/9318695/106789837-0ceb5480-6653-11eb-924e-17365ca37a33.png)

* **What is the expected behavior?**

Time input should be present below calendar when date picker is opened. Time could be changed.

**Comment by asvae** [comment]
Fixed
