### ISSUE TITLE
python2 is a requirement to run "npm install" on Windows (10)

### ISSUE THREAD

**Issue by Felix-Puetz** [epicmaxco/vuestic-admin#784]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
Running `npm install` on Windows 10 without python 2 installed will **fail**

* **What is the expected behavior?**
Either add it as a requirement or remove it as a requirement

**Comment by asvae** [comment]
This seems like [node-gyp](https://github.com/nodejs/node-gyp) issue to me.
Its installation differs vastly for different platform, and imo is easier to google this issue compared to documenting somewhere in readme or wiki.
