### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-admin#797]
Please have a look at 2 themes we can offer as quick solutions when `topbar` and `sidebar` will be styled based on `primary` and `secondary` color values (`secondary` for dark themes is pre-defined as a lighter version of the light theme value, but can be overwritten). These 2 choices would have pre-designed styles for `topbar` and `sidebar` . Everything can be customised to the fullest (cyan bg in `custom` theme column for custom values that don't follow `light` or `dark/semi-dark` theme patterns).

For dark themes we can start with `semi-dark` theme that won't turn on a dark mode for widgets and UI elements, only `navbar` and `sidebar`, and follow up with a `dark theme` as an improvement after the initial release.

[Design in Figma](https://www.figma.com/file/2yH0KFiWds3q1B5NA5dELZ/vuestic-ui?node-id=216%3A544)

**Comment by asvae** [comment]
Done.
