### ISSUE TITLE
File upload Z-index issue

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#798]
![image](https://user-images.githubusercontent.com/5394573/118472300-5860d480-b711-11eb-9df2-0afe877ae77b.png)

Probably same issue with icons

![image](https://user-images.githubusercontent.com/5394573/118472891-0a989c00-b712-11eb-8316-9fb28dab2c0b.png)

**Comment by Derranion** [comment]
Issue was caused by our layout z-index nesting.
Icons \ buttons parent - "app-layout__page" [now has z-index](https://github.com/epicmaxco/vuestic-admin/commit/42c5184dd8a90377ad4c50489afb4fb84a46e01b) so the issue is resolved.
