### ISSUE TITLE
Upgrade ionicons to latest stable version 3.0.0

### ISSUE THREAD

**Issue by palashmon** [epicmaxco/vuestic-admin#8]
There is a newer version of [`ionicons`](https://www.npmjs.com/package/ionicons) released that this project depends on.

**Required:** ^2.0.1
**Stable:** 3.0.0

Please update to latest and test it out.
Regards!

**Comment by xRahul** [comment]
Their website http://ionicons.com/ is still showing 2.0.1
Plus just tried upgrading to 3.0.0 and there were some issues that need to be addressed.

**Comment by jean-moldovan** [comment]
Updated with https://github.com/epicmaxco/vuestic-admin/pull/37
