### ISSUE TITLE
Cards

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-admin#801]
- If a card has rounded corners at the bottom, it should have rounded corners at the top, even if it has an image or a stripe (top border).
- Let's make `Explore gallery` centered. If it's aligned to left or right, it should be a filled button or a link, so that paddings looks right.
- A title that appears over the image should be `display 5` not `title`.
- 
<img width="375" alt="card-no-rounded-corners" src="https://user-images.githubusercontent.com/22664941/118490205-fce91380-b71d-11eb-8d96-7febbc698ea1.png">

<img width="381" alt="card-title-over-image" src="https://user-images.githubusercontent.com/22664941/118490231-01153100-b71e-11eb-9844-b38c99f29bbe.png">

<img width="379" alt="card-w-action" src="https://user-images.githubusercontent.com/22664941/118490233-01153100-b71e-11eb-916f-8d44bd9e17b2.png">

<img width="382" alt="card-w-stripe" src="https://user-images.githubusercontent.com/22664941/118490236-02465e00-b71e-11eb-953a-a84654b818ae.png">

**Comment by Swatijl** [comment]
@xx13 Fixed this bug via PR 
https://github.com/epicmaxco/vuestic-admin/pull/856

**Comment by Swatijl** [comment]
#856
