### ISSUE TITLE
Language select

### ISSUE THREAD

**Issue by xx13** [epicmaxco/vuestic-admin#804]
- [ ] Remove flags
- [ ] The default value should say `English`, `EN`, or `en` (shorter names might be better for mobile version if we don't change the layout) - we can also use [an icon](https://fonts.google.com/icons?icon.query=language)
- [x] Update dropdown style to white bg and default shadow style (light and blue'n'green theme).
- [ ] Update dropdown style to dark bg for semi-dark theme.

<img width="215" alt="lang-select" src="https://user-images.githubusercontent.com/22664941/118491623-78979000-b71f-11eb-8bf2-3486ec4aa248.png">

**Comment by asvae** [comment]
@m0ksem still relevant?

**Comment by m0ksem** [comment]
> @m0ksem still relevant?

Yap. We haven't removed flags yet. But I don't think that it's important.

**Comment by asvae** [comment]
There is no language select for now.
