### ISSUE TITLE
Make graphs transparent 

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-admin#821]
![image](https://user-images.githubusercontent.com/23530004/127139385-8d45df33-1dd1-4be8-a962-bc7d39909f60.png)

**Comment by imjwang** [comment]
Hi @m0ksem, can you assign me this issue. I'd like to work on it

**Comment by m0ksem** [comment]
@imjwang, please have a look at vuestic-ui `setHSLAColor` method. This can be helpful for this issue.

https://github.com/epicmaxco/vuestic-ui/blob/073e74f17c8f350c4c46443659b140711bd6e667/packages/ui/src/services/color-config/color-config.ts#L61

**Comment by imjwang** [comment]
I'm having trouble getting project set up with `npm run serve`
Any ideas?

```bash
 ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": [
    null
     ],
  "use": [
      {
      "loader": "C:\\Users\\jeffr\\Documents\\repos\\vuestic-admin\\node_modules\\cache-loader\\dist\\cjs.js",
      "options": {
        "cacheDirectory": "C:\\Users\\jeffr\\Documents\\repos\\vuestic-admin\\node_modules\\.cache\\babel-loader",
        "cacheIdentifier": "870faf2e"
      },
      "ident": "clonedRuleSet-38.use[0]"
     },
      {
      "loader": "C:\\Users\\jeffr\\Documents\\repos\\vuestic-admin\\node_modules\\babel-loader\\lib\\index.js",
      "options": "undefined",
      "ident": "undefined"
      }
      ]
      }
```

**Comment by imjwang** [comment]
nvm, it's working with yarn

**Comment by m0ksem** [comment]
Npm install works fine for me on `6.14.10`.

**Comment by m0ksem** [comment]
Found that this issue was caused because the 4.47.0 webpack version. Rollback to 4.46.0 should fix npm.

**Comment by imjwang** [comment]
![Screenshot 2021-09-08 181335](https://user-images.githubusercontent.com/64715088/132592812-555256c4-817a-4953-8ad5-d6dc5cad8f24.png)
@m0ksem Seems like they are already transparent?

**Comment by asvae** [comment]
We're replacing charts in new version.
