### ISSUE TITLE
GUI abnormal when update vuestic to 1.2.2

### ISSUE THREAD

**Issue by magixyu** [epicmaxco/vuestic-admin#822]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
  report a bug

* **What is the current behavior?**
  GUI show abnormal, especially the side bar.

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
  yarn remove vuestic
 yarn add vuestic@1.2.2
  yarn run serve

* **What is the expected behavior?**
  GUI works well.

* **What is the motivation / use case for changing the behavior?**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
Likely fixed in recent versions of vuestic-ui. If not - please reopen.
Thanks.
