### ISSUE TITLE
npm install on macOS error

### ISSUE THREAD

**Issue by huasonli** [epicmaxco/vuestic-admin#841]
When I run  npm install on MacOS, I got the error as below:
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: vuestic-admin@3.0.0
npm ERR! Found: vue@3.2.11
npm ERR! node_modules/vue
npm ERR!   vue@"^3.2.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.5.2" from epic-spinners@1.1.0
npm ERR! node_modules/epic-spinners
npm ERR!   epic-spinners@"^1.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!

**Comment by Sharifur** [comment]
facing same error !!

**Comment by suvarivaza** [comment]
facing same error !!
what to do???

**Comment by Swatijl** [comment]
@huasonli It got installed in my mac m1.I would suggest to check your npm & node versions.
npm - 8.3.1
node - v16.14.0
vue - @vue/cli 5.0.1

**Comment by mateozupanjac** [comment]
one workaround is to add '--legacy-peer-deps', so like this -> `npm install --legacy-peer-deps`

**Comment by asvae** [comment]
Probably fine right now.
