### ISSUE TITLE
Button text is off

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#843]
![Screenshot_20211111-081102](https://user-images.githubusercontent.com/5394573/141241217-ee00d970-a6b7-4574-9556-943e22ec6814.jpg)

And that's a first page...

**Comment by Gabriel-scodiero** [comment]
Could reproduce it on the website from my cellphone, but didn't reproduce the error when using my local project.

**Comment by asvae** [comment]
That's fixed
