### ISSUE TITLE
Moving to Vite

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#848]
Thinking if we can move to Vite (currently we use vue-cli).
[Vite is very popular](https://github.com/vitejs/vite) and well supported. So, more-less standard solution for vue.

Probably makes sense to do after vite plugin for vue-cli is done: https://github.com/epicmaxco/vuestic-ui/issues/1317

**Comment by laoshaw** [comment]
Yes please,  the reason I am using primevue now is due to its vite readiness.

**Comment by bitsnaps** [comment]
The first steps are [easy](https://wildermuth.com/2021/01/10/Vite-for-Existing-Vue-CLI-Projects/), you just need to `npm` install `@vitejs/plugin-vue` plugin, then move your `public/index.html` to the root directory and remove unnecessary parts , and finally configure `vite.config.js` file (this last one need some work...).

**Comment by bitsnaps** [comment]
> Probably the easiest way to transition to vite - is to create a new project, then move existing pages there.

That's what I did, but I think it's better to move to something new for [now](https://www.naiveui.com/), since nuxt v3 is almost ready...
