### ISSUE TITLE
any tutorial for beginners?

### ISSUE THREAD

**Issue by gileneusz** [epicmaxco/vuestic-admin#85]
Hi, I spend all day trying to set up a form element into my vue app. Unfortunately your theme is so complicated that I was unable to use it and set it up. I think that if you really want to share your work and do it for other users, try to make it user frendly for beginners.

**Comment by Bear4** [comment]
I would say the same ;)
It's hard to walk through app for beginners.

**Comment by jean-moldovan** [comment]
Hello @gileneusz and thanks for contacting us!

We are constantly working on improving our documentation (Please see https://github.com/epicmaxco/vuestic-admin/wiki).

Would be happy to understand your use case and what did cause you trouble. This will help us to figure out the best approach regarding docs/tutorials.

Thanks!

**Comment by smartapant** [comment]
@gileneusz @Bear4 Also, we've got lots of the components usage right inside the template

Got stuck with forms? Check 'Form Elements' page - that works better than docs :)
