### ISSUE TITLE
Dashboard button error

### ISSUE THREAD

**Issue by Derranion** [epicmaxco/vuestic-admin#850]
* **I'm submitting a ...**
  - [X] bug report
  - [ ] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**
`Show in more detail` button on the `admin dashboard` page does not work and throws console error.

![vuesticAdminShowInMoreDetailsIsNotWorking](https://user-images.githubusercontent.com/7745899/147299172-1591572d-ab0b-4aa1-aced-927c2c0b8365.jpg)

**Comment by Swatijl** [comment]
@Derranion I did RCA & found that issue is occuring because of line 44 in `LineChartData.ts`
`dataset.data.shift()`

Hope this would be helpful.
