### ISSUE TITLE
Closing alert not working

### ISSUE THREAD

**Issue by m0ksem** [epicmaxco/vuestic-admin#861]
https://vuestic.epicmax.co/admin/ui/notifications

Alert can't be closed because it has not modelValue.

Need to make similar demo like in docs https://vuestic.dev/en/ui-elements/alert#closeable

See this discussion: https://github.com/epicmaxco/vuestic-ui/discussions/1626

**Comment by brunorabelo** [comment]
Can I take this?

**Comment by m0ksem** [comment]
> Can I take this?

Hey! We're currently moving to Vite and making a massive Vuestic Admin update. To prevent conflicts, I would recommend ignoring this issues for a while. Also, @RVitaly1978 likely closing it in https://github.com/epicmaxco/vuestic-admin/pull/876.

If you're just motivated to contribute, we have a lot of small issues in [Vuestic UI](https://github.com/epicmaxco/vuestic-ui/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

**Comment by asvae** [comment]
Should be fixed in vuestic-ui
