### ISSUE TITLE
Scroll to top on route change

### ISSUE THREAD

**Issue by MerlinEmris** [epicmaxco/vuestic-admin#863]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
feature

* **What is the current behavior?**
on route change does not scroll to top

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

* **What is the expected behavior?**
on route change scroll to top

* **What is the motivation / use case for changing the behavior?**
easy of navigation

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
That's implemented
