### ISSUE TITLE
Checkbox and switch broken when build with Vuestic-UI (1.3.5)

### ISSUE THREAD

**Issue by WintonLi** [epicmaxco/vuestic-admin#867]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report  ------> maybe
  - [x] feature request  ----> not sure
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
Not sure

* **What is the current behavior?**
After upgrading Vuestic-UI from 1.2.8 to 1.3.5, both checkbox and switch work normally in develop environment (e.g. `npm run serve`) but render nothing after build (the corresponding templates are left blank). No error is reported during build. No error message is displayed in browser console.

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
OS: Windows 10 Professional
npm version: 8.5.0
node version: 16.14.2

1. Clone the repo and install dependencies
2. Change the version of vuestic-ui to 1.3.5, which is the latest version
3. Run `npm install` to perform upgrade
4. Run `npm run serve` to launch develop server. All UI elements display normally
5. Run `npm run build`, and the repo is built successfully without error
6. Run `serve -s dist`. Navigate to http://localhost:3000/admin/forms/form-elements, and it can be seen that the checkboxes and switches are all gone. All other UI elements seem to work normally
![image](https://user-images.githubusercontent.com/19507650/167940299-1f39febd-7a25-4606-ab6a-2c93a44f34ed.png)

* **What is the expected behavior?**
The display of checkboxes and switches were expected behave consistently in develop and production environment. If they work in develop mode, they are supposed to work in production mode as well. 

* **What is the motivation / use case for changing the behavior?**
We want to use the datatable component that comes with the latest version of Vuestic UI

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by asvae** [comment]
That's probably fixed long ago.
