### ISSUE TITLE
Check mobile on nuxtjs

### ISSUE THREAD

**Issue by jerateep** [epicmaxco/vuestic-admin#868]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [x] feature request
  - [ ] support request => Please do not submit support request here, see note at the top of this template.

* I use templates in nuxt.js
Error: window is not defined in Nuxt.js
Is there a way to check mobile mode in nuxt.js
![image](https://user-images.githubusercontent.com/18267454/169762444-e078ed40-333a-4158-aa52-4d5441eb6bbe.png)

**Comment by asvae** [comment]
Probably fixed in vuestic ui, please reopen if it's not.
