### ISSUE TITLE
How to use va-data-table?

### ISSUE THREAD

**Issue by Jamsa** [epicmaxco/vuestic-admin#871]
The data table is disabled by default.
When use it will got an error:
```Failed to resolve component: va-data-table```

How can I use the data table?

**Comment by Jamsa** [comment]
After upgrade the vuestic-ui to 1.4.0, the va-data-table is working, but there are some other issues, some methods not found...

**Comment by vrandeshbandikatti** [comment]
This is a disappointment as it lead to waste of a lot of time trying to debug if my code was wrong. Not sure if the vuestic-ui team considered this as a negative impact on their components. Most of the production sites would then be rendered false with this issue.

**Comment by vrandeshbandikatti** [comment]
I have faced the issue and posted a Stackoverflow : https://stackoverflow.com/questions/72553714/vue3-data-tables-via-vuestic-ui

**Comment by asvae** [comment]
[This](https://ui.vuestic.dev/ui-elements/data-table) might help

please reopen if it doesn't 🫠
