### ISSUE TITLE
Issue with Navigation Routes passing a dynamic value when added programmatically

### ISSUE THREAD

**Issue by vrandeshbandikatti** [epicmaxco/vuestic-admin#873]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request

* **Do you want to request a *feature* or report a *bug*?**
* Report a bug

* **What is the current behavior?**
Does not support dynamic sidebar, NavigationRoutes.js is a not defined clearly as to how to pass a dynamic sidebar item whose values are dynamic in nature.

* **What is the expected behavior?**
Should list the dynamic navigation items with their dynamic prop id passed to the item in route.

* **What is the motivation / use case for changing the behavior?**
Trying to add the Dynamic Sidebar items with props 

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**

I have the following router/index.ts as follows
` {
        name: 'statistics',
        path: 'statistics',
        component: RouteViewComponent,
        children: [
          {
            name: 'charts',
            path: 'charts/:type?',
            component: () => import('@/pages/admin/statistics/charts/Charts.vue'),
            meta: {
              wikiLink: 'https://github.com/epicmaxco/vuestic-admin/wiki/Charts',
            },
            children: [
              {
                name: 'bar',
                path: 'bar',
                component: () => import('@/pages/admin/statistics/charts/Charts.vue'),
              },
              {
                name: 'line',
                path: 'line',
                component: () => import('@/pages/admin/statistics/charts/Charts.vue'),
              },
            ]
          },
          {
            name: 'progress-bars',
            path: 'progress-bars',
            component: () => import('@/pages/admin/statistics/progress-bars/ProgressBars.vue'),
            meta: {
              wikiLink: 'https://github.com/epicmaxco/vuestic-admin/wiki/Progress-Bars',
            },
          },
        ],
      },`

notice the charts as a :/type? in its parent route and the children bar and line (which can be stated as redundant since it is being mentioned as route params :/type? as above. 

But the real problem is when trying to build a dynamic menu which has programmatically added items to NavigationRoutes which have dynamic in nature. 

The current NavigationRoutes.js in vuestic-admin template code does not state any of such routes. 

When we try to add such a dynamic item to the NavigationRoutes, it either ends with Route not matched for example: 

When on URL : <localhost>/statistics/charts/bar or <localhost>/statistics/charts/<chart_id>{chart_id can be a string line kasdsd-12asdads}
The routes system fails with Route No Match Found, despite having the router/index.ts having the route params. 

Clearly this is a bug and an issue that needs to resolved and any help appreciated.

Cheers,

**Comment by asvae** [comment]
Should be fine right now.
