### ISSUE TITLE
Fix dashboard's form -> map connection

### ISSUE THREAD

**Issue by smellyshovel** [epicmaxco/vuestic-admin#877]
![Screenshot_20220705_113746](https://user-images.githubusercontent.com/9782236/177275332-98669cc3-17d6-423e-b514-0ab89748c6d0.png)

The map and the form should probably be somehow connected (interact with each other, or at least in one way: form -> map). At least the code looks so. But it's broken and should probably be fixed.

Doesn't work in the currently-deployed app, nor does it work after rewrite in #876.

**Comment by asvae** [comment]
We got rid of the map.
