### ISSUE TITLE
Switch in form elements page are not implemented correctly

### ISSUE THREAD

**Issue by khusroohayat** [epicmaxco/vuestic-admin#881]
**Note: for support questions, please use stackoverflow**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  -  bug report

* **Do you want to request a *feature* or report a *bug*?**
 - Bug
 
* **What is the current behavior?**
Switch are not disabled, and switch size are not according to label i.e small and large

* **If the current behavior is a bug, please provide the steps to reproduce, ideally also a screenshot or gif if it's a style issue**
1. go to https://vuestic.epicmax.co/admin/forms/form-elements
2. scroll down to last section
3. Yo will the switch are not implement according to their labels
4. ![firefox_x4FVE2AweP](https://user-images.githubusercontent.com/5275996/180000411-f9278b88-c438-4687-9b60-8c0d8f7f0d1e.png)

* **What is the expected behavior?**
It show the correct state as defined

**Comment by asvae** [comment]
Should be fixed.
