### ISSUE TITLE
Language localization for Bangla language

### ISSUE THREAD

**Issue by ShekharUllah06** [epicmaxco/vuestic-admin#895]
- **I'm submitting a ...**

  - [ ] feature request
 

- **Do you want to request a _feature_ or report a _bug_?**

   - feature request

- **What is the current behavior?**
   - There are no Bangla language option on language drop-down

- **What is the expected behavior?**
   - Expect Bangla option on language drop-down

- **What is the motivation / use case for changing the behavior?**
   - Language localization for Bangla language

- **Other information** 
   - I am interested to develop the feature

**Comment by asvae** [comment]
We decided to drop language support. Too easy to translate via external tools.
