### ISSUE TITLE
vuestic-admin for android and ios with cordova

### ISSUE THREAD

**Issue by michaelscheurer** [epicmaxco/vuestic-admin#92]
With [cordova](https://cordova.apache.org) you can distribute your vuestic-admin-app as a native android/ios/windows (and more) app. The builded vuejs files will be executed directly in the app (android, ios...) and thus don't have to be loaded from a server. 
It would be a perfect extension for vuestic-admin to support cordova by default. What do you think?
Cheers
Michael

**Comment by smartapant** [comment]
Hi @michaelscheurer 

We're not planning to support cordova, we're thinking about PWA :)

Anyway, it's quite easy to use vuestic as a cordova app, check out https://github.com/lesion/vue-webpack-cordova
