### ISSUE TITLE
Navbar doesn't look right on 1.8.0

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#951]
[Ihttp://localhost:5173/admin/dashboard](http://localhost:5173/admin/dashboard)

* branch - local develop

Might be something with vuestic ui. If it's a regression - ping maxim so that we can showcase this as a breaking change.

<img width="945" alt="image" src="https://github.com/epicmaxco/vuestic-admin/assets/5394573/cf308dd2-c21a-49f7-8122-dfb484232938">

<img width="1260" alt="image" src="https://github.com/epicmaxco/vuestic-admin/assets/5394573/0e97a30e-a451-458c-b0a3-6c4a810ccb6b">

**Comment by 0xffmeta** [comment]
Seems 1.8.3 still have this issue?
