### ISSUE TITLE
Error page

### ISSUE THREAD

**Issue by asvae** [epicmaxco/vuestic-admin#961]
https://www.figma.com/file/1FrFtIjHjMAV0o4t0wpYGq/Admin?node-id=367:622&mode=dev

Please only pick one design (I understand the choice is hard)

**Comment by asvae** [comment]
We still have some bugs on the page, so not closing

**Comment by m0ksem** [comment]
> We still have some bugs on the page, so not closing

@asvae, Can you specify which bug you found here?

**Comment by m0ksem** [comment]
Remove old 404 pages.

**Comment by asvae** [comment]
Seems to be done
